/**
 * Adyen logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/adyen).
 * Artwork: Simple Icons (CC0-1.0). Adyen is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type AdyenLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#0abf53" viewBox="0 0 24 24" {...props}><path d="M11.647 9.882v2.934c0 .134.109.243.243.243h.463V9.882h1.765v5.15c0 .47-.38.85-.85.85H9.943v-1.235h2.41v-.53h-1.621a.85.85 0 0 1-.85-.849V9.882zm-8.261 0c.469 0 .85.38.85.85v3.386H.85a.85.85 0 0 1-.85-.85v-.948c0-.469.38-.85.85-.85h.915v1.346c0 .134.108.243.242.243h.464v-1.875a.243.243 0 0 0-.243-.243H.06V9.882Zm5.79-1.764v6H5.791a.85.85 0 0 1-.85-.85v-2.536c0-.47.38-.85.85-.85h.915v2.934c0 .134.108.243.243.243h.463V8.118zm9.033 1.764a.85.85 0 0 1 .85.85v.948c0 .47-.38.85-.85.85h-.915v-1.346a.243.243 0 0 0-.243-.243h-.463v1.875c0 .134.109.243.243.243h2.167v1.059h-3.325a.85.85 0 0 1-.85-.85V9.882Zm4.942 0a.85.85 0 0 1 .849.85v3.386h-1.765v-2.934a.243.243 0 0 0-.242-.243h-.464v3.177h-1.764V9.882Z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.647 9.882v2.934c0 .134.109.243.243.243h.463V9.882h1.765v5.15c0 .47-.38.85-.85.85H9.943v-1.235h2.41v-.53h-1.621a.85.85 0 0 1-.85-.849V9.882zm-8.261 0c.469 0 .85.38.85.85v3.386H.85a.85.85 0 0 1-.85-.85v-.948c0-.469.38-.85.85-.85h.915v1.346c0 .134.108.243.242.243h.464v-1.875a.243.243 0 0 0-.243-.243H.06V9.882Zm5.79-1.764v6H5.791a.85.85 0 0 1-.85-.85v-2.536c0-.47.38-.85.85-.85h.915v2.934c0 .134.108.243.243.243h.463V8.118zm9.033 1.764a.85.85 0 0 1 .85.85v.948c0 .47-.38.85-.85.85h-.915v-1.346a.243.243 0 0 0-.243-.243h-.463v1.875c0 .134.109.243.243.243h2.167v1.059h-3.325a.85.85 0 0 1-.85-.85V9.882Zm4.942 0a.85.85 0 0 1 .849.85v3.386h-1.765v-2.934a.243.243 0 0 0-.242-.243h-.464v3.177h-1.764V9.882Z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 166" {...props}><path fill="#32aa52" d="M72.23 37.647c10.01 0 18.124 8.114 18.124 18.123V128H18.123C8.113 128 0 119.886 0 109.877V89.652c0-10.009 8.114-18.123 18.123-18.123h19.524v28.705a5.18 5.18 0 0 0 5.178 5.178h9.881v-40a5.18 5.18 0 0 0-5.178-5.177H1.294V37.647zm85.886 67.765L158.117 0h37.648v128h-72.23c-10.009 0-18.123-8.114-18.123-18.123V55.77c0-10.009 8.114-18.123 18.123-18.123h19.522v62.587a5.18 5.18 0 0 0 5.178 5.178zm105.412 0V37.647h37.649V147.52c0 10.01-8.114 18.123-18.123 18.123h-70.936v-26.348h51.411V128h-34.583c-10.009 0-18.123-8.114-18.123-18.123v-72.23h37.646v62.587a5.18 5.18 0 0 0 5.178 5.178zm124.937-67.765c10.009 0 18.123 8.114 18.123 18.123v20.225c0 10.01-8.114 18.123-18.123 18.123H368.94V65.414a5.177 5.177 0 0 0-5.178-5.178h-9.88v39.998a5.18 5.18 0 0 0 5.178 5.178h46.233V128h-70.935c-10.009 0-18.123-8.114-18.123-18.123v-72.23zm105.412 0c10.01 0 18.123 8.114 18.123 18.123V128h-37.647V65.413c0-2.848-2.33-5.178-5.178-5.178h-9.881V128h-37.648V37.647z" /></svg>;

export function AdyenLogo({
  variant = "color",
  type = "icon",
  title = "Adyen",
  className,
  ...props
}: AdyenLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return <Wordmark {...shared} className={className} />;
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default AdyenLogo;
