/**
 * Alpine Linux logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/alpine-linux).
 * Artwork: Simple Icons (CC0-1.0). Alpine Linux is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type AlpineLinuxLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#0d597f" viewBox="0 0 24 24" {...props}><path d="M5.998 1.607 0 12l5.998 10.393h12.004L24 12 18.002 1.607zM9.965 7.12 12.66 9.9l1.598 1.595.002-.002 2.41 2.363q-.299.208-.563.344a4 4 0 0 1-.496.217 3 3 0 0 1-.425.111q-.196.034-.358.034-.194-.002-.338-.034a1.3 1.3 0 0 1-.24-.072 1 1 0 0 1-.2-.113l-1.062-1.092-3.039-3.041-1.1 1.053-3.07 3.072a1 1 0 0 1-.2.111 1.3 1.3 0 0 1-.237.073 1.7 1.7 0 0 1-.338.033q-.162.001-.358-.031a3 3 0 0 1-.425-.114 4 4 0 0 1-.496-.217 5 5 0 0 1-.563-.343zm4.72.785 4.579 4.598 1.382 1.353a5 5 0 0 1-.564.344 4 4 0 0 1-.494.217 3 3 0 0 1-.426.111q-.196.034-.36.034-.193-.002-.337-.034a1.3 1.3 0 0 1-.385-.146.2.2 0 0 1-.053-.04l-1.232-1.218-2.111-2.111-.334.334L12.79 9.8l1.896-1.897zm-5.966 4.12v2.529a2 2 0 0 1-.356-.035 3 3 0 0 1-.422-.116 4 4 0 0 1-.488-.214 5 5 0 0 1-.555-.34l1.82-1.825Z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M5.998 1.607 0 12l5.998 10.393h12.004L24 12 18.002 1.607zM9.965 7.12 12.66 9.9l1.598 1.595.002-.002 2.41 2.363q-.299.208-.563.344a4 4 0 0 1-.496.217 3 3 0 0 1-.425.111q-.196.034-.358.034-.194-.002-.338-.034a1.3 1.3 0 0 1-.24-.072 1 1 0 0 1-.2-.113l-1.062-1.092-3.039-3.041-1.1 1.053-3.07 3.072a1 1 0 0 1-.2.111 1.3 1.3 0 0 1-.237.073 1.7 1.7 0 0 1-.338.033q-.162.001-.358-.031a3 3 0 0 1-.425-.114 4 4 0 0 1-.496-.217 5 5 0 0 1-.563-.343zm4.72.785 4.579 4.598 1.382 1.353a5 5 0 0 1-.564.344 4 4 0 0 1-.494.217 3 3 0 0 1-.426.111q-.196.034-.36.034-.193-.002-.337-.034a1.3 1.3 0 0 1-.385-.146.2.2 0 0 1-.053-.04l-1.232-1.218-2.111-2.111-.334.334L12.79 9.8l1.896-1.897zm-5.966 4.12v2.529a2 2 0 0 1-.356-.035 3 3 0 0 1-.422-.116 4 4 0 0 1-.488-.214 5 5 0 0 1-.555-.34l1.82-1.825Z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#0e638d" viewBox="0 0 24 24" {...props}><path d="M5.998 1.607 0 12l5.998 10.393h12.004L24 12 18.002 1.607zM9.965 7.12 12.66 9.9l1.598 1.595.002-.002 2.41 2.363q-.299.208-.563.344a4 4 0 0 1-.496.217 3 3 0 0 1-.425.111q-.196.034-.358.034-.194-.002-.338-.034a1.3 1.3 0 0 1-.24-.072 1 1 0 0 1-.2-.113l-1.062-1.092-3.039-3.041-1.1 1.053-3.07 3.072a1 1 0 0 1-.2.111 1.3 1.3 0 0 1-.237.073 1.7 1.7 0 0 1-.338.033q-.162.001-.358-.031a3 3 0 0 1-.425-.114 4 4 0 0 1-.496-.217 5 5 0 0 1-.563-.343zm4.72.785 4.579 4.598 1.382 1.353a5 5 0 0 1-.564.344 4 4 0 0 1-.494.217 3 3 0 0 1-.426.111q-.196.034-.36.034-.193-.002-.337-.034a1.3 1.3 0 0 1-.385-.146.2.2 0 0 1-.053-.04l-1.232-1.218-2.111-2.111-.334.334L12.79 9.8l1.896-1.897zm-5.966 4.12v2.529a2 2 0 0 1-.356-.035 3 3 0 0 1-.422-.116 4 4 0 0 1-.488-.214 5 5 0 0 1-.555-.34l1.82-1.825Z" /></svg>;

export function AlpineLinuxLogo({
  variant = "color",
  mode = "auto",
  title = "Alpine Linux",
  className,
  ...props
}: AlpineLinuxLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default AlpineLinuxLogo;
