/**
 * Appium logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/appium).
 * Artwork: gilbarbara/logos (CC0-1.0). Appium is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type AppiumLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><path fill="#662d91" d="M.295 119.397c24.814 57.004 87.778 66.563 162.925 18.246 34.66 32.08 43.295 70.11 14.374 108.392C162.341 252.451 145.586 256 128 256 57.308 256 0 198.692 0 128c0-2.89.106-5.758.295-8.602m117.059-24.744c11.205-46.695 42.494-73.48 91.678-65.737C237.702 52.39 256 88.056 256 128c0 50.395-29.126 93.979-71.46 114.857 38.457-54.784 7.03-112.584-67.186-148.204M128 0c27.435 0 52.85 8.635 73.687 23.33-69.951-8.132-102.984 50.175-98.37 130.694-45.452 13.941-82.48 3.669-102.048-44.047C10.03 47.819 63.427 0 128 0" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.923 0C5.937 0 .976 4.384.07 10.115a11.94 11.94 0 0 1 7.645-2.754 11.98 11.98 0 0 1 9.43 4.58 11.94 11.94 0 0 0 1.015-8.769 12 12 0 0 0-.626-1.772l-.003-.008A12 12 0 0 0 11.923 0m7.721 2.754A12 12 0 0 1 9.398 16.521a12.08 12.08 0 0 0 9.02 5.617c.24-.119.766-.51 1.224-.89A11.97 11.97 0 0 0 23.995 12a11.98 11.98 0 0 0-4.35-9.247zM9.33 7.557a12 12 0 0 0-2.647.401A11.94 11.94 0 0 0 .01 12.595l-.005.006q.032.641.131 1.275C1.037 19.61 6 24 11.991 24c1.45 0 2.887-.26 4.243-.773a12 12 0 0 1-6.905-15.67z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><path fill="#873bc0" d="M.295 119.397c24.814 57.004 87.778 66.563 162.925 18.246 34.66 32.08 43.295 70.11 14.374 108.392C162.341 252.451 145.586 256 128 256 57.308 256 0 198.692 0 128c0-2.89.106-5.758.295-8.602m117.059-24.744c11.205-46.695 42.494-73.48 91.678-65.737C237.702 52.39 256 88.056 256 128c0 50.395-29.126 93.979-71.46 114.857 38.457-54.784 7.03-112.584-67.186-148.204M128 0c27.435 0 52.85 8.635 73.687 23.33-69.951-8.132-102.984 50.175-98.37 130.694-45.452 13.941-82.48 3.669-102.048-44.047C10.03 47.819 63.427 0 128 0" /></svg>;

export function AppiumLogo({
  variant = "color",
  mode = "auto",
  title = "Appium",
  className,
  ...props
}: AppiumLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default AppiumLogo;
