/**
 * AWS API Gateway logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/aws-api-gateway).
 * Artwork: gilbarbara/logos (CC0-1.0). AWS API Gateway is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type AwsApiGatewayLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><defs><linearGradient id="aws-api-gateway-a" x1="0%" x2="100%" y1="100%" y2="0%"><stop offset="0%" stopColor="#b0084d" /><stop offset="100%" stopColor="#ff4f8b" /></linearGradient></defs><path fill="url(#aws-api-gateway-a)" d="M0 0h256v256H0z" /><path fill="#fff" d="M109.008 178.024h9.392v-6.455h-9.392zm15.792 0h9.6v-6.455h-9.6zM86.4 46.814 44.8 67.463v128.356l41.6 14.068zm6.4 40.845v83.91h9.6v6.455h-9.6v36.349a3.24 3.24 0 0 1-1.331 2.62 3.18 3.18 0 0 1-2.887.44l-48-16.23a3.23 3.23 0 0 1-2.182-3.06V65.452c0-1.226.694-2.353 1.789-2.895l48-23.824a3.16 3.16 0 0 1 3.1.155 3.23 3.23 0 0 1 1.511 2.74v39.576h9.6v6.455zm48 90.365h9.6v-6.455h-9.6zm.208-90.365h9.392v-6.455h-9.392zm-16 0h9.392v-6.455h-9.392zm-16 0h9.392v-6.455h-9.392zM211.2 67.463l-41.6-20.649v163.073l41.6-14.068zm6.4 130.68a3.23 3.23 0 0 1-2.182 3.06l-48 16.23a3.17 3.17 0 0 1-2.887-.44 3.24 3.24 0 0 1-1.331-2.62v-36.35h-6.192v-6.454h6.192v-83.91h-6.192v-6.455h6.192V41.628c0-1.117.573-2.153 1.51-2.74a3.16 3.16 0 0 1 3.101-.155l48 23.824a3.23 3.23 0 0 1 1.789 2.895zm-80.211-89.962-5.978-2.317-16 41.955 5.978 2.317zm21.673 20.487a3.243 3.243 0 0 0 0-4.563l-12.8-12.91-4.524 4.564 10.537 10.628-10.537 10.627 4.524 4.564zm-49.324 12.91-12.8-12.91a3.243 3.243 0 0 1 0-4.563l12.8-12.91 4.524 4.564-10.537 10.628 10.537 10.627z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><defs><mask id="aws-api-gateway-mono-cut-mono" maskUnits="userSpaceOnUse" x={0} y={0} width={256} height={256}><g fill="#fff"><defs><linearGradient id="aws-api-gateway-a-mono" x1="0%" x2="100%" y1="100%" y2="0%"><stop offset="0%" stopColor="#fff" /><stop offset="100%" stopColor="#fff" /></linearGradient></defs><path fill="#fff" d="M0 0h256v256H0z" /><path fill="#000" d="M109.008 178.024h9.392v-6.455h-9.392zm15.792 0h9.6v-6.455h-9.6zM86.4 46.814 44.8 67.463v128.356l41.6 14.068zm6.4 40.845v83.91h9.6v6.455h-9.6v36.349a3.24 3.24 0 0 1-1.331 2.62 3.18 3.18 0 0 1-2.887.44l-48-16.23a3.23 3.23 0 0 1-2.182-3.06V65.452c0-1.226.694-2.353 1.789-2.895l48-23.824a3.16 3.16 0 0 1 3.1.155 3.23 3.23 0 0 1 1.511 2.74v39.576h9.6v6.455zm48 90.365h9.6v-6.455h-9.6zm.208-90.365h9.392v-6.455h-9.392zm-16 0h9.392v-6.455h-9.392zm-16 0h9.392v-6.455h-9.392zM211.2 67.463l-41.6-20.649v163.073l41.6-14.068zm6.4 130.68a3.23 3.23 0 0 1-2.182 3.06l-48 16.23a3.17 3.17 0 0 1-2.887-.44 3.24 3.24 0 0 1-1.331-2.62v-36.35h-6.192v-6.454h6.192v-83.91h-6.192v-6.455h6.192V41.628c0-1.117.573-2.153 1.51-2.74a3.16 3.16 0 0 1 3.101-.155l48 23.824a3.23 3.23 0 0 1 1.789 2.895zm-80.211-89.962-5.978-2.317-16 41.955 5.978 2.317zm21.673 20.487a3.243 3.243 0 0 0 0-4.563l-12.8-12.91-4.524 4.564 10.537 10.628-10.537 10.627 4.524 4.564zm-49.324 12.91-12.8-12.91a3.243 3.243 0 0 1 0-4.563l12.8-12.91 4.524 4.564-10.537 10.628 10.537 10.627z" /></g></mask></defs><rect x={0} y={0} width={256} height={256} fill="currentColor" mask="url(#aws-api-gateway-mono-cut-mono)" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><defs><linearGradient id="aws-api-gateway-a-dark" x1="0%" x2="100%" y1="100%" y2="0%"><stop offset="0%" stopColor="#bf0953" /><stop offset="100%" stopColor="#ff4f8b" /></linearGradient></defs><path fill="url(#aws-api-gateway-a-dark)" d="M0 0h256v256H0z" /><path fill="#fff" d="M109.008 178.024h9.392v-6.455h-9.392zm15.792 0h9.6v-6.455h-9.6zM86.4 46.814 44.8 67.463v128.356l41.6 14.068zm6.4 40.845v83.91h9.6v6.455h-9.6v36.349a3.24 3.24 0 0 1-1.331 2.62 3.18 3.18 0 0 1-2.887.44l-48-16.23a3.23 3.23 0 0 1-2.182-3.06V65.452c0-1.226.694-2.353 1.789-2.895l48-23.824a3.16 3.16 0 0 1 3.1.155 3.23 3.23 0 0 1 1.511 2.74v39.576h9.6v6.455zm48 90.365h9.6v-6.455h-9.6zm.208-90.365h9.392v-6.455h-9.392zm-16 0h9.392v-6.455h-9.392zm-16 0h9.392v-6.455h-9.392zM211.2 67.463l-41.6-20.649v163.073l41.6-14.068zm6.4 130.68a3.23 3.23 0 0 1-2.182 3.06l-48 16.23a3.17 3.17 0 0 1-2.887-.44 3.24 3.24 0 0 1-1.331-2.62v-36.35h-6.192v-6.454h6.192v-83.91h-6.192v-6.455h6.192V41.628c0-1.117.573-2.153 1.51-2.74a3.16 3.16 0 0 1 3.101-.155l48 23.824a3.23 3.23 0 0 1 1.789 2.895zm-80.211-89.962-5.978-2.317-16 41.955 5.978 2.317zm21.673 20.487a3.243 3.243 0 0 0 0-4.563l-12.8-12.91-4.524 4.564 10.537 10.628-10.537 10.627 4.524 4.564zm-49.324 12.91-12.8-12.91a3.243 3.243 0 0 1 0-4.563l12.8-12.91 4.524 4.564-10.537 10.628 10.537 10.627z" /></svg>;

export function AwsApiGatewayLogo({
  variant = "color",
  mode = "auto",
  title = "AWS API Gateway",
  className,
  ...props
}: AwsApiGatewayLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default AwsApiGatewayLogo;
