/**
 * Blueprint logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/blueprint).
 * Artwork: gilbarbara/logos (CC0-1.0). Blueprint is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type BlueprintLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 298" {...props}><path fill="#00b46f" d="m192 112.384 64 37.943v74.441l-64 36.48-64-36.48v-74.423" /><path fill="#2294d9" d="m128 0 64 37.943v74.441l-64 36.48-64-36.48V37.961" /><path fill="#2294d9" d="m192 37.943 64 37.943v74.45l-64 36.48-64-36.48v-74.45" /><path fill="#f85551" d="m64 37.943 64 37.943v74.45l-64 36.48-64-36.48v-74.45" /><path fill="#f85551" d="m64 112.384 64 37.943v74.441l-64 36.48-64-36.48v-74.423" /><path fill="#00b46f" d="m128 148.873 64 37.943v74.441l-64 36.48-64-36.48v-74.441" /><path fill="#30b2e9" d="m192 37.943-64 37.943-64-37.943L128 0zm64 37.943-64 37.96-64-37.942 64-37.943 64 37.943z" /><path fill="#00ab64" d="M128 223.305v-74.423l-64 37.943v74.423" /><path fill="#00ce8e" d="m192 186.816-64 36.48-64-36.48 64-37.943" /><path fill="#00c783" d="m128 223.305-64-36.48 64-37.943z" /><path fill="#2caee7" d="M128 75.886 64 37.943 128 0z" /><path fill="#fb716c" d="m128 75.886-64 37.96L0 75.905l64-37.943" /><path fill="#1f8ed6" d="m256 150.336-64 36.48-64-37.943 64-35.017" /><path fill="#f64743" d="M63.013 260.626 0 224.146l63.013-37.96z" /><path fill="#f96560" d="M64 113.847V37.96l64 37.943v72.96" /><path fill="#b71d1d" d="M128 148.873V75.886l-64 37.96v72.96" /><path fill="#b21a1a" d="m128 148.873-64-35.017 64-37.97z" /><path fill="#10161a" fillOpacity={0.2} d="m256 224.768-64-37.943 64-36.48z" style={{
    mixBlendMode: "soft-light"
  }} /><path fill="#007233" d="M192 261.257v-74.441l-64 36.48v74.45l64-36.48zm64-36.48v-74.441l-64 36.48v74.441z" /><path fill="#00682c" d="m256 224.768-64-37.943 64-36.48z" /><path fill="#0759ba" d="M256 150.336v-74.45l-64 37.96v72.96" /><path fill="#0860bf" d="m256 150.336-64-36.48 64-37.97z" /><path fill="#febcb7" d="m0 75.886 64 36.498 64-36.48-62.537 38.674L64 186.514c0 .028 0 0 0 0l-1.463-71.954z" opacity={0.78} /><path fill="#4edcf8" d="m128 75.886 64 36.498 64-36.48-62.537 38.674L192 186.807l-1.463-72.229" opacity={0.78} /><path fill="#00f3c9" d="m64 186.816 64 35.035 64-35.035-62.537 37.211L128 297.691c0 .028 0 0 0 0l-1.463-73.654L64 186.825z" opacity={0.78} /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M21.809 5.524 12.806.179l-.013-.007.078-.045h-.166a1.28 1.28 0 0 0-1.196.043l-.699.403-8.604 4.954a1.29 1.29 0 0 0-.644 1.113v10.718c0 .46.245.884.644 1.113l9.304 5.357c.402.232.898.228 1.297-.009l9.002-5.345c.39-.231.629-.651.629-1.105V6.628c0-.453-.239-.873-.629-1.104m-19.282.559L11.843.719a.64.64 0 0 1 .636.012l9.002 5.345a.64.64 0 0 1 .207.203l-4.543 2.555-4.498-2.7a.96.96 0 0 0-.968-.014L6.83 8.848 2.287 6.329a.64.64 0 0 1 .24-.246m14.13 8.293-4.496-2.492V6.641a.3.3 0 0 1 .155.045l4.341 2.605zm-4.763-1.906 4.692 2.601-4.431 2.659-4.648-2.615a.3.3 0 0 1-.115-.112zm-.064 10.802-9.304-5.357a.64.64 0 0 1-.322-.557V7.018L6.7 9.51v5.324c0 .348.188.669.491.84l4.811 2.706.157.088v4.887a.64.64 0 0 1-.329-.083" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 298" {...props}><path fill="#00b46f" d="m192 112.384 64 37.943v74.441l-64 36.48-64-36.48v-74.423" /><path fill="#2294d9" d="m128 0 64 37.943v74.441l-64 36.48-64-36.48V37.961" /><path fill="#2294d9" d="m192 37.943 64 37.943v74.45l-64 36.48-64-36.48v-74.45" /><path fill="#f85551" d="m64 37.943 64 37.943v74.45l-64 36.48-64-36.48v-74.45" /><path fill="#f85551" d="m64 112.384 64 37.943v74.441l-64 36.48-64-36.48v-74.423" /><path fill="#00b46f" d="m128 148.873 64 37.943v74.441l-64 36.48-64-36.48v-74.441" /><path fill="#30b2e9" d="m192 37.943-64 37.943-64-37.943L128 0zm64 37.943-64 37.96-64-37.942 64-37.943 64 37.943z" /><path fill="#00ab64" d="M128 223.305v-74.423l-64 37.943v74.423" /><path fill="#00ce8e" d="m192 186.816-64 36.48-64-36.48 64-37.943" /><path fill="#00c783" d="m128 223.305-64-36.48 64-37.943z" /><path fill="#2caee7" d="M128 75.886 64 37.943 128 0z" /><path fill="#fb716c" d="m128 75.886-64 37.96L0 75.905l64-37.943" /><path fill="#1f8ed6" d="m256 150.336-64 36.48-64-37.943 64-35.017" /><path fill="#f64743" d="M63.013 260.626 0 224.146l63.013-37.96z" /><path fill="#f96560" d="M64 113.847V37.96l64 37.943v72.96" /><path fill="#b71d1d" d="M128 148.873V75.886l-64 37.96v72.96" /><path fill="#bf1c1c" d="m128 148.873-64-35.017 64-37.97z" /><path fill="#ffffff" fillOpacity={0.2} d="m256 224.768-64-37.943 64-36.48z" style={{
    mixBlendMode: "soft-light"
  }} /><path fill="#007233" d="M192 261.257v-74.441l-64 36.48v74.45l64-36.48zm64-36.48v-74.441l-64 36.48v74.441z" /><path fill="#007732" d="m256 224.768-64-37.943 64-36.48z" /><path fill="#0860c9" d="M256 150.336v-74.45l-64 37.96v72.96" /><path fill="#0860bf" d="m256 150.336-64-36.48 64-37.97z" /><path fill="#febcb7" d="m0 75.886 64 36.498 64-36.48-62.537 38.674L64 186.514c0 .028 0 0 0 0l-1.463-71.954z" opacity={0.78} /><path fill="#4edcf8" d="m128 75.886 64 36.498 64-36.48-62.537 38.674L192 186.807l-1.463-72.229" opacity={0.78} /><path fill="#00f3c9" d="m64 186.816 64 35.035 64-35.035-62.537 37.211L128 297.691c0 .028 0 0 0 0l-1.463-73.654L64 186.825z" opacity={0.78} /></svg>;

export function BlueprintLogo({
  variant = "color",
  mode = "auto",
  title = "Blueprint",
  className,
  ...props
}: BlueprintLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default BlueprintLogo;
