/**
 * C logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/c).
 * Artwork: gilbarbara/logos (CC0-1.0). C is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type CLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 288" {...props}><path fill="#a9b9cb" d="M255.987 85.672c-.002-4.843-1.037-9.122-3.129-12.794-2.055-3.612-5.134-6.638-9.262-9.032-34.081-19.67-68.195-39.28-102.264-58.97-9.185-5.307-18.091-5.114-27.208.27-13.565 8.008-81.481 46.956-101.719 58.689C4.071 68.665.015 76.056.013 85.663 0 125.221.013 164.777 0 204.336c.002 4.736.993 8.932 2.993 12.55 2.056 3.72 5.177 6.83 9.401 9.278 20.239 11.733 88.164 50.678 101.726 58.688 9.121 5.387 18.027 5.579 27.215.27 34.07-19.691 68.186-39.3 102.272-58.97 4.224-2.447 7.345-5.559 9.401-9.276 1.997-3.618 2.99-7.814 2.992-12.551 0 0 0-79.094-.013-118.653" /><path fill="#7f8b99" d="M141.101 5.134c-9.17-5.294-18.061-5.101-27.163.269C100.395 13.39 32.59 52.237 12.385 63.94 4.064 68.757.015 76.129.013 85.711 0 125.166.013 164.62 0 204.076c.002 4.724.991 8.909 2.988 12.517 2.053 3.711 5.169 6.813 9.386 9.254a9009 9009 0 0 0 20.159 11.62L219.625 50.375c-26.178-15.074-52.363-30.136-78.524-45.241" /><path fill="#fff" d="m154.456 126.968 39.839.281c0-16.599-16.802-57.249-64.973-57.249-30.691 0-71.951 19.512-71.951 75.61S97.818 220 129.322 220c51.017 0 63.21-35.302 63.21-55.252l-38.007-2.173s1.017 23.075-25.406 23.075c-24.39 0-28.46-29.878-28.46-40.04 0-15.447 5.493-40.244 28.46-40.244 22.968 0 25.337 21.602 25.337 21.602" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M16.592 9.196s-.354-3.298-3.627-3.39c-3.274-.09-4.955 2.474-4.955 6.14s1.858 6.597 5.045 6.597c3.184 0 3.538-3.665 3.538-3.665l6.104.365s.36 3.31-2.196 5.836c-2.552 2.524-5.69 2.937-7.876 2.92-2.19-.016-5.226.035-8.16-2.97-2.938-3.01-3.436-5.93-3.436-8.8s.556-6.67 4.047-9.55C7.444.72 9.849 0 12.254 0c10.042 0 10.717 9.26 10.717 9.26z" /></svg>;

export function CLogo({
  variant = "color",
  title = "C",
  className,
  ...props
}: CLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default CLogo;
