/**
 * Chainlink logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/chainlink).
 * Artwork: Simple Icons (CC0-1.0). Chainlink is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ChainlinkLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#375bd2" viewBox="0 0 24 24" {...props}><path d="M12 0 9.798 1.266l-6 3.468L1.596 6v12l2.202 1.266 6.055 3.468L12.055 24l2.202-1.266 5.945-3.468L22.404 18V6l-2.202-1.266-6-3.468zM6 15.468V8.532l6-3.468 6 3.468v6.936l-6 3.468z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12 0 9.798 1.266l-6 3.468L1.596 6v12l2.202 1.266 6.055 3.468L12.055 24l2.202-1.266 5.945-3.468L22.404 18V6l-2.202-1.266-6-3.468zM6 15.468V8.532l6-3.468 6 3.468v6.936l-6 3.468z" /></svg>;

export function ChainlinkLogo({
  variant = "color",
  title = "Chainlink",
  className,
  ...props
}: ChainlinkLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default ChainlinkLogo;
