/**
 * CocoaPods logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/cocoapods).
 * Artwork: gilbarbara/logos (CC0-1.0). CocoaPods is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type CocoapodsLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#fa2a00" d="M255.349 255.35H0V0h255.349z" /><path fill="#fff" d="M160.993 135.984c-3.837 21.052-21.917 38.274-49.807 38.274-33.316 0-53.375-24.471-53.375-52.361 0-27.33 19.066-52.389 53.084-52.389 29.18 0 47.261 18.357 49.956 41.267H136.8c-2.128-11.667-10.959-20.484-25.613-20.484-19.08 0-29.89 15.086-29.89 31.606 0 17.499 12.094 31.593 30.174 31.593 13.377 0 22.2-7.689 25.045-17.506zm27.937-64.149-14.698 6.298 18.42 43.076-18.427 43.09 14.704 6.285 12.363-29.117.064.134 8.554-20.392z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><defs><mask id="cocoapods-mono-cut-mono" maskUnits="userSpaceOnUse" x={0} y={0} width={256} height={256}><g fill="#000"><path fill="#fff" d="M255.349 255.35H0V0h255.349z" /><path fill="#000" d="M160.993 135.984c-3.837 21.052-21.917 38.274-49.807 38.274-33.316 0-53.375-24.471-53.375-52.361 0-27.33 19.066-52.389 53.084-52.389 29.18 0 47.261 18.357 49.956 41.267H136.8c-2.128-11.667-10.959-20.484-25.613-20.484-19.08 0-29.89 15.086-29.89 31.606 0 17.499 12.094 31.593 30.174 31.593 13.377 0 22.2-7.689 25.045-17.506zm27.937-64.149-14.698 6.298 18.42 43.076-18.427 43.09 14.704 6.285 12.363-29.117.064.134 8.554-20.392z" /></g></mask></defs><rect x={0} y={0} width={256} height={256} fill="currentColor" mask="url(#cocoapods-mono-cut-mono)" /></svg>;

export function CocoapodsLogo({
  variant = "color",
  title = "CocoaPods",
  className,
  ...props
}: CocoapodsLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default CocoapodsLogo;
