/**
 * Codacy logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/codacy).
 * Artwork: gilbarbara/logos (CC0-1.0). Codacy is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type CodacyLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><path d="m41.416 104.612-37.07-9.919A128.13 128.13 0 0 1 63.964 17.13l19.174 33.183a89.73 89.73 0 0 0-41.722 54.3m63.35-63.248-9.97-37.069A128.3 128.3 0 0 1 127.875 0v38.348a90 90 0 0 0-23.11 3.016m46.477 0 9.92-37.018a128.18 128.18 0 0 1 77.564 59.516l-33.235 19.173a89.73 89.73 0 0 0-54.249-41.67M0 127.825h38.348a89.2 89.2 0 0 0 3.016 23.111l-37.069 9.92A127.8 127.8 0 0 1 0 127.826m17.129 63.913 33.388-19.174a91 91 0 0 0 14.214 18.51l-27.15 27.098a127.8 127.8 0 0 1-20.452-26.434m46.835 46.784 19.174-33.183a89.1 89.1 0 0 0 44.688 11.964v38.348a127.16 127.16 0 0 1-63.862-17.129m141.477-65.855 33.183 19.225a128.18 128.18 0 0 1-77.615 59.464l-9.92-37.07a89.73 89.73 0 0 0 54.352-41.62m46.017-10.482-36.865-10.124a89.4 89.4 0 0 0 0-46.426l37.172-9.92a128.1 128.1 0 0 1-.307 66.47" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M3.883 9.825a8.46 8.46 0 0 1 3.875-5.07l.04-.021-1.803-3.113C3.276 3.212 1.268 5.769.427 8.81l-.02.084zm5.941-5.931a8.3 8.3 0 0 1 2.164-.283h.005V.016h-.019a12 12 0 0 0-3.165.421l.084-.02zm4.354.003a8.45 8.45 0 0 1 5.063 3.875l.021.04 3.117-1.799c-1.591-2.718-4.146-4.726-7.186-5.568l-.084-.02zM0 12v.006c0 1.1.148 2.165.425 3.177l-.02-.084 3.476-.929a8 8 0 0 1-.284-2.161v-.008zm1.605 5.995c.55.941 1.18 1.754 1.901 2.475l2.553-2.54a8.6 8.6 0 0 1-1.313-1.695l-.022-.04zm4.39 4.385a11.77 11.77 0 0 0 5.967 1.604h.021-.001v-3.595h-.004a8.3 8.3 0 0 1-4.223-1.145l.039.021zm13.264-6.175a8.44 8.44 0 0 1-5.034 3.884l-.059.014.931 3.476c3.124-.86 5.681-2.863 7.246-5.52l.031-.056zm4.318-.984c.268-.947.423-2.035.423-3.159 0-1.087-.144-2.14-.415-3.142l.019.084-3.486.931c.175.64.275 1.374.275 2.132 0 .79-.109 1.555-.313 2.28l.014-.059z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><path d="m41.416 104.612-37.07-9.919A128.13 128.13 0 0 1 63.964 17.13l19.174 33.183a89.73 89.73 0 0 0-41.722 54.3m63.35-63.248-9.97-37.069A128.3 128.3 0 0 1 127.875 0v38.348a90 90 0 0 0-23.11 3.016m46.477 0 9.92-37.018a128.18 128.18 0 0 1 77.564 59.516l-33.235 19.173a89.73 89.73 0 0 0-54.249-41.67M0 127.825h38.348a89.2 89.2 0 0 0 3.016 23.111l-37.069 9.92A127.8 127.8 0 0 1 0 127.826m17.129 63.913 33.388-19.174a91 91 0 0 0 14.214 18.51l-27.15 27.098a127.8 127.8 0 0 1-20.452-26.434m46.835 46.784 19.174-33.183a89.1 89.1 0 0 0 44.688 11.964v38.348a127.16 127.16 0 0 1-63.862-17.129m141.477-65.855 33.183 19.225a128.18 128.18 0 0 1-77.615 59.464l-9.92-37.07a89.73 89.73 0 0 0 54.352-41.62m46.017-10.482-36.865-10.124a89.4 89.4 0 0 0 0-46.426l37.172-9.92a128.1 128.1 0 0 1-.307 66.47" /></svg>;

export function CodacyLogo({
  variant = "color",
  mode = "auto",
  title = "Codacy",
  className,
  ...props
}: CodacyLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default CodacyLogo;
