/**
 * Coding Dojo logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/coding-dojo).
 * Artwork: Coding Dojo (trademark). Coding Dojo is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type CodingDojoLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -5 44 44" {...props}><path fillRule="evenodd" d="M.484.48c.267.264 1.88 1.801 3.587 3.417l3.102 2.936h2.651v5.044h-1.78v5.125h1.78v17.001h5.337v-16.92h13.504v16.92h5.337V17.002h1.78v-5.125h-1.78V6.833h2.651l3.102-2.936A505 505 0 0 0 43.341.48l.485-.48H0zm28.262 8.794v2.603H15.08V6.67h13.666z" clipRule="evenodd" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 -5 44 44" {...props}><path fillRule="evenodd" d="M.484.48c.267.264 1.88 1.801 3.587 3.417l3.102 2.936h2.651v5.044h-1.78v5.125h1.78v17.001h5.337v-16.92h13.504v16.92h5.337V17.002h1.78v-5.125h-1.78V6.833h2.651l3.102-2.936A505 505 0 0 0 43.341.48l.485-.48H0zm28.262 8.794v2.603H15.08V6.67h13.666z" clipRule="evenodd" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 -5 44 44" {...props}><path fillRule="evenodd" d="M.484.48c.267.264 1.88 1.801 3.587 3.417l3.102 2.936h2.651v5.044h-1.78v5.125h1.78v17.001h5.337v-16.92h13.504v16.92h5.337V17.002h1.78v-5.125h-1.78V6.833h2.651l3.102-2.936A505 505 0 0 0 43.341.48l.485-.48H0zm28.262 8.794v2.603H15.08V6.67h13.666z" clipRule="evenodd" /></svg>;

export function CodingDojoLogo({
  variant = "color",
  mode = "auto",
  title = "Coding Dojo",
  className,
  ...props
}: CodingDojoLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default CodingDojoLogo;
