/**
 * .NET logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/dotnet).
 * Artwork: gilbarbara/logos (CC0-1.0). .NET is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type DotnetLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#512bd4" d="M0 0h256v256H0z" /><path fill="#fff" d="M45.627 163.555q-2.715 0-4.615-1.809-1.9-1.856-1.901-4.408 0-2.598 1.9-4.454 1.901-1.856 4.616-1.856 2.76 0 4.661 1.856 1.946 1.856 1.946 4.454 0 2.551-1.946 4.408-1.9 1.81-4.66 1.81m72.361-1.02h-11.765L75.225 113.63a22 22 0 0 1-1.946-3.85h-.272l.047.305.043.35.04.393.038.436.049.736.042.832.035.93.028 1.028.02 1.125.01.805.01 2.2v43.614H62.961V96h12.535l29.957 47.743.74 1.169.477.768.408.675.34.583.19.338.16.296.13.255h.18l-.034-.21-.064-.45-.06-.493-.053-.537-.024-.285-.046-.602-.04-.645-.035-.69-.042-1.114-.03-1.212-.018-1.31-.006-1.407V96h10.362zm50.685 0h-36.428V96h34.98v9.373h-24.21v18.837h22.31v9.326h-22.31v19.673h25.658zm51.772-57.162H201.8v57.162h-10.77v-57.162h-18.6V96h48.014z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M24 8.77h-2.468v7.565h-1.425V8.77h-2.462V7.53H24zm-6.852 7.565h-4.821V7.53h4.63v1.24h-3.205v2.494h2.953v1.234h-2.953v2.604h3.396zm-6.708 0H8.882L4.78 9.863a3 3 0 0 1-.258-.51h-.036q.048.283.048 1.21v5.772H3.157V7.53h1.659l3.965 6.32q.25.392.323.54h.024q-.06-.35-.06-1.185V7.529h1.372zm-8.703-.693a.868.829 0 0 1-.869.829.868.829 0 0 1-.868-.83.868.829 0 0 1 .868-.828.868.829 0 0 1 .869.829" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#6644d9" d="M0 0h256v256H0z" /><path fill="#fff" d="M45.627 163.555q-2.715 0-4.615-1.809-1.9-1.856-1.901-4.408 0-2.598 1.9-4.454 1.901-1.856 4.616-1.856 2.76 0 4.661 1.856 1.946 1.856 1.946 4.454 0 2.551-1.946 4.408-1.9 1.81-4.66 1.81m72.361-1.02h-11.765L75.225 113.63a22 22 0 0 1-1.946-3.85h-.272l.047.305.043.35.04.393.038.436.049.736.042.832.035.93.028 1.028.02 1.125.01.805.01 2.2v43.614H62.961V96h12.535l29.957 47.743.74 1.169.477.768.408.675.34.583.19.338.16.296.13.255h.18l-.034-.21-.064-.45-.06-.493-.053-.537-.024-.285-.046-.602-.04-.645-.035-.69-.042-1.114-.03-1.212-.018-1.31-.006-1.407V96h10.362zm50.685 0h-36.428V96h34.98v9.373h-24.21v18.837h22.31v9.326h-22.31v19.673h25.658zm51.772-57.162H201.8v57.162h-10.77v-57.162h-18.6V96h48.014z" /></svg>;

export function DotnetLogo({
  variant = "color",
  mode = "auto",
  title = ".NET",
  className,
  ...props
}: DotnetLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default DotnetLogo;
