/**
 * Dropbox logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/dropbox).
 * Artwork: gilbarbara/logos (CC0-1.0). Dropbox is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type DropboxLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 218" {...props}><path fill="#0061ff" d="M63.995 0 0 40.771l63.995 40.772L128 40.77zM192 0l-64 40.775 64 40.775 64-40.775zM0 122.321l63.995 40.772L128 122.32 63.995 81.55zM192 81.55l-64 40.775 64 40.774 64-40.774zM64 176.771l64.005 40.772L192 176.77 128.005 136z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M6 1.807 0 5.629l6 3.822 6.001-3.822zm12 0-6 3.822 6 3.822 6-3.822zM0 13.274l6 3.822 6.001-3.822L6 9.452zm18-3.822-6 3.822 6 3.822 6-3.822zM6 18.371l6.001 3.822 6-3.822-6-3.822z" /></svg>;

export function DropboxLogo({
  variant = "color",
  title = "Dropbox",
  className,
  ...props
}: DropboxLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default DropboxLogo;
