/**
 * Elementor logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/elementor).
 * Artwork: Simple Icons (CC0-1.0). Elementor is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ElementorLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#92003b" viewBox="0 0 24 24" {...props}><path d="M12 0C5.372 0 0 5.372 0 12c0 6.626 5.372 12 12 12s12-5.372 12-12c0-6.626-5.372-12-12-12M9 17H7V7h2Zm8 0h-6v-2h6Zm0-4h-6v-2h6Zm0-4h-6V7h6Z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12 0C5.372 0 0 5.372 0 12c0 6.626 5.372 12 12 12s12-5.372 12-12c0-6.626-5.372-12-12-12M9 17H7V7h2Zm8 0h-6v-2h6Zm0-4h-6v-2h6Zm0-4h-6V7h6Z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#c0004e" viewBox="0 0 24 24" {...props}><path d="M12 0C5.372 0 0 5.372 0 12c0 6.626 5.372 12 12 12s12-5.372 12-12c0-6.626-5.372-12-12-12M9 17H7V7h2Zm8 0h-6v-2h6Zm0-4h-6v-2h6Zm0-4h-6V7h6Z" /></svg>;

export function ElementorLogo({
  variant = "color",
  mode = "auto",
  title = "Elementor",
  className,
  ...props
}: ElementorLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default ElementorLogo;
