/**
 * Element logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/element).
 * Artwork: gilbarbara/logos (CC0-1.0). Element is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ElementLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 293" {...props}><path fill="#409eff" d="M255.947 209.282c-.073 12.126-6.371 14.83-6.371 14.83s-108.694 62.807-115.76 66.743c-7.003 3.005-11.683 0-11.683 0S8.401 224.894 4.25 221.995C.098 219.094 0 214.577 0 214.577S.115 83.965 0 77.917c-.114-6.05 7.434-10.595 7.434-10.595L121.071 1.641c6.996-3.692 13.807 0 13.807 0s100.386 58.351 111.511 64.623c10.904 5.184 9.558 15.89 9.558 15.89s.068 115.858 0 127.128m-45.37-131.09c-23.267-13.391-78.08-45.15-78.08-45.15s-5.347-2.89-10.84 0L32.44 84.443s-5.927 3.558-5.837 8.292c.09 4.733 0 106.952 0 106.952s.076 3.535 3.336 5.804c3.26 2.268 92.553 53.89 92.553 53.89s3.675 2.353 9.172 0c5.548-3.08 90.886-52.232 90.886-52.232s4.946-2.118 5.003-11.608c.016-2.736.022-13.36.023-26.706l-100.472 60.881v-23.29c0-9.567 7.406-15.88 7.406-15.88l88.869-53.551c3.353-3.502 4.045-9.112 4.188-11.234-.003-9.728-.007-18.226-.01-23.61L127.104 163.02v-24.35c0-9.566 6.348-13.762 6.348-13.762z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0m-1.314 4.715c3.289 0 5.956 2.66 5.956 5.943a.879.879 0 0 1-1.758 0 4.194 4.194 0 0 0-4.198-4.189.878.878 0 1 1 0-1.754m-5.092 9.504a.88.88 0 0 1-.879-.877 5.95 5.95 0 0 1 5.956-5.945.878.878 0 1 1 0 1.753 4.195 4.195 0 0 0-4.198 4.191.88.88 0 0 1-.879.878m7.735 5.067c-3.29 0-5.957-2.662-5.957-5.944a.88.88 0 0 1 1.758 0 4.194 4.194 0 0 0 4.199 4.189.879.879 0 1 1 0 1.755m0-2.683a.88.88 0 0 1-.88-.876.88.88 0 0 1 .88-.878 4.195 4.195 0 0 0 4.199-4.19.878.878 0 0 1 1.758 0c0 3.282-2.667 5.944-5.957 5.944" /></svg>;

export function ElementLogo({
  variant = "color",
  title = "Element",
  className,
  ...props
}: ElementLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default ElementLogo;
