/**
 * Elm logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/elm).
 * Artwork: gilbarbara/logos (CC0-1.0). Elm is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ElmLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><g fill="#1293d8"><path d="m8.529 256 119.399-119.4 119.4 119.4zM0 8.673l119.4 119.4L0 247.47z" /><path fillOpacity={0.75} d="M136.595 0H256v119.405z" /><path d="m136.456 128.072 55.436 55.436 55.435-55.436-55.435-55.435z" /><path fillOpacity={0.75} d="M8.529.144h110.87l52.024 52.024H60.553zm174.834 63.964-55.435 55.436-55.436-55.436zm72.493 183.363-55.436-55.435 55.436-55.435z" /></g></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M23.986 12.806V23.2l-5.197-5.197zM6.796 6.01H17.19l-5.197 5.197zm9.275-1.12H5.677L.8.015h10.394zm7.116 7.117L17.99 6.81l-5.197 5.197 5.197 5.197zm.813-.813L12.806 0H24zM0 23.2V.813l11.194 11.194zm23.187.8H.8l11.193-11.194Z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><g fill="#1293d8"><path d="m8.529 256 119.399-119.4 119.4 119.4zM0 8.673l119.4 119.4L0 247.47z" /><path fillOpacity={0.75} d="M136.595 0H256v119.405z" /><path d="m136.456 128.072 55.436 55.436 55.435-55.436-55.435-55.435z" /><path fillOpacity={0.75} d="M8.529.144h110.87l52.024 52.024H60.553zm174.834 63.964-55.435 55.436-55.436-55.436zm72.493 183.363-55.436-55.435 55.436-55.435z" /></g></svg>;

export function ElmLogo({
  variant = "color",
  mode = "auto",
  title = "Elm",
  className,
  ...props
}: ElmLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default ElmLogo;
