/**
 * ESLint logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/eslint).
 * Artwork: gilbarbara/logos (CC0-1.0). ESLint is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type EslintLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 225" {...props}><path fill="#8080f2" d="m77.965 80.568 48.57-28.042a3.93 3.93 0 0 1 3.93 0l48.57 28.042A3.93 3.93 0 0 1 181 83.971v56.084c0 1.403-.75 2.7-1.965 3.403l-48.57 28.042a3.93 3.93 0 0 1-3.93 0l-48.57-28.042A3.93 3.93 0 0 1 76 140.055V83.97c.001-1.404.75-2.7 1.965-3.403" /><path fill="#4b32c3" d="M254.417 107.417 196.323 6.35C194.213 2.696 190.315 0 186.095 0H69.906c-4.22 0-8.12 2.696-10.23 6.35L1.583 107.194c-2.11 3.655-2.11 8.268 0 11.923l58.093 100.239c2.11 3.654 6.01 5.522 10.23 5.522h116.188c4.22 0 8.119-1.812 10.228-5.467l58.094-100.402c2.112-3.653 2.112-7.938 0-11.592m-48.105 48.6c0 1.485-.894 2.86-2.182 3.604l-73.999 42.693a4.21 4.21 0 0 1-4.186 0l-74.056-42.693c-1.287-.744-2.188-2.118-2.188-3.605V70.628c0-1.487.888-2.86 2.176-3.604l73.995-42.694a4.2 4.2 0 0 1 4.185 0l74.06 42.694c1.289.744 2.195 2.117 2.195 3.604z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M7.257 9.132 11.816 6.5a.37.37 0 0 1 .368 0l4.559 2.632a.37.37 0 0 1 .184.32v5.263a.37.37 0 0 1-.184.319l-4.559 2.632a.37.37 0 0 1-.368 0l-4.559-2.632a.37.37 0 0 1-.184-.32V9.452a.37.37 0 0 1 .184-.32m16.595 2.398-5.446-9.475c-.198-.343-.564-.596-.96-.596H6.555c-.396 0-.762.253-.96.596L.149 11.509a1.13 1.13 0 0 0 0 1.117l5.447 9.398c.197.342.563.517.959.517h10.893c.395 0 .76-.17.959-.512l5.446-9.413a1.07 1.07 0 0 0 0-1.086m-4.51 4.556a.4.4 0 0 1-.204.338L12.2 20.426a.4.4 0 0 1-.392 0l-6.943-4.002a.4.4 0 0 1-.205-.338V8.08c0-.14.083-.269.204-.338L11.8 3.74c.12-.07.272-.07.392 0l6.943 4.003a.4.4 0 0 1 .206.338z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 225" {...props}><path fill="#8080f2" d="m77.965 80.568 48.57-28.042a3.93 3.93 0 0 1 3.93 0l48.57 28.042A3.93 3.93 0 0 1 181 83.971v56.084c0 1.403-.75 2.7-1.965 3.403l-48.57 28.042a3.93 3.93 0 0 1-3.93 0l-48.57-28.042A3.93 3.93 0 0 1 76 140.055V83.97c.001-1.404.75-2.7 1.965-3.403" /><path fill="#5c44cf" d="M254.417 107.417 196.323 6.35C194.213 2.696 190.315 0 186.095 0H69.906c-4.22 0-8.12 2.696-10.23 6.35L1.583 107.194c-2.11 3.655-2.11 8.268 0 11.923l58.093 100.239c2.11 3.654 6.01 5.522 10.23 5.522h116.188c4.22 0 8.119-1.812 10.228-5.467l58.094-100.402c2.112-3.653 2.112-7.938 0-11.592m-48.105 48.6c0 1.485-.894 2.86-2.182 3.604l-73.999 42.693a4.21 4.21 0 0 1-4.186 0l-74.056-42.693c-1.287-.744-2.188-2.118-2.188-3.605V70.628c0-1.487.888-2.86 2.176-3.604l73.995-42.694a4.2 4.2 0 0 1 4.185 0l74.06 42.694c1.289.744 2.195 2.117 2.195 3.604z" /></svg>;

export function EslintLogo({
  variant = "color",
  mode = "auto",
  title = "ESLint",
  className,
  ...props
}: EslintLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default EslintLogo;
