/**
 * Ethereum logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/ethereum).
 * Artwork: gilbarbara/logos (CC0-1.0). Ethereum is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type EthereumLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 417" {...props}><path fill="#343434" d="m127.961 0-2.795 9.5v275.668l2.795 2.79 127.962-75.638z" /><path fill="#8c8c8c" d="M127.962 0 0 212.32l127.962 75.639V154.158z" /><path fill="#3c3c3b" d="m127.961 312.187-1.575 1.92v98.199l1.575 4.6L256 236.587z" /><path fill="#8c8c8c" d="M127.962 416.905v-104.72L0 236.585z" /><path fill="#141414" d="m127.961 287.958 127.96-75.637-127.96-58.162z" /><path fill="#393939" d="m0 212.32 127.96 75.638v-133.8z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.944 17.97 4.58 13.62 11.943 24l7.37-10.38-7.372 4.35zM12.056 0 4.69 12.223l7.365 4.354 7.365-4.35z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 417" {...props}><path fill="#ffffff" d="m127.961 0-2.795 9.5v275.668l2.795 2.79 127.962-75.638z" /><path fill="#8c8c8c" d="M127.962 0 0 212.32l127.962 75.639V154.158z" /><path fill="#ffffff" d="m127.961 312.187-1.575 1.92v98.199l1.575 4.6L256 236.587z" /><path fill="#8c8c8c" d="M127.962 416.905v-104.72L0 236.585z" /><path fill="#ffffff" d="m127.961 287.958 127.96-75.637-127.96-58.162z" /><path fill="#ffffff" d="m0 212.32 127.96 75.638v-133.8z" /></svg>;

export function EthereumLogo({
  variant = "color",
  mode = "auto",
  title = "Ethereum",
  className,
  ...props
}: EthereumLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default EthereumLogo;
