/**
 * Ethers logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/ethers).
 * Artwork: Simple Icons (CC0-1.0). Ethers is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type EthersLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#2535a0" viewBox="0 0 24 24" {...props}><path d="M24 17.443c-12.547 1.64-21.503 3.61-21.636-4.474 0 0 .274-3.133 4.116-3.33 0 0 .13-2.782 3.065-3.097 1.578-.171 3.37 1.454 3.565 3.165 0 0 3.883-.719 4.051 3.067.059 1.32-.238 3.563-3.983 3.465 0 0-2.167-.294-2.461-3.644-.61 6.485 8.767 6.108 8.902.218.06-2.547-1.572-5.167-5.246-4.676-2.014-5.066-7.375-4.775-9.37-.076-2.854 0-5.035 2.196-5.003 5.064.11 9.23 12.954 6.447 24 4.318" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M24 17.443c-12.547 1.64-21.503 3.61-21.636-4.474 0 0 .274-3.133 4.116-3.33 0 0 .13-2.782 3.065-3.097 1.578-.171 3.37 1.454 3.565 3.165 0 0 3.883-.719 4.051 3.067.059 1.32-.238 3.563-3.983 3.465 0 0-2.167-.294-2.461-3.644-.61 6.485 8.767 6.108 8.902.218.06-2.547-1.572-5.167-5.246-4.676-2.014-5.066-7.375-4.775-9.37-.076-2.854 0-5.035 2.196-5.003 5.064.11 9.23 12.954 6.447 24 4.318" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 162" {...props}><path fill="#24339b" d="M256 138.739c-133.839 17.491-229.367 38.5-230.78-47.733 0 0 2.92-33.412 43.902-35.516 0 0 1.381-29.676 32.69-33.036 16.832-1.822 35.956 15.513 38.029 33.758 0 0 41.42-7.662 43.21 32.722.628 14.068-2.544 37.997-42.488 36.96 0 0-23.112-3.14-26.253-38.876-6.5 69.18 93.518 65.161 94.963 2.324.628-27.164-16.77-55.112-55.96-49.868-21.48-54.044-78.665-50.935-99.956-.816-30.43 0-53.699 23.426-53.353 54.013C1.166 191.119 138.176 161.443 256 138.739" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#3f52d3" viewBox="0 0 24 24" {...props}><path d="M24 17.443c-12.547 1.64-21.503 3.61-21.636-4.474 0 0 .274-3.133 4.116-3.33 0 0 .13-2.782 3.065-3.097 1.578-.171 3.37 1.454 3.565 3.165 0 0 3.883-.719 4.051 3.067.059 1.32-.238 3.563-3.983 3.465 0 0-2.167-.294-2.461-3.644-.61 6.485 8.767 6.108 8.902.218.06-2.547-1.572-5.167-5.246-4.676-2.014-5.066-7.375-4.775-9.37-.076-2.854 0-5.035 2.196-5.003 5.064.11 9.23 12.954 6.447 24 4.318" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 162" {...props}><path fill="#4758d4" d="M256 138.739c-133.839 17.491-229.367 38.5-230.78-47.733 0 0 2.92-33.412 43.902-35.516 0 0 1.381-29.676 32.69-33.036 16.832-1.822 35.956 15.513 38.029 33.758 0 0 41.42-7.662 43.21 32.722.628 14.068-2.544 37.997-42.488 36.96 0 0-23.112-3.14-26.253-38.876-6.5 69.18 93.518 65.161 94.963 2.324.628-27.164-16.77-55.112-55.96-49.868-21.48-54.044-78.665-50.935-99.956-.816-30.43 0-53.699 23.426-53.353 54.013C1.166 191.119 138.176 161.443 256 138.739" /></svg>;

export function EthersLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "Ethers",
  className,
  ...props
}: EthersLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default EthersLogo;
