/**
 * Google Drive logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/google-drive).
 * Artwork: gilbarbara/logos (CC0-1.0). Google Drive is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type GoogleDriveLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 238" {...props}><defs><linearGradient id="google-drive-c" x1="86.924%" x2="7.63%" y1="94.294%" y2="45.952%"><stop offset="9%" stopColor="#ffe921" /><stop offset="100%" stopColor="#fec700" /></linearGradient><linearGradient id="google-drive-d" x1="99.538%" x2="23.437%" y1="93.901%" y2="54.033%"><stop offset="15%" stopColor="#a9a8ff" /><stop offset="33%" stopColor="#6d97ff" /><stop offset="48%" stopColor="#3186ff" /></linearGradient><linearGradient id="google-drive-e" x1="87.128%" x2="-.639%" y1="51.518%" y2="93.078%"><stop offset="55%" stopColor="#0ebc5f" /><stop offset="85%" stopColor="#78c9ff" /></linearGradient><path id="google-drive-a" d="M77.303 29.27c22.531-39.026 78.863-39.027 101.394 0l69.373 120.158c22.531 39.027-5.633 87.81-50.698 87.81H58.628c-45.065 0-73.23-48.783-50.698-87.81z" /></defs><mask id="google-drive-b" fill="#fff"><use xlinkHref="#google-drive-a" /></mask><g mask="url(#google-drive-b)"><path fill="url(#google-drive-c)" d="M341.72 295.937H200.165l-29.293-50.735 70.777-122.59z" transform="translate(-42.87 -58.67)" /><path fill="url(#google-drive-d)" d="M0 295.916 100.07 122.59v.003l-29.283 50.723h58.57l70.783 122.596-200.138.001z" transform="translate(-42.87 -58.67)" /><path fill="url(#google-drive-e)" d="m170.881 0 70.781 122.6-29.286 50.726H70.812z" transform="translate(-42.87 -58.67)" /></g></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12.01 1.485c-2.082 0-3.754.02-3.743.047.01.02 1.708 3.001 3.774 6.62l3.76 6.574h3.76c2.081 0 3.753-.02 3.742-.047-.005-.02-1.708-3.001-3.775-6.62l-3.76-6.574zm-4.76 1.73a789.828 789.861 0 0 0-3.63 6.319L0 15.868l1.89 3.298 1.885 3.297 3.62-6.335 3.618-6.33-1.88-3.287C8.1 4.704 7.255 3.22 7.25 3.214zm2.259 12.653-.203.348c-.114.198-.96 1.672-1.88 3.287a423.93 423.948 0 0 1-1.698 2.97c-.01.026 3.24.042 7.222.042h7.244l1.796-3.157c.992-1.734 1.85-3.23 1.906-3.323l.104-.167h-7.249z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 238" {...props}><defs><linearGradient id="google-drive-c-dark" x1="86.924%" x2="7.63%" y1="94.294%" y2="45.952%"><stop offset="9%" stopColor="#ffe921" /><stop offset="100%" stopColor="#fec700" /></linearGradient><linearGradient id="google-drive-d-dark" x1="99.538%" x2="23.437%" y1="93.901%" y2="54.033%"><stop offset="15%" stopColor="#a9a8ff" /><stop offset="33%" stopColor="#6d97ff" /><stop offset="48%" stopColor="#3186ff" /></linearGradient><linearGradient id="google-drive-e-dark" x1="87.128%" x2="-.639%" y1="51.518%" y2="93.078%"><stop offset="55%" stopColor="#0ebc5f" /><stop offset="85%" stopColor="#78c9ff" /></linearGradient><path id="google-drive-a-dark" d="M77.303 29.27c22.531-39.026 78.863-39.027 101.394 0l69.373 120.158c22.531 39.027-5.633 87.81-50.698 87.81H58.628c-45.065 0-73.23-48.783-50.698-87.81z" /></defs><mask id="google-drive-b-dark" fill="#fff"><use xlinkHref="#google-drive-a-dark" /></mask><g mask="url(#google-drive-b-dark)"><path fill="url(#google-drive-c-dark)" d="M341.72 295.937H200.165l-29.293-50.735 70.777-122.59z" transform="translate(-42.87 -58.67)" /><path fill="url(#google-drive-d-dark)" d="M0 295.916 100.07 122.59v.003l-29.283 50.723h58.57l70.783 122.596-200.138.001z" transform="translate(-42.87 -58.67)" /><path fill="url(#google-drive-e-dark)" d="m170.881 0 70.781 122.6-29.286 50.726H70.812z" transform="translate(-42.87 -58.67)" /></g></svg>;

export function GoogleDriveLogo({
  variant = "color",
  mode = "auto",
  title = "Google Drive",
  className,
  ...props
}: GoogleDriveLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default GoogleDriveLogo;
