/**
 * Google Keep logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/google-keep).
 * Artwork: gilbarbara/logos (CC0-1.0). Google Keep is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type GoogleKeepLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 326" {...props}><defs><linearGradient id="google-keep-a" x1={71.83} x2={156.83} y1={148} y2={8} gradientUnits="userSpaceOnUse"><stop offset={0.1} stopColor="#ffe921" /><stop offset={0.48} stopColor="#fdd313" /><stop offset={0.86} stopColor="#ffbe00" /></linearGradient><linearGradient id="google-keep-c" x1={96} x2={96} y1={140.04} y2={8} gradientUnits="userSpaceOnUse"><stop offset={0.16} stopColor="#ffe921" /><stop offset={0.64} stopColor="#fec700" /><stop offset={0.96} stopColor="#ffbe00" /></linearGradient><linearGradient id="google-keep-f" x1={96} x2={96} y1={51.19} y2={142.89} gradientUnits="userSpaceOnUse"><stop offset={0.11} stopColor="#ffb8dd" stopOpacity={0} /><stop offset={0.68} stopColor="#ffb5e8" /></linearGradient><filter id="google-keep-d" width={203.2} height={235.2} x={-5.6} y={6.4} colorInterpolationFilters="sRGB" filterUnits="userSpaceOnUse"><feFlood floodOpacity={0} result="BackgroundImageFix" /><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape" /><feGaussianBlur result="effect1_foregroundBlur_37487_16896" stdDeviation={28.8} /></filter><filter id="google-keep-e" width={88} height={140} x={52} y={58} colorInterpolationFilters="sRGB" filterUnits="userSpaceOnUse"><feFlood floodOpacity={0} result="BackgroundImageFix" /><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape" /><feGaussianBlur result="effect1_foregroundBlur_37487_16896" stdDeviation={6} /></filter></defs><mask id="google-keep-b" width={140} height={140} x={26} y={8} maskUnits="userSpaceOnUse" style={{
    maskType: "alpha"
  }}><path fill="url(#google-keep-a)" d="M166 78c0 27.13-15.434 50.381-38 62-9.591 4.938-20.47 8-32 8s-22.41-3.062-32-8c-22.566-11.619-38-34.87-38-62C26 39.34 57.34 8 96 8s70 31.34 70 70" /></mask><g mask="url(#google-keep-b)" transform="translate(-47.543 -14.629)scale(1.82857)"><circle cx={96} cy={78} r={70} fill="url(#google-keep-c)" /><g filter="url(#google-keep-d)"><path fill="#fdfd6d" d="M52 124c0-38.137 14.81-60 44-60s44 21.863 44 60c0 33.137-19.699 60-44 60s-44-26.863-44-60" /></g><g filter="url(#google-keep-e)"><path fill="url(#google-keep-f)" d="M64 102c0-17.673 14.327-32 32-32s32 14.327 32 32v52c0 17.673-14.327 32-32 32s-32-14.327-32-32z" /></g><path fill="#fff" d="M78 127c0-7.18 5.82-13 13-13h10c7.18 0 13 5.82 13 13s-5.82 13-13 13H91c-7.18 0-13-5.82-13-13" /></g><g mask="url(#google-keep-g)" transform="translate(-47.543 -14.629)scale(1.82857)"><path fill="#f6a100" d="M96 56c-18.4 0-32 14.4-32 33.6v62.8c0 19.2 13.6 33.6 32 33.6s32-14.4 32-33.6V89.6C128 70.4 114.4 56 96 56" /></g><mask id="google-keep-g" width={80} height={46} x={56} y={140} maskUnits="userSpaceOnUse" style={{
    maskType: "alpha"
  }}><path fill="#ffbe00" d="M56 140h80v46H56z" /></mask></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M4.908 0c-.904 0-1.635.733-1.635 1.637v20.726c0 .904.732 1.637 1.635 1.637H19.09c.904 0 1.637-.733 1.637-1.637V6.5h-6.5V0zm9.819 0v6h6zM11.97 8.229c.224 0 .571.031.765.072.2.04.576.185.842.312.828.414 1.467 1.164 1.774 2.088.168.511.188 1.34.05 1.865a3.75 3.75 0 0 1-1.277 1.952l-.25.193h-1.87c-2.134 0-1.931.042-2.478-.494a3.35 3.35 0 0 1-.984-1.844c-.148-.766-.053-1.437.32-2.203.19-.399.303-.556.65-.899.68-.679 1.513-1.037 2.458-1.042m-1.866 7.863h3.781v1.328h-3.779v-1.328z" /></svg>;

export function GoogleKeepLogo({
  variant = "color",
  title = "Google Keep",
  className,
  ...props
}: GoogleKeepLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default GoogleKeepLogo;
