/**
 * Google Search Console logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/google-search-console).
 * Artwork: gilbarbara/logos (CC0-1.0). Google Search Console is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type GoogleSearchConsoleLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 228" {...props}><defs><radialGradient id="google-search-console-a" cx="21.66%" cy="28.708%" r="82.87%" fx="21.66%" fy="28.708%" gradientTransform="matrix(.59503 .59486 -.44034 .80383 .214 -.073)"><stop offset="0%" stopColor="#f1f2f2" /><stop offset="100%" stopColor="#e6e7e8" /></radialGradient></defs><path fill="#737373" d="M165.98 0H90.02L71.098 19.055V37.98H90.02V19.055h75.958V37.98h18.924V19.055z" /><path fill="#bfbfbf" d="M90.02 0v19.055h75.96V0z" /><path fill="url(#google-search-console-a)" d="M36.402 37.98 0 74.381v134.177c0 10.513 8.542 18.924 18.924 18.924h218.152c10.513 0 18.924-8.543 18.924-18.924V74.513L219.466 37.98z" /><path fill="#fff" d="M28.517 109.076h199.097v118.538H28.517z" /><path fill="#e0e0e0" d="M36.402 37.98 0 74.381v34.694h256V74.513L219.466 37.98z" /><path fill="#d1d1d1" d="M42.71 213.29H128v14.193H42.71z" /><path fill="#4285f4" d="M28.517 86.998a14.695 14.695 0 0 1 14.72-14.719h169.527a14.695 14.695 0 0 1 14.719 14.719v22.078H28.517z" /><path fill="#e6e6e6" d="M56.903 90.152a7.067 7.067 0 0 1-7.096 7.096 7.067 7.067 0 0 1-7.097-7.096 7.067 7.067 0 0 1 7.097-7.097 7.067 7.067 0 0 1 7.096 7.097m23.656 0a7.067 7.067 0 0 1-7.097 7.096 7.067 7.067 0 0 1-7.096-7.096 7.067 7.067 0 0 1 7.096-7.097 7.067 7.067 0 0 1 7.097 7.097" /><path fill="#bababa" d="m227.483 165.191-29.832-29.832-9.988 30.883-40.739-40.608-1.183 62.686 15.113 23.655c2.234-.394-11.302 15.508-11.302 15.508h77.93z" /><path fill="#4d4d4d" d="M208.821 164.008c0-16.821-9.856-31.277-23.918-38.242v39.95l-18.792 10.12-19.056-10.12v-40.082c-14.061 6.966-23.655 21.553-23.655 38.243 0 16.821 9.725 31.277 23.787 38.242v25.364h37.848v-25.364c13.93-6.834 23.786-21.42 23.786-38.11" /><path fill="#d1d1d1" d="M42.71 123.269h66.366v75.828H42.71z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M8.548 1.156 6.832 2.872v1.682h1.716zm0 3.398v.035H6.832v-.035H3.386L0 7.844v3.577h2.826V8.94c0-.525.429-.954.954-.954h16.476c.525 0 .954.43.954.954v2.48h2.754V7.844l-3.386-3.29H17.3v.035h-1.717v-.035zm7.035 0H17.3V2.872l-1.717-1.716zM8.679 1.188V2.84h6.773V1.188zm11.471 7.07a1 1 0 0 0-.132.01l-.543.002c-5.216.014-10.432-.008-15.648.01-.435-.063-.794.436-.716.883v2.264h17.812c-.016-.888.045-1.782-.034-2.666-.104-.342-.427-.502-.739-.502zm-15.422.634a.689.698 0 0 1 .689.698.689.698 0 0 1-.689.697.689.698 0 0 1-.688-.697.689.698 0 0 1 .688-.698m2.134 0a.689.698 0 0 1 .689.698.689.698 0 0 1-.689.697.689.698 0 0 1-.688-.697.689.698 0 0 1 .688-.698M.036 11.645v9.156c0 1.05.858 1.908 1.907 1.908h.883V11.645zm21.174 0v11.064h.882c1.05 0 1.908-.858 1.908-1.908v-9.156zM4.057 13.133v6.85h6.137v-6.85zm13.243.021v3.777l-1.708.977-1.708-.977v-3.758a4.006 4.006 0 0 0 0 7.23v2.441h3.457v-2.442a4.006 4.006 0 0 0-.041-7.248m-13.243 8.26v1.43h7.925v-1.43z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 228" {...props}><defs><radialGradient id="google-search-console-a-dark" cx="21.66%" cy="28.708%" r="82.87%" fx="21.66%" fy="28.708%" gradientTransform="matrix(.59503 .59486 -.44034 .80383 .214 -.073)"><stop offset="0%" stopColor="#f1f2f2" /><stop offset="100%" stopColor="#e6e7e8" /></radialGradient></defs><path fill="#737373" d="M165.98 0H90.02L71.098 19.055V37.98H90.02V19.055h75.958V37.98h18.924V19.055z" /><path fill="#bfbfbf" d="M90.02 0v19.055h75.96V0z" /><path fill="url(#google-search-console-a-dark)" d="M36.402 37.98 0 74.381v134.177c0 10.513 8.542 18.924 18.924 18.924h218.152c10.513 0 18.924-8.543 18.924-18.924V74.513L219.466 37.98z" /><path fill="#fff" d="M28.517 109.076h199.097v118.538H28.517z" /><path fill="#e0e0e0" d="M36.402 37.98 0 74.381v34.694h256V74.513L219.466 37.98z" /><path fill="#d1d1d1" d="M42.71 213.29H128v14.193H42.71z" /><path fill="#4285f4" d="M28.517 86.998a14.695 14.695 0 0 1 14.72-14.719h169.527a14.695 14.695 0 0 1 14.719 14.719v22.078H28.517z" /><path fill="#e6e6e6" d="M56.903 90.152a7.067 7.067 0 0 1-7.096 7.096 7.067 7.067 0 0 1-7.097-7.096 7.067 7.067 0 0 1 7.097-7.097 7.067 7.067 0 0 1 7.096 7.097m23.656 0a7.067 7.067 0 0 1-7.097 7.096 7.067 7.067 0 0 1-7.096-7.096 7.067 7.067 0 0 1 7.096-7.097 7.067 7.067 0 0 1 7.097 7.097" /><path fill="#bababa" d="m227.483 165.191-29.832-29.832-9.988 30.883-40.739-40.608-1.183 62.686 15.113 23.655c2.234-.394-11.302 15.508-11.302 15.508h77.93z" /><path fill="#ffffff" d="M208.821 164.008c0-16.821-9.856-31.277-23.918-38.242v39.95l-18.792 10.12-19.056-10.12v-40.082c-14.061 6.966-23.655 21.553-23.655 38.243 0 16.821 9.725 31.277 23.787 38.242v25.364h37.848v-25.364c13.93-6.834 23.786-21.42 23.786-38.11" /><path fill="#d1d1d1" d="M42.71 123.269h66.366v75.828H42.71z" /></svg>;

export function GoogleSearchConsoleLogo({
  variant = "color",
  mode = "auto",
  title = "Google Search Console",
  className,
  ...props
}: GoogleSearchConsoleLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default GoogleSearchConsoleLogo;
