/**
 * Google AI Studio logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/google-aistudio).
 * Artwork: gilbarbara/logos (CC0-1.0). Google AI Studio is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type GoogleAistudioLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 266" {...props}><path d="M107.336 27.398a86.6 86.6 0 0 0-9.931 18.266H54.796c-20.175 0-36.53 16.355-36.53 36.53v127.858c0 20.175 16.355 36.53 36.53 36.53h127.858c20.175 0 36.53-16.355 36.53-36.53v-55.998a87 87 0 0 0 18.266-13.157v69.155c0 30.263-24.533 54.796-54.796 54.796H54.796C24.533 264.848 0 240.315 0 210.052V82.194c0-30.263 24.533-54.796 54.796-54.796z" /><path d="M240.874 61.238c-10.554-4.543-19.788-10.776-27.707-18.69-7.915-7.915-14.148-17.153-18.69-27.708a82 82 0 0 1-4.221-12.465A3.135 3.135 0 0 0 187.219 0a3.134 3.134 0 0 0-3.036 2.375 82 82 0 0 1-4.22 12.465q-6.817 15.834-18.692 27.708c-7.914 7.914-17.152 14.147-27.707 18.69a82 82 0 0 1-12.465 4.22 3.135 3.135 0 0 0-2.375 3.037c0 1.436.981 2.686 2.375 3.037a82 82 0 0 1 12.465 4.22c10.555 4.543 19.79 10.776 27.707 18.69q11.878 11.874 18.692 27.708a82 82 0 0 1 4.22 12.465 3.134 3.134 0 0 0 3.036 2.375 3.135 3.135 0 0 0 3.037-2.375 82 82 0 0 1 4.22-12.465c4.543-10.555 10.776-19.79 18.69-27.707 7.915-7.915 17.154-14.148 27.708-18.691a82 82 0 0 1 12.466-4.22 3.135 3.135 0 0 0 2.374-3.037 3.135 3.135 0 0 0-2.374-3.037 82 82 0 0 1-12.466-4.22" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 266" {...props}><path d="M107.336 27.398a86.6 86.6 0 0 0-9.931 18.266H54.796c-20.175 0-36.53 16.355-36.53 36.53v127.858c0 20.175 16.355 36.53 36.53 36.53h127.858c20.175 0 36.53-16.355 36.53-36.53v-55.998a87 87 0 0 0 18.266-13.157v69.155c0 30.263-24.533 54.796-54.796 54.796H54.796C24.533 264.848 0 240.315 0 210.052V82.194c0-30.263 24.533-54.796 54.796-54.796z" /><path d="M240.874 61.238c-10.554-4.543-19.788-10.776-27.707-18.69-7.915-7.915-14.148-17.153-18.69-27.708a82 82 0 0 1-4.221-12.465A3.135 3.135 0 0 0 187.219 0a3.134 3.134 0 0 0-3.036 2.375 82 82 0 0 1-4.22 12.465q-6.817 15.834-18.692 27.708c-7.914 7.914-17.152 14.147-27.707 18.69a82 82 0 0 1-12.465 4.22 3.135 3.135 0 0 0-2.375 3.037c0 1.436.981 2.686 2.375 3.037a82 82 0 0 1 12.465 4.22c10.555 4.543 19.79 10.776 27.707 18.69q11.878 11.874 18.692 27.708a82 82 0 0 1 4.22 12.465 3.134 3.134 0 0 0 3.036 2.375 3.135 3.135 0 0 0 3.037-2.375 82 82 0 0 1 4.22-12.465c4.543-10.555 10.776-19.79 18.69-27.707 7.915-7.915 17.154-14.148 27.708-18.691a82 82 0 0 1 12.466-4.22 3.135 3.135 0 0 0 2.374-3.037 3.135 3.135 0 0 0-2.374-3.037 82 82 0 0 1-12.466-4.22" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 266" {...props}><path d="M107.336 27.398a86.6 86.6 0 0 0-9.931 18.266H54.796c-20.175 0-36.53 16.355-36.53 36.53v127.858c0 20.175 16.355 36.53 36.53 36.53h127.858c20.175 0 36.53-16.355 36.53-36.53v-55.998a87 87 0 0 0 18.266-13.157v69.155c0 30.263-24.533 54.796-54.796 54.796H54.796C24.533 264.848 0 240.315 0 210.052V82.194c0-30.263 24.533-54.796 54.796-54.796z" /><path d="M240.874 61.238c-10.554-4.543-19.788-10.776-27.707-18.69-7.915-7.915-14.148-17.153-18.69-27.708a82 82 0 0 1-4.221-12.465A3.135 3.135 0 0 0 187.219 0a3.134 3.134 0 0 0-3.036 2.375 82 82 0 0 1-4.22 12.465q-6.817 15.834-18.692 27.708c-7.914 7.914-17.152 14.147-27.707 18.69a82 82 0 0 1-12.465 4.22 3.135 3.135 0 0 0-2.375 3.037c0 1.436.981 2.686 2.375 3.037a82 82 0 0 1 12.465 4.22c10.555 4.543 19.79 10.776 27.707 18.69q11.878 11.874 18.692 27.708a82 82 0 0 1 4.22 12.465 3.134 3.134 0 0 0 3.036 2.375 3.135 3.135 0 0 0 3.037-2.375 82 82 0 0 1 4.22-12.465c4.543-10.555 10.776-19.79 18.69-27.707 7.915-7.915 17.154-14.148 27.708-18.691a82 82 0 0 1 12.466-4.22 3.135 3.135 0 0 0 2.374-3.037 3.135 3.135 0 0 0-2.374-3.037 82 82 0 0 1-12.466-4.22" /></svg>;

export function GoogleAistudioLogo({
  variant = "color",
  mode = "auto",
  title = "Google AI Studio",
  className,
  ...props
}: GoogleAistudioLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default GoogleAistudioLogo;
