/**
 * Hexo logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/hexo).
 * Artwork: gilbarbara/logos (CC0-1.0). Hexo is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type HexoLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 295" {...props}><path fill="#0e83cd" d="M128.04 0 .574 73.768.59 221.079l127.754 73.465 127.464-73.769.002-147.23z" /><path fill="#fff" d="m68.242 211.051.01-63.7.01-63.702 11.573-6.768 11.085 6.56.12 26.03.12 26.031h74.075l.12-26.013.12-26.014 11.257-6.505 11.412 6.68-.006 63.658-.005 63.659-11.298 6.31-11.361-6.392-.12-25.885-.12-25.886H91.16l-.12 25.878.034 26.008-11.36 6.663z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12.02 0 1.596 6.02l-.02 12L11.978 24l10.426-6.02.02-12zm4.828 17.14-.96.558-.969-.574V12.99H9.081v4.15l-.96.558-.969-.574V6.854l.964-.552.965.563v4.145h5.838V6.86l.965-.552.964.563z" /></svg>;

export function HexoLogo({
  variant = "color",
  title = "Hexo",
  className,
  ...props
}: HexoLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default HexoLogo;
