/**
 * HHVM logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/hhvm).
 * Artwork: gilbarbara/logos (CC0-1.0). HHVM is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type HhvmLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 382" {...props}><path fill="#fff" d="m131.015 127.065 117.088.003-117.088 115.396z" /><path fill="#878787" d="M.002 257.489h116.672L.002 375.955zM.001 120.581 121.948 1l.061 121.501L.001 244.185zm256 12.152v124.388L131.02 381.188V256.832zm-.044-14.864-117.087-.003L255.957.723z" /><path fill="#f7852f" d="m121.909 247.908-113.513-.003L121.909 134.32z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 382" {...props}><path fill="currentColor" d="m131.015 127.065 117.088.003-117.088 115.396z" /><path fill="currentColor" d="M.002 257.489h116.672L.002 375.955zM.001 120.581 121.948 1l.061 121.501L.001 244.185zm256 12.152v124.388L131.02 381.188V256.832zm-.044-14.864-117.087-.003L255.957.723z" /><path fill="currentColor" d="m121.909 247.908-113.513-.003L121.909 134.32z" /></svg>;

export function HhvmLogo({
  variant = "color",
  title = "HHVM",
  className,
  ...props
}: HhvmLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default HhvmLogo;
