/**
 * Instatus logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/instatus).
 * Artwork: Simple Icons (CC0-1.0). Instatus is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type InstatusLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#4ee3c2" viewBox="0 0 24 24" {...props}><path d="M16.994 21.028a9.65 9.65 0 0 0 5.056-9.564 37 37 0 0 0-3.87 3.69c-2.066 2.27-3.748 4.657-4.996 6.983a9.6 9.6 0 0 0 3.81-1.109M3.6 18.465c-1.34 1.82-2.377 4.5-1.303 5.307 1.515 1.14 8.404-2.013 13.908-8.805S23.53 1.17 21.084.094c-1.129-.497-3.486 1.083-4.84 2.394l.585.314c1.332-.852 3.552-1.733 1.499 1.976l-.03.053A9.65 9.65 0 0 0 7.92 4c-4.703 2.506-6.484 8.35-3.978 13.052a9.6 9.6 0 0 0 2.266 2.816c-3.559 2.75-2.69.36-2.193-.816z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M16.994 21.028a9.65 9.65 0 0 0 5.056-9.564 37 37 0 0 0-3.87 3.69c-2.066 2.27-3.748 4.657-4.996 6.983a9.6 9.6 0 0 0 3.81-1.109M3.6 18.465c-1.34 1.82-2.377 4.5-1.303 5.307 1.515 1.14 8.404-2.013 13.908-8.805S23.53 1.17 21.084.094c-1.129-.497-3.486 1.083-4.84 2.394l.585.314c1.332-.852 3.552-1.733 1.499 1.976l-.03.053A9.65 9.65 0 0 0 7.92 4c-4.703 2.506-6.484 8.35-3.978 13.052a9.6 9.6 0 0 0 2.266 2.816c-3.559 2.75-2.69.36-2.193-.816z" /></svg>;

export function InstatusLogo({
  variant = "color",
  title = "Instatus",
  className,
  ...props
}: InstatusLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default InstatusLogo;
