/**
 * Istio logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/istio).
 * Artwork: Simple Icons (CC0-1.0). Istio is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type IstioLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#466bb0" viewBox="0 0 24 24" {...props}><path d="M4 21h16l-10 3zm0-1 6-1V8zm7-1 9 1-9-20z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M4 21h16l-10 3zm0-1 6-1V8zm7-1 9 1-9-20z" /></svg>;

export function IstioLogo({
  variant = "color",
  title = "Istio",
  className,
  ...props
}: IstioLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default IstioLogo;
