/**
 * Jasmine logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/jasmine).
 * Artwork: gilbarbara/logos (CC0-1.0). Jasmine is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type JasmineLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 255" {...props}><g fill="#8a4182"><path d="M118.267 105.334h19.795l4.918-6.733V45.874h-29.627v52.733zm-12.758 23.517 6.115-18.717-4.919-6.73L56.271 87.11l-9.154 28.016 50.44 16.296zm18.551 19.336-16.012-11.57-7.96 2.572-31.168 42.66 23.968 17.313 31.172-42.66zm24.225-11.573-16.016 11.57.004 8.32 31.169 42.658 23.969-17.314-31.175-42.663zm-3.583-26.484 6.118 18.72 7.958 2.569 50.435-16.293-9.157-28.018-50.436 16.297z" /><path d="M128.17.106C57.71.106.384 57.1.384 127.152c0 70.078 57.326 127.087 127.788 127.087 70.454 0 127.774-57.009 127.774-127.087 0-70.053-57.32-127.046-127.774-127.046m0 25.725c56.27 0 101.9 45.357 101.9 101.32 0 55.983-45.63 101.36-101.9 101.36-56.287 0-101.912-45.377-101.912-101.36 0-55.963 45.625-101.32 101.913-101.32" /><path d="m205.565 155.391-38.338-12.387 2.535-7.765 38.338 12.387zM156.67 94.19l-6.645-4.798 23.693-32.429 6.644 4.799zm-56.598-.295-23.69-32.43 6.644-4.798 23.69 32.428zm-49.464 61.012-2.536-7.765 38.334-12.382 2.537 7.765zm73.199 53.252h8.211v-40.085h-8.21z" /></g></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.591 19.649h.771v-3.786h-.77zm-6.874-5.03-.238-.733 3.6-1.17.238.735-3.6 1.17m4.645-5.762L7.138 5.796l.624-.453 2.224 3.062zm5.315.028-.624-.454 2.225-3.062.624.453zm4.592 5.78-3.6-1.17.238-.734 3.6 1.17zM12 .001C5.383.001 0 5.384 0 11.998 0 18.617 5.383 24 12 24s12-5.382 12-12c0-6.617-5.383-12-12-12zm0 2.43c5.284 0 9.569 4.283 9.569 9.567 0 5.287-4.285 9.573-9.569 9.573-5.286 0-9.57-4.286-9.57-9.573 0-5.284 4.285-9.567 9.57-9.567m1.552 7.96.575 1.768.747.242 4.736-1.538-.86-2.645-4.736 1.539zm.337 2.5-1.504 1.093v.785l2.927 4.03 2.25-1.636-2.927-4.029zm-2.275 1.093-1.504-1.093-.747.243-2.927 4.029 2.25 1.635 2.928-4.029zM9.873 12.16l.574-1.767-.462-.635-4.736-1.54-.86 2.646 4.737 1.54zm1.198-2.22h1.859l.462-.636v-4.98H10.61v4.98z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 255" {...props}><g fill="#94468c"><path d="M118.267 105.334h19.795l4.918-6.733V45.874h-29.627v52.733zm-12.758 23.517 6.115-18.717-4.919-6.73L56.271 87.11l-9.154 28.016 50.44 16.296zm18.551 19.336-16.012-11.57-7.96 2.572-31.168 42.66 23.968 17.313 31.172-42.66zm24.225-11.573-16.016 11.57.004 8.32 31.169 42.658 23.969-17.314-31.175-42.663zm-3.583-26.484 6.118 18.72 7.958 2.569 50.435-16.293-9.157-28.018-50.436 16.297z" /><path d="M128.17.106C57.71.106.384 57.1.384 127.152c0 70.078 57.326 127.087 127.788 127.087 70.454 0 127.774-57.009 127.774-127.087 0-70.053-57.32-127.046-127.774-127.046m0 25.725c56.27 0 101.9 45.357 101.9 101.32 0 55.983-45.63 101.36-101.9 101.36-56.287 0-101.912-45.377-101.912-101.36 0-55.963 45.625-101.32 101.913-101.32" /><path d="m205.565 155.391-38.338-12.387 2.535-7.765 38.338 12.387zM156.67 94.19l-6.645-4.798 23.693-32.429 6.644 4.799zm-56.598-.295-23.69-32.43 6.644-4.798 23.69 32.428zm-49.464 61.012-2.536-7.765 38.334-12.382 2.537 7.765zm73.199 53.252h8.211v-40.085h-8.21z" /></g></svg>;

export function JasmineLogo({
  variant = "color",
  mode = "auto",
  title = "Jasmine",
  className,
  ...props
}: JasmineLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default JasmineLogo;
