/**
 * JWT logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/jwt).
 * Artwork: gilbarbara/logos (CC0-1.0). JWT is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type JwtLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 257" {...props}><path fill="#fff" d="M147.386 69.071 147.13 0h-38.515l.257 69.071 19.257 26.448zM108.87 187.442v69.328h38.516v-69.328l-19.258-26.447z" /><path fill="#00f2e6" d="m147.386 187.442 40.57 55.976 31.07-22.596-40.57-55.975-31.07-10.015zM108.87 69.071 68.045 13.095l-31.07 22.596 40.57 55.976 31.327 10.014z" /><path fill="#00b9f1" d="M77.545 91.667 11.81 70.355 0 106.816l65.733 21.57 31.07-10.272zm81.653 46.733 19.257 26.447 65.734 21.311L256 149.698l-65.733-21.313z" /><path fill="#d63aff" d="M190.267 128.385 256 106.816l-11.811-36.46-65.734 21.311-19.257 26.447zm-124.534 0L0 149.697l11.811 36.461 65.734-21.311 19.257-26.448z" /><path fill="#fb015b" d="m77.545 164.847-40.57 55.975 31.07 22.596 40.826-55.976v-32.61zm100.91-73.18 40.57-55.976-31.07-22.596-40.569 55.976v32.61z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 257" {...props}><path fill="currentColor" d="M147.386 69.071 147.13 0h-38.515l.257 69.071 19.257 26.448zM108.87 187.442v69.328h38.516v-69.328l-19.258-26.447z" /><path fill="currentColor" d="m147.386 187.442 40.57 55.976 31.07-22.596-40.57-55.975-31.07-10.015zM108.87 69.071 68.045 13.095l-31.07 22.596 40.57 55.976 31.327 10.014z" /><path fill="currentColor" d="M77.545 91.667 11.81 70.355 0 106.816l65.733 21.57 31.07-10.272zm81.653 46.733 19.257 26.447 65.734 21.311L256 149.698l-65.733-21.313z" /><path fill="currentColor" d="M190.267 128.385 256 106.816l-11.811-36.46-65.734 21.311-19.257 26.447zm-124.534 0L0 149.697l11.811 36.461 65.734-21.311 19.257-26.448z" /><path fill="currentColor" d="m77.545 164.847-40.57 55.975 31.07 22.596 40.826-55.976v-32.61zm100.91-73.18 40.57-55.976-31.07-22.596-40.569 55.976v32.61z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 172" {...props}><path fill="#fff" d="M98.192 46.017 98.02 0H72.36l.17 46.017 12.83 17.62zm-25.66 78.861v46.188h25.66v-46.188l-12.83-17.62z" /><path fill="#00f2e6" d="m98.192 124.878 27.028 37.292 20.7-15.053-27.03-37.293-20.698-6.671zm-25.66-78.861-27.2-37.293-20.699 15.054L51.662 61.07l20.87 6.672z" /><path fill="#00b9f1" d="M51.662 61.07 7.869 46.872 0 71.163l43.793 14.37 20.699-6.843zm54.398 31.134 12.83 17.62 43.794 14.199 7.869-24.292-43.793-14.198z" /><path fill="#d63aff" d="m126.76 85.533 43.793-14.37-7.87-24.291-43.792 14.198-12.83 17.62zm-82.967 0L0 99.73l7.869 24.292 43.793-14.199 12.83-17.62z" /><path fill="#fb015b" d="m51.662 109.824-27.029 37.293 20.7 15.053 27.199-37.292v-21.725zM118.89 61.07l27.03-37.292-20.7-15.054-27.028 37.293v21.725z" /><path d="M266.35 43.622v59.873c0 13.172-10.778 23.949-23.95 23.949v-11.975c6.672 0 11.975-5.303 11.975-11.974V43.622zm218.622 11.974H512V43.622h-65.86v11.974h26.857v71.848h11.975zm-74.927-11.974v59.873c0 6.671-5.303 11.974-11.975 11.974s-11.974-5.303-11.974-11.974V67.57c0-13.172-10.778-23.95-23.95-23.95s-23.949 10.778-23.949 23.95v35.924c0 6.671-5.303 11.974-11.974 11.974s-11.975-5.303-11.975-11.974V43.622h-11.975v59.873c0 13.172 10.777 23.949 23.95 23.949s23.949-10.777 23.949-23.95V67.572c0-6.672 5.303-11.975 11.974-11.975s11.975 5.303 11.975 11.975v35.924c0 13.172 10.777 23.949 23.95 23.949 13.171 0 23.948-10.777 23.948-23.95V43.623z" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 172" {...props}><path fill="#0a0a0a" d="M98.192 46.017 98.02 0H72.36l.17 46.017 12.83 17.62zm-25.66 78.861v46.188h25.66v-46.188l-12.83-17.62z" /><path fill="#00f2e6" d="m98.192 124.878 27.028 37.292 20.7-15.053-27.03-37.293-20.698-6.671zm-25.66-78.861-27.2-37.293-20.699 15.054L51.662 61.07l20.87 6.672z" /><path fill="#00b9f1" d="M51.662 61.07 7.869 46.872 0 71.163l43.793 14.37 20.699-6.843zm54.398 31.134 12.83 17.62 43.794 14.199 7.869-24.292-43.793-14.198z" /><path fill="#d63aff" d="m126.76 85.533 43.793-14.37-7.87-24.291-43.792 14.198-12.83 17.62zm-82.967 0L0 99.73l7.869 24.292 43.793-14.199 12.83-17.62z" /><path fill="#fb015b" d="m51.662 109.824-27.029 37.293 20.7 15.053 27.199-37.292v-21.725zM118.89 61.07l27.03-37.292-20.7-15.054-27.028 37.293v21.725z" /><path d="M266.35 43.622v59.873c0 13.172-10.778 23.949-23.95 23.949v-11.975c6.672 0 11.975-5.303 11.975-11.974V43.622zm218.622 11.974H512V43.622h-65.86v11.974h26.857v71.848h11.975zm-74.927-11.974v59.873c0 6.671-5.303 11.974-11.975 11.974s-11.974-5.303-11.974-11.974V67.57c0-13.172-10.778-23.95-23.95-23.95s-23.949 10.778-23.949 23.95v35.924c0 6.671-5.303 11.974-11.974 11.974s-11.975-5.303-11.975-11.974V43.622h-11.975v59.873c0 13.172 10.777 23.949 23.95 23.949s23.949-10.777 23.949-23.95V67.572c0-6.672 5.303-11.975 11.974-11.975s11.975 5.303 11.975 11.975v35.924c0 13.172 10.777 23.949 23.95 23.949 13.171 0 23.948-10.777 23.948-23.95V43.623z" /></svg>;

export function JwtLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "JWT",
  className,
  ...props
}: JwtLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default JwtLogo;
