/**
 * k6 logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/k6).
 * Artwork: Simple Icons (CC0-1.0). k6 is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type K6LogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#7d64ff" viewBox="0 0 24 24" {...props}><path d="M24 23.646H0L7.99 6.603l4.813 3.538L19.08.354Zm-8.8-3.681h.052a2.3 2.3 0 0 0 1.593-.64 2.1 2.1 0 0 0 .685-1.576 1.91 1.91 0 0 0-.66-1.511 2 2 0 0 0-1.37-.59h-.04a.7.7 0 0 0-.199.027l1.267-1.883-1.01-.705-.477.705-1.22 1.864c-.21.31-.386.582-.495.77q-.169.301-.29.625a1.9 1.9 0 0 0-.138.719 2.1 2.1 0 0 0 .676 1.558c.422.411.989.641 1.578.64Zm-5.365-2.027 1.398 1.978h1.496l-1.645-2.295 1.46-2.029-.97-.671-.427.565-1.314 1.853v-3.725l-1.31-1.068v7.37h1.31v-1.98Zm5.367.792a.963.963 0 1 1 0-1.927h.009a.94.94 0 0 1 .679.29.9.9 0 0 1 .29.668.98.98 0 0 1-.977.967Z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M24 23.646H0L7.99 6.603l4.813 3.538L19.08.354Zm-8.8-3.681h.052a2.3 2.3 0 0 0 1.593-.64 2.1 2.1 0 0 0 .685-1.576 1.91 1.91 0 0 0-.66-1.511 2 2 0 0 0-1.37-.59h-.04a.7.7 0 0 0-.199.027l1.267-1.883-1.01-.705-.477.705-1.22 1.864c-.21.31-.386.582-.495.77q-.169.301-.29.625a1.9 1.9 0 0 0-.138.719 2.1 2.1 0 0 0 .676 1.558c.422.411.989.641 1.578.64Zm-5.365-2.027 1.398 1.978h1.496l-1.645-2.295 1.46-2.029-.97-.671-.427.565-1.314 1.853v-3.725l-1.31-1.068v7.37h1.31v-1.98Zm5.367.792a.963.963 0 1 1 0-1.927h.009a.94.94 0 0 1 .679.29.9.9 0 0 1 .29.668.98.98 0 0 1-.977.967Z" /></svg>;

export function K6Logo({
  variant = "color",
  title = "k6",
  className,
  ...props
}: K6LogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default K6Logo;
