/**
 * KDE logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/kde).
 * Artwork: gilbarbara/logos (CC0-1.0). KDE is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type KdeLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#1d99f3" d="M256 0v256H0V0z" /><path fill="#fcfcfc" d="m143.025 32.309-31.88 3.052v131.27l31.543-4.748v-55.968l42.4 62.076 33.239-10.518-43.416-59.698 43.756-56.308-33.917-7.798-42.061 56.305zM70.762 64.298c-.36.037-.708.196-.978.467l-12.512 12.51a1.62 1.62 0 0 0-.238 1.985l14.65 24.127a62.6 62.6 0 0 0-6.17 14.046l-26.893 5.593a1.62 1.62 0 0 0-1.288 1.586v17.693c0 .748.512 1.396 1.233 1.57l26.103 6.38a62.5 62.5 0 0 0 6.4 16.223l-15.109 23.04a1.62 1.62 0 0 0 .211 2.034l12.508 12.51a1.63 1.63 0 0 0 1.989.242l23.676-14.38a62.6 62.6 0 0 0 14.967 6.228l5.524 26.56c.156.753.82 1.288 1.584 1.288h17.694c.744 0 1.393-.508 1.57-1.238l6.507-26.615a62.4 62.4 0 0 0 15.397-6.478l23.332 15.298c.641.423 1.49.338 2.034-.206l12.512-12.51c.53-.529.625-1.347.236-1.984l-8.518-14.037-2.755.871a.95.95 0 0 1-1.077-.373l-12.449-18.222c-8.387 16.416-25.452 27.66-45.158 27.66-27.998 0-50.696-22.698-50.696-50.697 0-20.597 12.285-38.31 29.921-46.246V76.144a62.5 62.5 0 0 0-9.26 4.082q-.001-.003-.013-.015L71.816 64.55a1.62 1.62 0 0 0-1.055-.257z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M13.881 0 9.89.382v16.435l3.949-.594V9.216l5.308 7.772 4.162-1.317-5.436-7.475 5.479-7.05L19.105.17 13.84 7.22zM4.834 4.005a.2.2 0 0 0-.123.059L3.145 5.63a.2.2 0 0 0-.03.248L4.949 8.9a7.8 7.8 0 0 0-.772 1.759l-3.367.7a.2.2 0 0 0-.162.199v2.215c0 .093.064.174.155.196l3.268.8a7.8 7.8 0 0 0 .801 2.03L2.98 19.683a.2.2 0 0 0 .027.254l1.566 1.567a.204.204 0 0 0 .249.03l2.964-1.8c.582.336 1.21.6 1.874.78l.692 3.325c.02.094.102.161.198.161h2.215a.2.2 0 0 0 .197-.155l.815-3.332a7.8 7.8 0 0 0 1.927-.811l2.922 1.915c.08.053.186.042.254-.026l1.567-1.566a.2.2 0 0 0 .03-.248l-1.067-1.758-.345.11a.12.12 0 0 1-.135-.047L17.371 15.8a6.347 6.347 0 1 1-8.255-8.674V5.488c-.401.14-.79.31-1.159.511l-.001-.002-2.99-1.96a.2.2 0 0 0-.132-.033Z" /></svg>;

export function KdeLogo({
  variant = "color",
  title = "KDE",
  className,
  ...props
}: KdeLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default KdeLogo;
