/**
 * Kilo logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/kilo).
 * Artwork: gilbarbara/logos (CC0-1.0). Kilo is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type KiloLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#231f20" d="M0 0v256h256V0zm237.037 237.037H18.963V18.963h218.074zm-80.593-52.948h23.704v18.963H150.35l-12.868-12.868v-29.8h18.963zm42.667 0h-18.963v-23.704h-23.704v-18.963h29.8l12.867 12.868zm-80.592-27.644H99.556v-18.963h18.963zm-61.63-18.963h18.963v42.667h42.667v18.963H69.757l-12.868-12.868zM199.11 99.556v18.963h-61.63V99.556h21.193V75.852H137.48V56.889h27.288l12.868 12.868v29.799zM75.851 78.222h23.705l18.963 18.963v21.334H99.556V97.185H75.852v21.334H56.889v-61.63h18.963zm42.668 0H99.556V56.89h18.963z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="currentColor" d="M0 0v256h256V0zm237.037 237.037H18.963V18.963h218.074zm-80.593-52.948h23.704v18.963H150.35l-12.868-12.868v-29.8h18.963zm42.667 0h-18.963v-23.704h-23.704v-18.963h29.8l12.867 12.868zm-80.592-27.644H99.556v-18.963h18.963zm-61.63-18.963h18.963v42.667h42.667v18.963H69.757l-12.868-12.868zM199.11 99.556v18.963h-61.63V99.556h21.193V75.852H137.48V56.889h27.288l12.868 12.868v29.799zM75.851 78.222h23.705l18.963 18.963v21.334H99.556V97.185H75.852v21.334H56.889v-61.63h18.963zm42.668 0H99.556V56.89h18.963z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#ffffff" d="M0 0v256h256V0zm237.037 237.037H18.963V18.963h218.074zm-80.593-52.948h23.704v18.963H150.35l-12.868-12.868v-29.8h18.963zm42.667 0h-18.963v-23.704h-23.704v-18.963h29.8l12.867 12.868zm-80.592-27.644H99.556v-18.963h18.963zm-61.63-18.963h18.963v42.667h42.667v18.963H69.757l-12.868-12.868zM199.11 99.556v18.963h-61.63V99.556h21.193V75.852H137.48V56.889h27.288l12.868 12.868v29.799zM75.851 78.222h23.705l18.963 18.963v21.334H99.556V97.185H75.852v21.334H56.889v-61.63h18.963zm42.668 0H99.556V56.89h18.963z" /></svg>;

export function KiloLogo({
  variant = "color",
  mode = "auto",
  title = "Kilo",
  className,
  ...props
}: KiloLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default KiloLogo;
