/**
 * Kuda logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/kuda).
 * Artwork: official website (trademark). Kuda is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type KudaLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 1392 352" {...props}><path fill="#000" d="M0 0h148.973v113.42c17.52 0 31.675-14.192 31.675-31.758V.116h154.658l-58.939 114.351h19.724c18.447 0 33.414 15.006 33.414 33.502V351.31H180.3V218.929c0-5.584-4.525-10.121-10.094-10.121h-21.349V351.31H0z" /><path fill="#000" d="M503.091.35v231.377c0 5.583 4.525 10.12 10.094 10.12h11.602c5.569 0 10.094-4.537 10.094-10.12V.351H683.97v284.072c0 36.992-29.933 67.005-66.829 67.005H420.946c-36.895 0-66.829-30.013-66.829-67.005V.234h149.09-.116z" /><path fill="#000" d="M971.108 0c36.892 0 66.832 30.013 66.832 67.005v217.3c0 36.992-29.94 66.889-66.832 66.889H708.084V0zM857.173 108.534v133.079h21.465c5.569 0 10.094-4.537 10.094-10.121V118.654c0-5.583-4.525-10.12-10.094-10.12z" /><path fill="#000" d="M1392.24 351.194 1356.04 0h-273.23l-33.41 351.194h147.23l5.92-62.119h36.66l5.68 62.119zm-189.81-142.269 8.01-95.273h20.65l8 95.273z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="none" className="kuda-wp-block-acf-landing-hero__logo-svg" viewBox="0 0 1392 352" {...props}><path fill="currentColor" d="M0 0h148.973v113.42c17.52 0 31.675-14.192 31.675-31.758V.116h154.658l-58.939 114.351h19.724c18.447 0 33.414 15.006 33.414 33.502V351.31H180.3V218.929c0-5.584-4.525-10.121-10.094-10.121h-21.349V351.31H0z" className="kuda-wp-block-acf-landing-hero__logo-svg-letter" data-letter="k" /><path fill="currentColor" d="M503.091.35v231.377c0 5.583 4.525 10.12 10.094 10.12h11.602c5.569 0 10.094-4.537 10.094-10.12V.351H683.97v284.072c0 36.992-29.933 67.005-66.829 67.005H420.946c-36.895 0-66.829-30.013-66.829-67.005V.234h149.09-.116z" className="kuda-wp-block-acf-landing-hero__logo-svg-letter" data-letter="u" /><path fill="currentColor" d="M971.108 0c36.892 0 66.832 30.013 66.832 67.005v217.3c0 36.992-29.94 66.889-66.832 66.889H708.084V0zM857.173 108.534v133.079h21.465c5.569 0 10.094-4.537 10.094-10.121V118.654c0-5.583-4.525-10.12-10.094-10.12z" className="kuda-wp-block-acf-landing-hero__logo-svg-letter" data-letter="d" /><path fill="currentColor" d="M1392.24 351.194 1356.04 0h-273.23l-33.41 351.194h147.23l5.92-62.119h36.66l5.68 62.119zm-189.81-142.269 8.01-95.273h20.65l8 95.273z" className="kuda-wp-block-acf-landing-hero__logo-svg-letter" data-letter="a" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 1392 352" {...props}><path fill="#ffffff" d="M0 0h148.973v113.42c17.52 0 31.675-14.192 31.675-31.758V.116h154.658l-58.939 114.351h19.724c18.447 0 33.414 15.006 33.414 33.502V351.31H180.3V218.929c0-5.584-4.525-10.121-10.094-10.121h-21.349V351.31H0z" /><path fill="#ffffff" d="M503.091.35v231.377c0 5.583 4.525 10.12 10.094 10.12h11.602c5.569 0 10.094-4.537 10.094-10.12V.351H683.97v284.072c0 36.992-29.933 67.005-66.829 67.005H420.946c-36.895 0-66.829-30.013-66.829-67.005V.234h149.09-.116z" /><path fill="#ffffff" d="M971.108 0c36.892 0 66.832 30.013 66.832 67.005v217.3c0 36.992-29.94 66.889-66.832 66.889H708.084V0zM857.173 108.534v133.079h21.465c5.569 0 10.094-4.537 10.094-10.121V118.654c0-5.583-4.525-10.12-10.094-10.12z" /><path fill="#ffffff" d="M1392.24 351.194 1356.04 0h-273.23l-33.41 351.194h147.23l5.92-62.119h36.66l5.68 62.119zm-189.81-142.269 8.01-95.273h20.65l8 95.273z" /></svg>;

export function KudaLogo({
  variant = "color",
  mode = "auto",
  title = "Kuda",
  className,
  ...props
}: KudaLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default KudaLogo;
