/**
 * LevelDB logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/leveldb).
 * Artwork: gilbarbara/logos (CC0-1.0). LevelDB is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type LeveldbLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 329" {...props}><path fill="#d4eb95" d="M128 72.17 0 135.367v128.535l128 64.268 128-64.268V135.367z" /><path fill="#96dc75" d="M128 51.745 0 114.94v128.536l128 64.268 128-64.268V114.94z" /><path fill="#317342" d="M128 0 0 63.197v128.535L128 256l128-64.268V63.197z" opacity={0.553} /><path fill="#34954c" d="M128 122.795 0 62.638v128.908L128 256l128-64.454V62.638z" opacity={0.553} /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 329" {...props}><defs><mask id="leveldb-mono-cut-mono" maskUnits="userSpaceOnUse" x={0} y={0} width={256} height={329}><g fill="#000"><path fill="#fff" d="M128 72.17 0 135.367v128.535l128 64.268 128-64.268V135.367z" /><path fill="#fff" d="M128 51.745 0 114.94v128.536l128 64.268 128-64.268V114.94z" /><path fill="#000" d="M128 0 0 63.197v128.535L128 256l128-64.268V63.197z" opacity={0.553} /><path fill="#000" d="M128 122.795 0 62.638v128.908L128 256l128-64.454V62.638z" opacity={0.553} /></g></mask></defs><rect x={0} y={0} width={256} height={329} fill="currentColor" mask="url(#leveldb-mono-cut-mono)" /></svg>;

export function LeveldbLogo({
  variant = "color",
  title = "LevelDB",
  className,
  ...props
}: LeveldbLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default LeveldbLogo;
