/**
 * Linkerd logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/linkerd).
 * Artwork: gilbarbara/logos (CC0-1.0). Linkerd is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type LinkerdLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 239" {...props}><defs><linearGradient id="linkerd-a" x1="50%" x2="50%" y1="0%" y2="100%"><stop offset="0%" stopColor="#4ad8ac" /><stop offset="100%" stopColor="#4076c4" /></linearGradient></defs><path fill="#40a0b4" d="m238.218 141.656 17.777 10.263v-96.4l-17.777-10.267zM0 55.52v96.405l17.778-10.268V45.255zm78.232 172.438 17.778 10.263 42.329-24.439-17.778-10.263z" /><path fill="#338090" d="m103.118 213.59 17.777 10.265 17.444-10.073-17.778-10.263z" /><path fill="#45c1a8" d="M168.884 198.188V177.66l-76.546-44.195-5.226 3.017.009.005v14.494zm-81.764-2.044L160 238.222l17.781-10.263-90.661-52.345z" /><path fill="#7ce1c0" d="m194.712 70.374 17.776 10.263 43.508-25.118-17.782-10.261zm-57.722 53.855-17.778-10.263-40.988 23.666L96 147.895zm79.903-91.286L199.11 22.679l-43.5 25.119 17.778 10.265zm-119.005 68.71L80.11 91.39l-40.99 23.665 17.78 10.263zm18.619-76.431 17.778 10.263 43.506-25.118L160.009.104zM.02 92.478l17.777 10.263 40.988-23.664-17.777-10.265z" /><g fill="url(#linkerd-a)" transform="translate(0 92.444)"><path d="M238.218 10.29v90.327l17.777-10.265V.027z" /><path d="M216.884 112.933V22.607L199.106 32.87v90.328z" /><path d="M159.994 55.451v90.327l17.78-10.264V45.186z" /><path d="m78.232 135.514 17.778 10.263V55.453L78.232 45.187z" /><path d="M56.899 32.871v90.326L39.12 112.934V22.607z" /><path d="m.01 90.352 17.777 10.263V10.29L.01.025z" /></g><path fill="#45c1a8" d="m103.108 123.263 17.778 10.263 16.105-9.297-17.778-10.263zM24.904 78.11l17.778 10.264 16.103-9.298-17.776-10.263zm39.102 22.577 17.778 10.263 16.103-9.298L80.11 91.39z" /><path fill="#a2eacf" d="m96.002.094-17.78 10.263 159.993 92.375 17.78-10.263zM56.89 22.676 39.111 32.939l159.99 92.375 17.782-10.263zM0 55.52l159.991 92.375 17.781-10.263L17.778 45.257z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M22.329 5.04v9.034l1.666.964V6.004zM0 15.038l1.666-.964V5.04L0 6.004zm8.165-.089 7.665 4.424V17.45l-7.176-4.142-.489.282zm8.105 6.989-8.105-4.681v1.923l2.164 1.25-2.604 1.503a.263.263 0 0 0 0 .454l1.27.737 3-1.73 3 1.73 1.27-.737c.178-.093.178-.35.005-.449m6.059-11.511v8.012c0 .202.218.331.396.227l1.142-.657a.27.27 0 0 0 .133-.228V9.468zm-3.271 10.354 1.072-.623a.39.39 0 0 0 .198-.341v-8.233l-1.666.963v8.012c0 .198.218.326.396.222m-4.063 2.348 1.537-.885a.27.27 0 0 0 .134-.227v-8.318l-1.671.964zm-7.532-.89L9 23.124v-8.461l-1.666-.964v8.313c0 .094.05.183.129.227m-3.598-2.076 1.072.623a.265.265 0 0 0 .396-.227v-8.017l-1.666-.963v8.238c0 .144.074.277.198.346M.198 18.048l1.072.623a.265.265 0 0 0 .396-.228v-8.016L0 9.468v8.239c0 .138.074.267.198.341M23.995 6.004l-1.666-.964-3 1.73-1.996-1.152 2.604-1.502a.264.264 0 0 0 0-.455l-1.077-.623a.4.4 0 0 0-.395 0l-2.803 1.616-1.996-1.151L16.27 2a.263.263 0 0 0 0-.454L15.193.923a.4.4 0 0 0-.396 0l-2.802 1.616L9.193.923a.4.4 0 0 0-.396 0l-1.077.623a.263.263 0 0 0 0 .454l14.6 8.432 1.665-.964-3-1.73zM5.135 3.038l-1.072.623a.264.264 0 0 0 0 .455l14.599 8.431 1.666-.963L5.53 3.038a.4.4 0 0 0-.395 0M0 6.004l3 1.729-3 1.735 1.671.959 2.995-1.73 2.001 1.157-3 1.73 1.666.963 3-1.734 1.996 1.156-3 1.73L9 14.663l2.995-1.735 3 1.735 1.666-.964L1.666 5.04z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 239" {...props}><defs><linearGradient id="linkerd-a-dark" x1="50%" x2="50%" y1="0%" y2="100%"><stop offset="0%" stopColor="#4ad8ac" /><stop offset="100%" stopColor="#4076c4" /></linearGradient></defs><path fill="#40a0b4" d="m238.218 141.656 17.777 10.263v-96.4l-17.777-10.267zM0 55.52v96.405l17.778-10.268V45.255zm78.232 172.438 17.778 10.263 42.329-24.439-17.778-10.263z" /><path fill="#338090" d="m103.118 213.59 17.777 10.265 17.444-10.073-17.778-10.263z" /><path fill="#45c1a8" d="M168.884 198.188V177.66l-76.546-44.195-5.226 3.017.009.005v14.494zm-81.764-2.044L160 238.222l17.781-10.263-90.661-52.345z" /><path fill="#7ce1c0" d="m194.712 70.374 17.776 10.263 43.508-25.118-17.782-10.261zm-57.722 53.855-17.778-10.263-40.988 23.666L96 147.895zm79.903-91.286L199.11 22.679l-43.5 25.119 17.778 10.265zm-119.005 68.71L80.11 91.39l-40.99 23.665 17.78 10.263zm18.619-76.431 17.778 10.263 43.506-25.118L160.009.104zM.02 92.478l17.777 10.263 40.988-23.664-17.777-10.265z" /><g fill="url(#linkerd-a-dark)" transform="translate(0 92.444)"><path d="M238.218 10.29v90.327l17.777-10.265V.027z" /><path d="M216.884 112.933V22.607L199.106 32.87v90.328z" /><path d="M159.994 55.451v90.327l17.78-10.264V45.186z" /><path d="m78.232 135.514 17.778 10.263V55.453L78.232 45.187z" /><path d="M56.899 32.871v90.326L39.12 112.934V22.607z" /><path d="m.01 90.352 17.777 10.263V10.29L.01.025z" /></g><path fill="#45c1a8" d="m103.108 123.263 17.778 10.263 16.105-9.297-17.778-10.263zM24.904 78.11l17.778 10.264 16.103-9.298-17.776-10.263zm39.102 22.577 17.778 10.263 16.103-9.298L80.11 91.39z" /><path fill="#a2eacf" d="m96.002.094-17.78 10.263 159.993 92.375 17.78-10.263zM56.89 22.676 39.111 32.939l159.99 92.375 17.782-10.263zM0 55.52l159.991 92.375 17.781-10.263L17.778 45.257z" /></svg>;

export function LinkerdLogo({
  variant = "color",
  mode = "auto",
  title = "Linkerd",
  className,
  ...props
}: LinkerdLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default LinkerdLogo;
