/**
 * Lit logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/lit).
 * Artwork: gilbarbara/logos (CC0-1.0). Lit is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type LitLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 320" {...props}><path fill="#00e8ff" d="m64 192 25.926-44.727 38.233-19.114 63.974 63.974 10.833 61.754L192 320l-64-64-38.074-25.615z" /><path fill="#283198" d="M128 256V128l64-64v128zM0 256l64 64 9.202-60.602L64 192l-37.542 23.71z" /><path fill="#324fff" d="M64 192V64l64-64v128zm128 128V192l64-64v128zM0 256V128l64 64z" /><path fill="#0ff" d="M64 320V192l64 64z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m2.4 9.6 4.8 4.8V24l-4.8-4.8zm4.8-4.8v9.6L12 9.6V0zM12 9.6v9.6l4.8-4.8V4.8zm4.8 4.8V24l4.8-4.8V9.6z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 242" {...props}><path d="M475.256 93.967v34.696H512v18.793h-36.744v42.888c0 4.336.12 8.673.603 12.408.964 6.385 4.819 12.65 10.12 15.059 6.866 3.132 11.685 2.53 26.021 2.048l-3.494 20.72c-.963.483-4.818.362-8.433.362-8.433 0-40.237 3.012-46.742-29.756-1.084-5.662-.843-11.445-.843-20.36v-43.128h-16.384l.24-19.155h16.144V93.967zm-62.283 34.575v110.23h-22.648v-110.23zm0-34.575v19.637h-22.89V93.967zM312.26 217.088h58.067l-21.685 21.685h-59.513V93.967h23.13z" /><path fill="#00e8ff" d="m48.188 144.565 19.52-33.677 28.788-14.392 48.169 48.169 8.156 46.497-8.256 49.78-48.189-48.19-28.667-19.286z" /><path fill="#283198" d="M96.376 192.753V96.376l48.189-48.188v96.377zm-96.376 0 48.188 48.188 6.929-45.63-6.929-50.746-28.267 17.851z" /><path fill="#324fff" d="M48.188 144.565V48.188L96.376 0v96.376zm96.377 96.376v-96.376l48.188-48.189v96.377zM0 192.753V96.376l48.188 48.189z" /><path fill="#0ff" d="M48.188 240.941v-96.376l48.188 48.188z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 320" {...props}><path fill="#00e8ff" d="m64 192 25.926-44.727 38.233-19.114 63.974 63.974 10.833 61.754L192 320l-64-64-38.074-25.615z" /><path fill="#4c57d0" d="M128 256V128l64-64v128zM0 256l64 64 9.202-60.602L64 192l-37.542 23.71z" /><path fill="#324fff" d="M64 192V64l64-64v128zm128 128V192l64-64v128zM0 256V128l64 64z" /><path fill="#0ff" d="M64 320V192l64 64z" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 242" {...props}><path d="M475.256 93.967v34.696H512v18.793h-36.744v42.888c0 4.336.12 8.673.603 12.408.964 6.385 4.819 12.65 10.12 15.059 6.866 3.132 11.685 2.53 26.021 2.048l-3.494 20.72c-.963.483-4.818.362-8.433.362-8.433 0-40.237 3.012-46.742-29.756-1.084-5.662-.843-11.445-.843-20.36v-43.128h-16.384l.24-19.155h16.144V93.967zm-62.283 34.575v110.23h-22.648v-110.23zm0-34.575v19.637h-22.89V93.967zM312.26 217.088h58.067l-21.685 21.685h-59.513V93.967h23.13z" /><path fill="#00e8ff" d="m48.188 144.565 19.52-33.677 28.788-14.392 48.169 48.169 8.156 46.497-8.256 49.78-48.189-48.19-28.667-19.286z" /><path fill="#4c57d0" d="M96.376 192.753V96.376l48.189-48.188v96.377zm-96.376 0 48.188 48.188 6.929-45.63-6.929-50.746-28.267 17.851z" /><path fill="#324fff" d="M48.188 144.565V48.188L96.376 0v96.376zm96.377 96.376v-96.376l48.188-48.189v96.377zM0 192.753V96.376l48.188 48.189z" /><path fill="#0ff" d="M48.188 240.941v-96.376l48.188 48.188z" /></svg>;

export function LitLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "Lit",
  className,
  ...props
}: LitLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default LitLogo;
