/**
 * Lodash logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/lodash).
 * Artwork: gilbarbara/logos (CC0-1.0). Lodash is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type LodashLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 233" {...props}><g fill="none" fillRule="evenodd"><path fill="#000" d="M.388 0H24.18v157.893h94.087v19.466H.387zm182.766 46.503c16.222-2.163 33.526 1.081 46.503 11.896 14.06 9.733 21.63 27.036 22.71 43.258 2.164 19.466 0 38.933-10.814 55.155-9.733 12.977-24.873 21.629-42.177 22.71-16.222 2.163-34.606-1.081-48.665-11.896-12.978-10.814-19.467-27.036-21.63-43.258-2.162-17.304 0-36.77 10.815-51.91 8.652-15.14 25.955-24.874 43.258-25.955m3.245 18.385c10.814-1.082 22.71 2.162 31.362 9.733 7.57 8.651 11.896 19.466 12.978 30.28 1.081 11.897 0 24.874-5.408 35.689-5.407 10.814-15.14 18.385-27.036 20.547-10.815 2.163-22.71-1.081-30.281-7.57-8.652-6.489-14.059-16.222-16.222-25.955-2.163-14.059-1.081-28.118 4.326-41.095 5.407-11.896 17.303-20.548 30.28-21.63" /><path fill="#3492ff" d="M.388 205.477h255.224v27.037H.388z" /></g></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M0 20.253h24v2.542H0zM18.061 5.212l.223.031c1.933-.071 3.885 1.006 4.882 2.674.844 1.566.976 3.458.712 5.187-.204 1.657-1.149 3.234-2.644 4.027-2.177 1.139-5.085 1.017-7.017-.59-1.994-1.942-2.461-5.136-1.444-7.678.711-2.207 3-3.661 5.288-3.63zm.234 1.8h-.183c-1.424-.03-2.777.915-3.285 2.237-.732 1.831-.732 4.17.691 5.695 1.17 1.434 3.458 1.597 4.882.438 1.525-1.312 1.83-3.59 1.322-5.451-.275-1.648-1.78-2.929-3.458-2.929zM0 1.205h2.237v14.847h8.848v1.831H0z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 233" {...props}><g fill="none" fillRule="evenodd"><path fill="#ffffff" d="M.388 0H24.18v157.893h94.087v19.466H.387zm182.766 46.503c16.222-2.163 33.526 1.081 46.503 11.896 14.06 9.733 21.63 27.036 22.71 43.258 2.164 19.466 0 38.933-10.814 55.155-9.733 12.977-24.873 21.629-42.177 22.71-16.222 2.163-34.606-1.081-48.665-11.896-12.978-10.814-19.467-27.036-21.63-43.258-2.162-17.304 0-36.77 10.815-51.91 8.652-15.14 25.955-24.874 43.258-25.955m3.245 18.385c10.814-1.082 22.71 2.162 31.362 9.733 7.57 8.651 11.896 19.466 12.978 30.28 1.081 11.897 0 24.874-5.408 35.689-5.407 10.814-15.14 18.385-27.036 20.547-10.815 2.163-22.71-1.081-30.281-7.57-8.652-6.489-14.059-16.222-16.222-25.955-2.163-14.059-1.081-28.118 4.326-41.095 5.407-11.896 17.303-20.548 30.28-21.63" /><path fill="#3492ff" d="M.388 205.477h255.224v27.037H.388z" /></g></svg>;

export function LodashLogo({
  variant = "color",
  mode = "auto",
  title = "Lodash",
  className,
  ...props
}: LodashLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default LodashLogo;
