/**
 * Meteor logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/meteor).
 * Artwork: gilbarbara/logos (CC0-1.0). Meteor is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type MeteorLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 251" {...props}><path fill="#df4f4f" d="M.439.438 219.3 232.266s7.457 5.259 13.158-.877c5.702-6.135 1.316-12.27 1.316-12.27zM69.738 22.35l166.668 179.677s7.456 5.26 13.158-.876c5.702-6.135 1.316-12.27 1.316-12.27zM21.053 69.242 187.72 248.919s7.456 5.259 13.158-.877c5.702-6.135 1.316-12.27 1.316-12.27zM128.32 41.194l116.442 125.53s5.21 3.674 9.193-.612c3.983-4.287.919-8.573.919-8.573zm-91.228 82.389 116.441 125.53s5.21 3.674 9.193-.613c3.983-4.286.919-8.572.919-8.572zM188.16 68.365l52.775 57.067s2.577 1.722 4.547-.287.455-4.017.455-4.017zM66.229 181.43l52.775 57.067s2.577 1.722 4.547-.286.455-4.017.455-4.017z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m0 .234 21.912 20.537s.412.575-.124 1.151c-.535.576-1.236.083-1.236.083zm6.508 2.058 17.01 15.638s.413.576-.123 1.152c-.534.576-1.235.083-1.235.083zM1.936 6.696l17.01 15.638s.412.576-.123 1.152-1.235.082-1.235.082zm10.073-2.635 11.886 10.927s.287.401-.087.805-.863.058-.863.058zm-8.567 7.737 11.886 10.926s.285.4-.088.803c-.375.403-.863.059-.863.059zm14.187-5.185 5.426 4.955s.142.188-.044.377c-.185.188-.428.027-.428.027l-4.954-5.358zM6.178 17.231l5.425 4.956s.144.188-.042.377-.427.026-.427.026z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 124" {...props}><g fillRule="evenodd"><path fill="#df4f4f" d="m303.758.215 107.286 113.642s3.656 2.578 6.45-.43c2.796-3.007.646-6.014.646-6.014zm33.97 10.741 81.702 88.078s3.655 2.578 6.45-.43.645-6.014.645-6.014zm-23.865 22.986 81.701 88.079s3.655 2.578 6.45-.43.645-6.015.645-6.015zm52.583-13.748 57.08 61.535s2.553 1.8 4.506-.3c1.953-2.102.45-4.203.45-4.203zM321.725 60.58l57.08 61.536s2.554 1.8 4.506-.3c1.953-2.102.451-4.203.451-4.203zm74.055-27.067 25.87 27.974s1.263.844 2.229-.14c.966-.985.223-1.97.223-1.97zm-59.772 55.425 25.87 27.974s1.264.844 2.23-.14c.966-.985.223-1.97.223-1.97z" /><path fill="#26262c" d="M446.171 46.23v75.433h17.067V97.331h12.8l16.457 24.332H512l-18.286-26.157s16.238-6.418 16.238-23.826c0-24.576-22.333-25.448-22.333-25.448zm17.067 14.602v21.9h21.943s8.387-.002 8.387-10.952c0-11.365-10.216-10.948-10.216-10.948zm-206.019-14.6v75.431h57.295v-14.6h-40.228V91.249h34.743v-14.6h-34.743V60.82h40.228V46.232zm-82.895 0v14.6h22.552v60.831h17.067V60.832h22.552v-14.6zm-78.019 0v75.431H153.6v-14.6h-40.229V91.249h34.743v-14.6h-34.743V60.82H153.6V46.232zM0 46.23v75.435l17.055-.001V74.213l20.724 30.416 20.735-30.416v47.452h17.067V46.23H58.514L37.78 77.254 17.055 46.23z" /></g></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 124" {...props}><g fillRule="evenodd"><path fill="#df4f4f" d="m303.758.215 107.286 113.642s3.656 2.578 6.45-.43c2.796-3.007.646-6.014.646-6.014zm33.97 10.741 81.702 88.078s3.655 2.578 6.45-.43.645-6.014.645-6.014zm-23.865 22.986 81.701 88.079s3.655 2.578 6.45-.43.645-6.015.645-6.015zm52.583-13.748 57.08 61.535s2.553 1.8 4.506-.3c1.953-2.102.45-4.203.45-4.203zM321.725 60.58l57.08 61.536s2.554 1.8 4.506-.3c1.953-2.102.451-4.203.451-4.203zm74.055-27.067 25.87 27.974s1.263.844 2.229-.14c.966-.985.223-1.97.223-1.97zm-59.772 55.425 25.87 27.974s1.264.844 2.23-.14c.966-.985.223-1.97.223-1.97z" /><path fill="#ffffff" d="M446.171 46.23v75.433h17.067V97.331h12.8l16.457 24.332H512l-18.286-26.157s16.238-6.418 16.238-23.826c0-24.576-22.333-25.448-22.333-25.448zm17.067 14.602v21.9h21.943s8.387-.002 8.387-10.952c0-11.365-10.216-10.948-10.216-10.948zm-206.019-14.6v75.431h57.295v-14.6h-40.228V91.249h34.743v-14.6h-34.743V60.82h40.228V46.232zm-82.895 0v14.6h22.552v60.831h17.067V60.832h22.552v-14.6zm-78.019 0v75.431H153.6v-14.6h-40.229V91.249h34.743v-14.6h-34.743V60.82H153.6V46.232zM0 46.23v75.435l17.055-.001V74.213l20.724 30.416 20.735-30.416v47.452h17.067V46.23H58.514L37.78 77.254 17.055 46.23z" /></g></svg>;

export function MeteorLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "Meteor",
  className,
  ...props
}: MeteorLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default MeteorLogo;
