/**
 * MicroPython logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/micropython).
 * Artwork: gilbarbara/logos (CC0-1.0). MicroPython is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type MicropythonLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path d="M0 0h122.76v199.86h10.48V0H256v256h-56.14V56.14h-10.48V256H66.62V56.14l-10.48.375V256H0zm237.287 208.094h-14.971v25.45h14.97z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M0 0h11.509v18.737h.982V0H24v24h-5.263V5.263h-.983V24H6.246V5.263l-.983.035V24H0zm22.246 19.509h-1.404v2.386h1.404z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path d="M0 0h122.76v199.86h10.48V0H256v256h-56.14V56.14h-10.48V256H66.62V56.14l-10.48.375V256H0zm237.287 208.094h-14.971v25.45h14.97z" /></svg>;

export function MicropythonLogo({
  variant = "color",
  mode = "auto",
  title = "MicroPython",
  className,
  ...props
}: MicropythonLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default MicropythonLogo;
