/**
 * Microsoft Azure logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/microsoft-azure).
 * Artwork: gilbarbara/logos (CC0-1.0). Microsoft Azure is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type MicrosoftAzureLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 242" {...props}><defs><linearGradient id="microsoft-azure-a" x1="58.972%" x2="37.191%" y1="7.411%" y2="103.762%"><stop offset="0%" stopColor="#114a8b" /><stop offset="100%" stopColor="#0669bc" /></linearGradient><linearGradient id="microsoft-azure-b" x1="59.719%" x2="52.691%" y1="52.313%" y2="54.864%"><stop offset="0%" stopOpacity={0.3} /><stop offset="7.1%" stopOpacity={0.2} /><stop offset="32.1%" stopOpacity={0.1} /><stop offset="62.3%" stopOpacity={0.05} /><stop offset="100%" stopOpacity={0} /></linearGradient><linearGradient id="microsoft-azure-c" x1="37.279%" x2="62.473%" y1="4.6%" y2="99.979%"><stop offset="0%" stopColor="#3ccbf4" /><stop offset="100%" stopColor="#2892df" /></linearGradient></defs><path fill="url(#microsoft-azure-a)" d="M85.343.003h75.753L82.457 233a12.08 12.08 0 0 1-11.442 8.216H12.06A12.06 12.06 0 0 1 .633 225.303L73.898 8.219A12.08 12.08 0 0 1 85.343 0z" /><path fill="#0078d4" d="M195.423 156.282H75.297a5.56 5.56 0 0 0-3.796 9.627l77.19 72.047a12.14 12.14 0 0 0 8.28 3.26h68.02z" /><path fill="url(#microsoft-azure-b)" d="M85.343.003a11.98 11.98 0 0 0-11.471 8.376L.723 225.105a12.045 12.045 0 0 0 11.37 16.112h60.475a12.93 12.93 0 0 0 9.921-8.437l14.588-42.991 52.105 48.6a12.33 12.33 0 0 0 7.757 2.828h67.766l-29.721-84.935-86.643.02L161.37.003z" /><path fill="url(#microsoft-azure-c)" d="M182.098 8.207A12.06 12.06 0 0 0 170.67.003H86.245c5.175 0 9.773 3.301 11.428 8.204L170.94 225.3a12.062 12.062 0 0 1-11.428 15.92h84.429a12.062 12.062 0 0 0 11.425-15.92z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 242" {...props}><defs><linearGradient id="microsoft-azure-a-mono" x1="58.972%" x2="37.191%" y1="7.411%" y2="103.762%"><stop offset="0%" stopColor="currentColor" /><stop offset="100%" stopColor="currentColor" /></linearGradient><linearGradient id="microsoft-azure-b-mono" x1="59.719%" x2="52.691%" y1="52.313%" y2="54.864%"><stop offset="0%" stopOpacity={0.3} /><stop offset="7.1%" stopOpacity={0.2} /><stop offset="32.1%" stopOpacity={0.1} /><stop offset="62.3%" stopOpacity={0.05} /><stop offset="100%" stopOpacity={0} /></linearGradient><linearGradient id="microsoft-azure-c-mono" x1="37.279%" x2="62.473%" y1="4.6%" y2="99.979%"><stop offset="0%" stopColor="currentColor" /><stop offset="100%" stopColor="currentColor" /></linearGradient></defs><path fill="currentColor" d="M85.343.003h75.753L82.457 233a12.08 12.08 0 0 1-11.442 8.216H12.06A12.06 12.06 0 0 1 .633 225.303L73.898 8.219A12.08 12.08 0 0 1 85.343 0z" /><path fill="currentColor" d="M195.423 156.282H75.297a5.56 5.56 0 0 0-3.796 9.627l77.19 72.047a12.14 12.14 0 0 0 8.28 3.26h68.02z" /><path fill="currentColor" d="M85.343.003a11.98 11.98 0 0 0-11.471 8.376L.723 225.105a12.045 12.045 0 0 0 11.37 16.112h60.475a12.93 12.93 0 0 0 9.921-8.437l14.588-42.991 52.105 48.6a12.33 12.33 0 0 0 7.757 2.828h67.766l-29.721-84.935-86.643.02L161.37.003z" /><path fill="currentColor" d="M182.098 8.207A12.06 12.06 0 0 0 170.67.003H86.245c5.175 0 9.773 3.301 11.428 8.204L170.94 225.3a12.062 12.062 0 0 1-11.428 15.92h84.429a12.062 12.062 0 0 0 11.425-15.92z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 242" {...props}><defs><linearGradient id="microsoft-azure-a-dark" x1="58.972%" x2="37.191%" y1="7.411%" y2="103.762%"><stop offset="0%" stopColor="#1660b4" /><stop offset="100%" stopColor="#0669bc" /></linearGradient><linearGradient id="microsoft-azure-b-dark" x1="59.719%" x2="52.691%" y1="52.313%" y2="54.864%"><stop offset="0%" stopOpacity={0.3} /><stop offset="7.1%" stopOpacity={0.2} /><stop offset="32.1%" stopOpacity={0.1} /><stop offset="62.3%" stopOpacity={0.05} /><stop offset="100%" stopOpacity={0} /></linearGradient><linearGradient id="microsoft-azure-c-dark" x1="37.279%" x2="62.473%" y1="4.6%" y2="99.979%"><stop offset="0%" stopColor="#3ccbf4" /><stop offset="100%" stopColor="#2892df" /></linearGradient></defs><path fill="url(#microsoft-azure-a-dark)" d="M85.343.003h75.753L82.457 233a12.08 12.08 0 0 1-11.442 8.216H12.06A12.06 12.06 0 0 1 .633 225.303L73.898 8.219A12.08 12.08 0 0 1 85.343 0z" /><path fill="#0078d4" d="M195.423 156.282H75.297a5.56 5.56 0 0 0-3.796 9.627l77.19 72.047a12.14 12.14 0 0 0 8.28 3.26h68.02z" /><path fill="url(#microsoft-azure-b-dark)" d="M85.343.003a11.98 11.98 0 0 0-11.471 8.376L.723 225.105a12.045 12.045 0 0 0 11.37 16.112h60.475a12.93 12.93 0 0 0 9.921-8.437l14.588-42.991 52.105 48.6a12.33 12.33 0 0 0 7.757 2.828h67.766l-29.721-84.935-86.643.02L161.37.003z" /><path fill="url(#microsoft-azure-c-dark)" d="M182.098 8.207A12.06 12.06 0 0 0 170.67.003H86.245c5.175 0 9.773 3.301 11.428 8.204L170.94 225.3a12.062 12.062 0 0 1-11.428 15.92h84.429a12.062 12.062 0 0 0 11.425-15.92z" /></svg>;

export function MicrosoftAzureLogo({
  variant = "color",
  mode = "auto",
  title = "Microsoft Azure",
  className,
  ...props
}: MicrosoftAzureLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default MicrosoftAzureLogo;
