/**
 * Monero logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/monero).
 * Artwork: gilbarbara/logos (CC0-1.0). Monero is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type MoneroLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#f60" d="M127.998 0C57.318 0 0 57.317 0 127.999c0 14.127 2.29 27.716 6.518 40.43H44.8V60.734l83.2 83.2 83.198-83.2v107.694h38.282c4.231-12.714 6.521-26.303 6.521-40.43C256 57.316 198.681 0 127.998 0" /><path fill="#4c4c4c" d="m108.867 163.062-36.31-36.311v67.765H18.623c22.47 36.863 63.051 61.48 109.373 61.48s86.907-24.617 109.374-61.48h-53.933V126.75l-36.31 36.31-19.13 19.129-19.128-19.128z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><defs><mask id="monero-mono-cut-mono" maskUnits="userSpaceOnUse" x={0} y={0} width={256} height={256}><g fill="#000"><path fill="#fff" d="M127.998 0C57.318 0 0 57.317 0 127.999c0 14.127 2.29 27.716 6.518 40.43H44.8V60.734l83.2 83.2 83.198-83.2v107.694h38.282c4.231-12.714 6.521-26.303 6.521-40.43C256 57.316 198.681 0 127.998 0" /><path fill="#000" d="m108.867 163.062-36.31-36.311v67.765H18.623c22.47 36.863 63.051 61.48 109.373 61.48s86.907-24.617 109.374-61.48h-53.933V126.75l-36.31 36.31-19.13 19.129-19.128-19.128z" /></g></mask></defs><rect x={0} y={0} width={256} height={256} fill="currentColor" mask="url(#monero-mono-cut-mono)" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#f60" d="M127.998 0C57.318 0 0 57.317 0 127.999c0 14.127 2.29 27.716 6.518 40.43H44.8V60.734l83.2 83.2 83.198-83.2v107.694h38.282c4.231-12.714 6.521-26.303 6.521-40.43C256 57.316 198.681 0 127.998 0" /><path fill="#ffffff" d="m108.867 163.062-36.31-36.311v67.765H18.623c22.47 36.863 63.051 61.48 109.373 61.48s86.907-24.617 109.374-61.48h-53.933V126.75l-36.31 36.31-19.13 19.129-19.128-19.128z" /></svg>;

export function MoneroLogo({
  variant = "color",
  mode = "auto",
  title = "Monero",
  className,
  ...props
}: MoneroLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default MoneroLogo;
