/**
 * Nodemon logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/nodemon).
 * Artwork: gilbarbara/logos (CC0-1.0). Nodemon is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type NodemonLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 292" {...props}><path fill="#76d04b" d="M120.947 289.19a13.76 13.76 0 0 0 13.77 0l114.08-65.83a13.77 13.77 0 0 0 6.893-11.935V79.664a13.79 13.79 0 0 0-6.886-11.934L134.724 1.846a13.79 13.79 0 0 0-13.785 0L6.889 67.73A13.79 13.79 0 0 0 0 79.664v131.77c0 4.918 2.627 9.465 6.892 11.925l114.054 65.83" /><path fill="#4f4d3f" d="m201.701 114.111-5.087-2.928c7.823-11.539 12.498-28.888 6.636-54.825 0 0-13.202 36.999-39.74 35.773L132.437 74.25a8.1 8.1 0 0 0-3.813-1.109h-.717a8.2 8.2 0 0 0-3.824 1.109L93.006 92.13c-26.535 1.23-39.74-35.773-39.74-35.773-5.866 25.936-1.183 43.285 6.638 54.825l-5.087 2.929a8.39 8.39 0 0 0-4.19 7.271l.153 107.332c0 1.498.775 2.885 2.09 3.614a4 4 0 0 0 4.155 0l41.164-23.572c2.605-1.547 4.189-4.276 4.189-7.26v-50.142c0-2.99 1.584-5.762 4.177-7.243l17.529-10.094a8.27 8.27 0 0 1 4.193-1.13 8.16 8.16 0 0 1 4.162 1.129l17.523 10.094a8.33 8.33 0 0 1 4.183 7.242v50.143c0 2.983 1.605 5.733 4.194 7.26l41.154 23.57a4.06 4.06 0 0 0 4.184 0 4.17 4.17 0 0 0 2.077-3.614l.134-107.332c-.003-3.018-1.586-5.784-4.186-7.27z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m22.33 7.851-.716-.398c1.101-1.569 1.758-3.927.934-7.453 0 0-1.857 5.029-5.59 4.863l-4.37-2.431a1.2 1.2 0 0 0-.536-.15h-.101a1.2 1.2 0 0 0-.538.15L7.042 4.863C3.309 5.03 1.452 0 1.452 0c-.825 3.526-.166 5.884.934 7.453l-.716.398a1.13 1.13 0 0 0-.589.988l.022 14.591c0 .203.109.392.294.491a.58.58 0 0 0 .584 0l5.79-3.204c.366-.211.589-.582.589-.987v-6.817c0-.406.223-.783.588-.984l2.465-1.372a1.2 1.2 0 0 1 .59-.154c.2 0 .407.05.585.154l2.465 1.372c.365.201.588.578.588.984v6.817c0 .405.226.779.59.987l5.788 3.204a.59.59 0 0 0 .589 0 .56.56 0 0 0 .292-.491l.019-14.591a1.13 1.13 0 0 0-.589-.988" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 292" {...props}><path fill="#76d04b" d="M120.947 289.19a13.76 13.76 0 0 0 13.77 0l114.08-65.83a13.77 13.77 0 0 0 6.893-11.935V79.664a13.79 13.79 0 0 0-6.886-11.934L134.724 1.846a13.79 13.79 0 0 0-13.785 0L6.889 67.73A13.79 13.79 0 0 0 0 79.664v131.77c0 4.918 2.627 9.465 6.892 11.925l114.054 65.83" /><path fill="#ffffff" d="m201.701 114.111-5.087-2.928c7.823-11.539 12.498-28.888 6.636-54.825 0 0-13.202 36.999-39.74 35.773L132.437 74.25a8.1 8.1 0 0 0-3.813-1.109h-.717a8.2 8.2 0 0 0-3.824 1.109L93.006 92.13c-26.535 1.23-39.74-35.773-39.74-35.773-5.866 25.936-1.183 43.285 6.638 54.825l-5.087 2.929a8.39 8.39 0 0 0-4.19 7.271l.153 107.332c0 1.498.775 2.885 2.09 3.614a4 4 0 0 0 4.155 0l41.164-23.572c2.605-1.547 4.189-4.276 4.189-7.26v-50.142c0-2.99 1.584-5.762 4.177-7.243l17.529-10.094a8.27 8.27 0 0 1 4.193-1.13 8.16 8.16 0 0 1 4.162 1.129l17.523 10.094a8.33 8.33 0 0 1 4.183 7.242v50.143c0 2.983 1.605 5.733 4.194 7.26l41.154 23.57a4.06 4.06 0 0 0 4.184 0 4.17 4.17 0 0 0 2.077-3.614l.134-107.332c-.003-3.018-1.586-5.784-4.186-7.27z" /></svg>;

export function NodemonLogo({
  variant = "color",
  mode = "auto",
  title = "Nodemon",
  className,
  ...props
}: NodemonLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default NodemonLogo;
