/**
 * OpenCode logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/opencode).
 * Artwork: gilbarbara/logos (CC0-1.0). OpenCode is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type OpencodeLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 321" {...props}><path fill="#cfcecd" d="M191.985 256.287H63.983V128.144h128.002z" /><path fill="#211e1e" d="M192.001 64.072H63.999v192.214h128.002zM256 320.357H0V0h256z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M22 24H2V0h20zM17 4.8H7v14.4h10z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 92" {...props}><path fill="#cfcecd" d="M39.388 65.715H13.13V39.429h26.257z" /><path fill="#656363" d="M39.385 26.286H13.128v39.428h26.257zm13.128 52.571H0V13.143h52.513z" /><path fill="#cfcecd" d="M105.025 65.715H78.769V39.429h26.256z" /><path fill="#656363" d="M78.772 65.714h26.256V26.286H78.772zm39.385 13.143H78.772V92H65.644V13.143h52.513z" /><path fill="#cfcecd" d="M183.797 52.571v13.143h-39.384V52.57z" /><path fill="#656363" d="M183.794 52.572H144.41v13.142h39.384v13.143h-52.512V13.143h52.512zM144.41 39.429h26.256V26.286H144.41z" /><path fill="#cfcecd" d="M236.306 78.857H210.05V39.43h26.256z" /><path fill="#656363" d="M236.31 26.286h-26.256v52.571h-13.13V13.143h39.386zm13.128 52.571H236.31V26.286h13.128z" /><path fill="#cfcecd" d="M315.078 65.715h-39.384V39.429h39.384z" /><path fill="#211e1e" d="M315.075 26.286H275.69v39.428h39.385v13.143h-52.513V13.143h52.513z" /><path fill="#cfcecd" d="M367.588 65.715h-26.257V39.429h26.257z" /><path fill="#211e1e" d="M367.591 26.286h-26.257v39.428h26.257zm13.128 52.571h-52.513V13.143h52.513z" /><path fill="#cfcecd" d="M433.231 65.715h-26.256V39.429h26.256z" /><path fill="#211e1e" d="M433.228 26.286h-26.256v39.428h26.256zm13.129 52.571h-52.513V13.143h39.384V0h13.129z" /><path fill="#cfcecd" d="M511.997 52.571v13.143h-39.384V52.57z" /><path fill="#211e1e" d="M472.616 26.286v13.143h26.256V26.286zM512 52.572h-39.384v13.142H512v13.143h-52.513V13.143H512z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 321" {...props}><path fill="#cfcecd" d="M191.985 256.287H63.983V128.144h128.002z" /><path fill="#ffffff" d="M192.001 64.072H63.999v192.214h128.002zM256 320.357H0V0h256z" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 92" {...props}><path fill="#cfcecd" d="M39.388 65.715H13.13V39.429h26.257z" /><path fill="#656363" d="M39.385 26.286H13.128v39.428h26.257zm13.128 52.571H0V13.143h52.513z" /><path fill="#cfcecd" d="M105.025 65.715H78.769V39.429h26.256z" /><path fill="#656363" d="M78.772 65.714h26.256V26.286H78.772zm39.385 13.143H78.772V92H65.644V13.143h52.513z" /><path fill="#cfcecd" d="M183.797 52.571v13.143h-39.384V52.57z" /><path fill="#656363" d="M183.794 52.572H144.41v13.142h39.384v13.143h-52.512V13.143h52.512zM144.41 39.429h26.256V26.286H144.41z" /><path fill="#cfcecd" d="M236.306 78.857H210.05V39.43h26.256z" /><path fill="#656363" d="M236.31 26.286h-26.256v52.571h-13.13V13.143h39.386zm13.128 52.571H236.31V26.286h13.128z" /><path fill="#cfcecd" d="M315.078 65.715h-39.384V39.429h39.384z" /><path fill="#ffffff" d="M315.075 26.286H275.69v39.428h39.385v13.143h-52.513V13.143h52.513z" /><path fill="#cfcecd" d="M367.588 65.715h-26.257V39.429h26.257z" /><path fill="#ffffff" d="M367.591 26.286h-26.257v39.428h26.257zm13.128 52.571h-52.513V13.143h52.513z" /><path fill="#cfcecd" d="M433.231 65.715h-26.256V39.429h26.256z" /><path fill="#ffffff" d="M433.228 26.286h-26.256v39.428h26.256zm13.129 52.571h-52.513V13.143h39.384V0h13.129z" /><path fill="#cfcecd" d="M511.997 52.571v13.143h-39.384V52.57z" /><path fill="#ffffff" d="M472.616 26.286v13.143h26.256V26.286zM512 52.572h-39.384v13.142H512v13.143h-52.513V13.143H512z" /></svg>;

export function OpencodeLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "OpenCode",
  className,
  ...props
}: OpencodeLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default OpencodeLogo;
