/**
 * Opera logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/opera).
 * Artwork: gilbarbara/logos (CC0-1.0). Opera is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type OperaLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><defs><linearGradient id="opera-a" x1="50.003%" x2="50.003%" y1="1.63%" y2="98.545%"><stop offset="30%" stopColor="#ff1b2d" /><stop offset="43.81%" stopColor="#fa1a2c" /><stop offset="59.39%" stopColor="#ed1528" /><stop offset="75.81%" stopColor="#d60e21" /><stop offset="92.72%" stopColor="#b70519" /><stop offset="100%" stopColor="#a70014" /></linearGradient><linearGradient id="opera-b" x1="49.99%" x2="49.99%" y1=".853%" y2="99.519%"><stop offset="0%" stopColor="#9c0000" /><stop offset="70%" stopColor="#ff4b4b" /></linearGradient></defs><path fill="url(#opera-a)" d="M85.9 200.1C71.7 183.4 62.6 158.7 62 131v-6c.6-27.7 9.8-52.4 23.9-69.1 18.4-23.8 45.4-34.5 75.9-34.5 18.8 0 36.5 1.3 51.5 11.3C190.8 12.4 161.1.1 128.5 0h-.5C57.3 0 0 57.3 0 128c0 68.6 54 124.7 121.9 127.9 2 .1 4.1.1 6.1.1 32.8 0 62.7-12.3 85.3-32.6-15 10-31.7 10.4-50.5 10.4-30.4.1-58.6-9.8-76.9-33.7" /><path fill="url(#opera-b)" d="M85.9 55.9c11.7-13.9 26.9-22.2 43.5-22.2 37.3 0 67.5 42.2 67.5 94.4s-30.2 94.4-67.5 94.4c-16.6 0-31.7-8.4-43.5-22.2 18.4 23.8 45.7 39 76.1 39 18.7 0 36.3-5.7 51.3-15.7C239.5 200 256 165.9 256 128s-16.5-72-42.7-95.4c-15-10-32.5-15.7-51.3-15.7-30.5 0-57.8 15.1-76.1 39" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M8.051 5.238c-1.328 1.566-2.186 3.883-2.246 6.48v.564c.061 2.598.918 4.912 2.246 6.479 1.721 2.236 4.279 3.654 7.139 3.654a8.65 8.65 0 0 0 4.807-1.471 11.93 11.93 0 0 1-8.567 3.042C5.064 23.689 0 18.436 0 12 0 5.371 5.373 0 12 0h.045a11.97 11.97 0 0 1 7.953 3.055c-1.408-.93-3.051-1.471-4.81-1.471-2.858 0-5.417 1.42-7.14 3.654zM24 12c0 3.556-1.545 6.748-4.002 8.945-3.078 1.5-5.946.451-6.896-.205 3.023-.664 5.307-4.32 5.307-8.74 0-4.422-2.283-8.075-5.307-8.74.949-.654 3.818-1.703 6.896-.205A11.96 11.96 0 0 1 24 12" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><defs><linearGradient id="opera-a-dark" x1="50.003%" x2="50.003%" y1="1.63%" y2="98.545%"><stop offset="30%" stopColor="#ff1b2d" /><stop offset="43.81%" stopColor="#fa1a2c" /><stop offset="59.39%" stopColor="#ed1528" /><stop offset="75.81%" stopColor="#d60e21" /><stop offset="92.72%" stopColor="#c6051b" /><stop offset="100%" stopColor="#c60018" /></linearGradient><linearGradient id="opera-b-dark" x1="49.99%" x2="49.99%" y1=".853%" y2="99.519%"><stop offset="0%" stopColor="#ca0000" /><stop offset="70%" stopColor="#ff4b4b" /></linearGradient></defs><path fill="url(#opera-a-dark)" d="M85.9 200.1C71.7 183.4 62.6 158.7 62 131v-6c.6-27.7 9.8-52.4 23.9-69.1 18.4-23.8 45.4-34.5 75.9-34.5 18.8 0 36.5 1.3 51.5 11.3C190.8 12.4 161.1.1 128.5 0h-.5C57.3 0 0 57.3 0 128c0 68.6 54 124.7 121.9 127.9 2 .1 4.1.1 6.1.1 32.8 0 62.7-12.3 85.3-32.6-15 10-31.7 10.4-50.5 10.4-30.4.1-58.6-9.8-76.9-33.7" /><path fill="url(#opera-b-dark)" d="M85.9 55.9c11.7-13.9 26.9-22.2 43.5-22.2 37.3 0 67.5 42.2 67.5 94.4s-30.2 94.4-67.5 94.4c-16.6 0-31.7-8.4-43.5-22.2 18.4 23.8 45.7 39 76.1 39 18.7 0 36.3-5.7 51.3-15.7C239.5 200 256 165.9 256 128s-16.5-72-42.7-95.4c-15-10-32.5-15.7-51.3-15.7-30.5 0-57.8 15.1-76.1 39" /></svg>;

export function OperaLogo({
  variant = "color",
  mode = "auto",
  title = "Opera",
  className,
  ...props
}: OperaLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default OperaLogo;
