/**
 * Orange logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/orange).
 * Artwork: Simple Icons (CC0-1.0). Orange is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type OrangeLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#ff7900" viewBox="0 0 24 24" {...props}><path d="M0 0h24v24H0zm3.43 20.572h17.143v-3.429H3.43z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M0 0h24v24H0zm3.43 20.572h17.143v-3.429H3.43z" /></svg>;

export function OrangeLogo({
  variant = "color",
  title = "Orange",
  className,
  ...props
}: OrangeLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default OrangeLogo;
