/**
 * Ory logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/ory).
 * Artwork: gilbarbara/logos (CC0-1.0). Ory is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type OryLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 511" {...props}><path fill="#4f46e5" d="M128 127.698c-70.704 0-128 57.161-128 127.698s57.296 127.698 128 127.698c70.706 0 128-57.16 128-127.698s-57.294-127.698-128-127.698M0 111.736V63.849L128 0l128 63.85v47.886l-128-63.85zm256 287.32v47.887l-128 63.85-128-63.85v-47.886l128 63.849z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12 6a6 6 0 1 0 0 12 6 6 0 0 0 0-12m-6-.75V3l6-3 6 3v2.25l-6-3zm12 13.5V21l-6 3-6-3v-2.25l6 3z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 186" {...props}><path fill="#4f46e5" d="M419.082 185.13h-39.82l46.722-92.477L379.262 0h39.82l26.638 53.247L473.065 0H512zM342.059 56.862v.882c-.176 26.094-17.827 48.135-41.805 54.745l44.527 72.643h-41.304l-43.185-70.616h-14.755v70.616h-35.132V79.253h28.019l-28.105-45.93V0h74.653c31.354 0 56.824 25.39 57.087 56.861m-89.32-21.598 27.14 44.078h5.18c12.12 0 21.958-9.873 21.958-22.039 0-12.165-9.838-22.04-21.958-22.04zM93.091 0c51.422 0 93.091 41.434 93.091 92.565s-41.669 92.566-93.09 92.566C41.668 185.13 0 143.696 0 92.565S41.67 0 93.091 0m0 35.263c-31.828 0-57.628 25.654-57.628 57.302 0 31.65 25.8 57.301 57.628 57.301s57.627-25.652 57.627-57.3c0-31.65-25.8-57.303-57.627-57.303" /></svg>;

export function OryLogo({
  variant = "color",
  type = "icon",
  title = "Ory",
  className,
  ...props
}: OryLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return <Wordmark {...shared} className={className} />;
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default OryLogo;
