/**
 * Passport logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/passport).
 * Artwork: gilbarbara/logos (CC0-1.0). Passport is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type PassportLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 320" {...props}><path fill="#d6ff00" d="M128 0C57.28 0 0 57.28 0 128h64c0-35.328 28.672-64 64-64z" /><path fill="#34e27a" d="M256 128C256 57.28 198.72 0 128 0v64c35.328 0 64 28.672 64 64z" /><path fill="#00b9f1" d="M128 256c70.72 0 128-57.28 128-128h-64c0 35.328-28.672 64-64 64z" /><path fill="#fff" d="M64 256V128H0v192h128v-64z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.875 0A9.6 9.6 0 0 0 2.4 9.475h4.8A4.81 4.81 0 0 1 11.875 4.8zm.25 0v4.8A4.81 4.81 0 0 1 16.8 9.475h4.8A9.6 9.6 0 0 0 12.125 0M2.4 9.725V24H12v-4.8H7.2V9.724zm9.6 9.474a9.6 9.6 0 0 0 9.6-9.474h-4.8A4.807 4.807 0 0 1 12 14.4z" /></svg>;

export function PassportLogo({
  variant = "color",
  title = "Passport",
  className,
  ...props
}: PassportLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default PassportLogo;
