/**
 * Payload logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/payload).
 * Artwork: gilbarbara/logos (CC0-1.0). Payload is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type PayloadLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 305" {...props}><path d="M116.204 0 256 84.031v159.5l-105.265 60.896v-159.5L10.772 61.008zM105.49 171.121v124.463L0 232.13z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 305" {...props}><path d="M116.204 0 256 84.031v159.5l-105.265 60.896v-159.5L10.772 61.008zM105.49 171.121v124.463L0 232.13z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 305" {...props}><path d="M116.204 0 256 84.031v159.5l-105.265 60.896v-159.5L10.772 61.008zM105.49 171.121v124.463L0 232.13z" /></svg>;

export function PayloadLogo({
  variant = "color",
  mode = "auto",
  title = "Payload",
  className,
  ...props
}: PayloadLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default PayloadLogo;
