/**
 * Payload CMS logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/payload-cms).
 * Artwork: Simple Icons (CC0-1.0). Payload CMS is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type PayloadCmsLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}><path d="M11.9 20.4q.1.1.2 0l5.5-3.2q.1-.05.2 0l2.6 1.5q.2.15 0 .3l-8.3 5h-.2L1.8 18.1q-.2-.1-.2-.3V6.2q0-.2.2-.3l1.3-.8q.15-.1.3 0l9.8 5.7q.2.1.2.3v3.1q0 .3-.2.2L4.9 9.6q-.2-.1-.2.2V16q0 .2.2.3zM22.3 5.9q.1.1.1.2v9.8q0 .2-.2.1l-2.7-1.5q-.2-.1-.2-.3V7.9q0-.2-.2-.3l-7-4q-.1-.05-.2 0L9.5 5q-.1.05-.2 0L6.7 3.4q-.2-.15 0-.3L11.9 0h.2z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.9 20.4q.1.1.2 0l5.5-3.2q.1-.05.2 0l2.6 1.5q.2.15 0 .3l-8.3 5h-.2L1.8 18.1q-.2-.1-.2-.3V6.2q0-.2.2-.3l1.3-.8q.15-.1.3 0l9.8 5.7q.2.1.2.3v3.1q0 .3-.2.2L4.9 9.6q-.2-.1-.2.2V16q0 .2.2.3zM22.3 5.9q.1.1.1.2v9.8q0 .2-.2.1l-2.7-1.5q-.2-.1-.2-.3V7.9q0-.2-.2-.3l-7-4q-.1-.05-.2 0L9.5 5q-.1.05-.2 0L6.7 3.4q-.2-.15 0-.3L11.9 0h.2z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}><path d="M11.9 20.4q.1.1.2 0l5.5-3.2q.1-.05.2 0l2.6 1.5q.2.15 0 .3l-8.3 5h-.2L1.8 18.1q-.2-.1-.2-.3V6.2q0-.2.2-.3l1.3-.8q.15-.1.3 0l9.8 5.7q.2.1.2.3v3.1q0 .3-.2.2L4.9 9.6q-.2-.1-.2.2V16q0 .2.2.3zM22.3 5.9q.1.1.1.2v9.8q0 .2-.2.1l-2.7-1.5q-.2-.1-.2-.3V7.9q0-.2-.2-.3l-7-4q-.1-.05-.2 0L9.5 5q-.1.05-.2 0L6.7 3.4q-.2-.15 0-.3L11.9 0h.2z" /></svg>;

export function PayloadCmsLogo({
  variant = "color",
  mode = "auto",
  title = "Payload CMS",
  className,
  ...props
}: PayloadCmsLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default PayloadCmsLogo;
