/**
 * Product Hunt logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/producthunt).
 * Artwork: gilbarbara/logos (CC0-1.0). Product Hunt is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ProducthuntLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" {...props}><defs><linearGradient id="producthunt-a" x1="50%" x2="50%" y1="0%" y2="100%"><stop offset="0%" stopColor="#da552f" /><stop offset="100%" stopColor="#d04b25" /></linearGradient></defs><g fill="none" fillRule="evenodd"><path fill="url(#producthunt-a)" d="M128 256c70.694 0 128-57.306 128-128S198.694 0 128 0 0 57.306 0 128s57.306 128 128 128" /><path fill="#fff" d="M96 76.8v102.4h19.2v-32h29.056c19.296-.512 34.944-16.16 34.944-35.2 0-19.552-15.648-35.2-34.944-35.2zm48.493 51.2H115.2V96h29.293c8.563 0 15.507 7.168 15.507 16s-6.944 16-15.507 16" /></g></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M13.604 8.4h-3.405V12h3.405a1.8 1.8 0 1 0 0-3.6M12 0C5.372 0 0 5.372 0 12s5.372 12 12 12 12-5.372 12-12S18.628 0 12 0m1.604 14.4h-3.405V18H7.801V6h5.804a4.2 4.2 0 1 1-.001 8.4" /></svg>;

export function ProducthuntLogo({
  variant = "color",
  title = "Product Hunt",
  className,
  ...props
}: ProducthuntLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default ProducthuntLogo;
