/**
 * Qt logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/qt).
 * Artwork: gilbarbara/logos (CC0-1.0). Qt is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type QtLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 192" {...props}><path fill="#41cd52" d="M231.392 0H35.512L0 36.084v155.507h220.485l35.511-36.083V0z" /><path fill="#fff" d="M95.453 33.512c16.665 0 28.357 4.789 34.988 14.453 6.719 9.575 10.034 24.38 10.034 44.418 0 13.209-1.396 23.848-4.1 31.917-2.794 8.157-7.242 14.363-13.525 18.618l13.524 22.253-16.665 7.891-14.396-24.027c-2.094.62-5.323.976-9.86.976-16.84 0-28.618-4.61-35.25-13.832-6.63-9.22-9.946-23.848-9.946-43.709 0-19.948 3.403-34.753 10.121-44.417 6.719-9.665 18.41-14.54 35.075-14.54m84.984 6.385v23.937h22.336v15.338h-22.336v36.262c0 6.737.523 11.17 1.483 13.299.959 2.216 3.49 3.28 7.416 3.28l13.262-.533.785 14.364q-10.732 2.128-16.49 2.128-13.741 0-18.847-6.384c-3.402-4.255-5.147-12.324-5.147-24.204v-38.3h-12.39v-15.25h12.39V39.897zm-84.664 8.426c-10.1 0-17.064 3.427-20.895 10.373-3.743 6.945-5.658 17.95-5.658 33.194 0 15.153 1.828 26.068 5.484 32.562 3.657 6.495 10.709 9.832 21.069 9.832s17.325-3.247 20.981-9.651c3.57-6.405 5.398-17.319 5.398-32.563 0-15.334-1.828-26.429-5.572-33.374s-10.708-10.373-20.807-10.373" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M21.693 3.162H3.33L0 6.49v14.348h20.671L24 17.51V3.162zM12.785 18.4l-1.562.728-1.35-2.217c-.196.057-.499.09-.924.09q-2.37 0-3.305-1.276c-.622-.85-.932-2.2-.932-4.033q.002-2.76.949-4.098.945-1.34 3.288-1.341c1.562 0 2.658.441 3.28 1.333.63.883.94 2.25.94 4.098q-.002 1.828-.384 2.945c-.261.752-.679 1.325-1.268 1.718zm4.736-1.587q-1.287 0-1.766-.59-.482-.588-.483-2.232v-3.534H14.11V9.051h1.162V6.843h1.644V9.05h2.094v1.415h-2.094v3.346c0 .622.05 1.03.14 1.227.09.204.326.303.695.303l1.243-.05.073 1.326q-1.006.195-1.546.196m-8.58-9.08q-1.425-.002-1.963.94c-.352.63-.532 1.629-.532 3.011 0 1.374.172 2.364.515 2.953s1.006.892 1.98.892c.973 0 1.628-.295 1.971-.876.335-.58.507-1.57.507-2.953 0-1.39-.172-2.396-.523-3.026s-1.006-.94-1.955-.94Z" /></svg>;

export function QtLogo({
  variant = "color",
  title = "Qt",
  className,
  ...props
}: QtLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default QtLogo;
