/**
 * Railway logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/railway).
 * Artwork: gilbarbara/logos (CC0-1.0). Railway is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type RailwayLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#100f13" d="M11.254 181.077h233.088C224.132 225.249 179.643 256 127.865 256c-86.63-1.308-116.61-74.923-116.61-74.923M127.864 0C198.633 0 256 57.339 256 128.054a127.6 127.6 0 0 1-6.524 40.164H6.818a141 141 0 0 1-2.645-9.437H181.94c11.358 0 20.737-5.812 25.096-15.554 4.736-10.6 2.732-21.665-4.233-31.29-7.535-10.406-20.174-25.012-28.928-31.63-16.126-12.201-36.622-13.991-53.297-14.547l-4.787-.177c-7.731-.323-9.202-.5-48.78-.5v.014c-.007 0-33.49.02-50.683.056C38.328 26.29 79.988 0 127.864 0M.1 135.424h195.883c-1.466 5.676-5.98 10.25-14.041 10.25H1.094c-.466-3.37-.79-6.787-.994-10.25m66.875-57.49c33.947 0 39.73.141 48.259.492 25.58 1.09 43.462-2.633 76.705 40.315.92 1.17 1.832 2.366 2.51 3.693H0c.182-4.314.58-8.616 1.189-12.89h102.21V96.567H3.758c1.169-5.3 3.57-11.814 6.06-18.535 19.236-.052 38.988-.098 57.158-.098" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M.113 10.27A13 13 0 0 0 0 11.48h18.23a2.3 2.3 0 0 0-.235-.347c-3.117-4.027-4.793-3.677-7.19-3.78-.8-.034-1.34-.048-4.524-.048-1.704 0-3.555.005-5.358.01-.234.63-.459 1.24-.567 1.737h9.342v1.216H.113zm18.26 2.426H.009q.029.488.094.961h16.955c.754 0 1.179-.429 1.315-.96zm-17.318 4.28s2.81 6.902 10.93 7.024c4.855 0 9.027-2.883 10.92-7.024H1.056zM11.988 0C7.5 0 3.593 2.466 1.531 6.108l4.75-.005v-.002c3.71 0 3.849.016 4.573.047l.448.016c1.563.052 3.485.22 4.996 1.364.82.621 2.007 1.99 2.712 2.965.654.902.842 1.94.396 2.934-.408.914-1.289 1.458-2.353 1.458H.391s.099.42.249.886h22.748A12 12 0 0 0 24 12.005C24 5.377 18.621 0 11.988 0" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#ffffff" d="M11.254 181.077h233.088C224.132 225.249 179.643 256 127.865 256c-86.63-1.308-116.61-74.923-116.61-74.923M127.864 0C198.633 0 256 57.339 256 128.054a127.6 127.6 0 0 1-6.524 40.164H6.818a141 141 0 0 1-2.645-9.437H181.94c11.358 0 20.737-5.812 25.096-15.554 4.736-10.6 2.732-21.665-4.233-31.29-7.535-10.406-20.174-25.012-28.928-31.63-16.126-12.201-36.622-13.991-53.297-14.547l-4.787-.177c-7.731-.323-9.202-.5-48.78-.5v.014c-.007 0-33.49.02-50.683.056C38.328 26.29 79.988 0 127.864 0M.1 135.424h195.883c-1.466 5.676-5.98 10.25-14.041 10.25H1.094c-.466-3.37-.79-6.787-.994-10.25m66.875-57.49c33.947 0 39.73.141 48.259.492 25.58 1.09 43.462-2.633 76.705 40.315.92 1.17 1.832 2.366 2.51 3.693H0c.182-4.314.58-8.616 1.189-12.89h102.21V96.567H3.758c1.169-5.3 3.57-11.814 6.06-18.535 19.236-.052 38.988-.098 57.158-.098" /></svg>;

export function RailwayLogo({
  variant = "color",
  mode = "auto",
  title = "Railway",
  className,
  ...props
}: RailwayLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default RailwayLogo;
