/**
 * Refine logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/refine).
 * Artwork: Simple Icons (CC0-1.0). Refine is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type RefineLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#14141f" viewBox="0 0 24 24" {...props}><path d="M13.789.422a4 4 0 0 0-3.578 0l-8 4A4 4 0 0 0 0 8v8c0 1.515.856 2.9 2.211 3.578l8 4a4 4 0 0 0 3.578 0l8-4A4 4 0 0 0 24 16V8c0-1.515-.856-2.9-2.211-3.578zM8 8a4 4 0 0 1 8 0v8a4 4 0 0 1-8 0zm6 0a2 2 0 1 1-3.999.001A2 2 0 0 1 14 8" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M13.789.422a4 4 0 0 0-3.578 0l-8 4A4 4 0 0 0 0 8v8c0 1.515.856 2.9 2.211 3.578l8 4a4 4 0 0 0 3.578 0l8-4A4 4 0 0 0 24 16V8c0-1.515-.856-2.9-2.211-3.578zM8 8a4 4 0 0 1 8 0v8a4 4 0 0 1-8 0zm6 0a2 2 0 1 1-3.999.001A2 2 0 0 1 14 8" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" viewBox="0 0 24 24" {...props}><path d="M13.789.422a4 4 0 0 0-3.578 0l-8 4A4 4 0 0 0 0 8v8c0 1.515.856 2.9 2.211 3.578l8 4a4 4 0 0 0 3.578 0l8-4A4 4 0 0 0 24 16V8c0-1.515-.856-2.9-2.211-3.578zM8 8a4 4 0 0 1 8 0v8a4 4 0 0 1-8 0zm6 0a2 2 0 1 1-3.999.001A2 2 0 0 1 14 8" /></svg>;

export function RefineLogo({
  variant = "color",
  mode = "auto",
  title = "Refine",
  className,
  ...props
}: RefineLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default RefineLogo;
