/**
 * Relay logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/relay).
 * Artwork: Simple Icons (CC0-1.0). Relay is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type RelayLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#f26b00" viewBox="0 0 24 24" {...props}><path d="M2.264 4.937A2.264 2.264 0 1 0 4.456 7.77h10.339a1.792 1.792 0 0 1 0 3.583h-5.73a3.037 3.037 0 0 0-3.034 3.033 3.036 3.036 0 0 0 3.033 3.033h10.494a2.264 2.264 0 1 0 0-1.242H9.064a1.793 1.793 0 0 1-1.791-1.791c0-.988.803-1.792 1.791-1.792h5.73a3.036 3.036 0 0 0 3.034-3.033 3.036 3.036 0 0 0-3.033-3.033H4.427a2.265 2.265 0 0 0-2.163-1.592" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M2.264 4.937A2.264 2.264 0 1 0 4.456 7.77h10.339a1.792 1.792 0 0 1 0 3.583h-5.73a3.037 3.037 0 0 0-3.034 3.033 3.036 3.036 0 0 0 3.033 3.033h10.494a2.264 2.264 0 1 0 0-1.242H9.064a1.793 1.793 0 0 1-1.791-1.791c0-.988.803-1.792 1.791-1.792h5.73a3.036 3.036 0 0 0 3.034-3.033 3.036 3.036 0 0 0-3.033-3.033H4.427a2.265 2.265 0 0 0-2.163-1.592" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 151" {...props}><path fill="#f26b00" d="M208.615 119.908H96.683c-10.537 0-19.11-8.572-19.11-19.107 0-10.539 8.572-19.111 19.11-19.111h61.129c17.84 0 32.353-14.513 32.353-32.353s-14.512-32.354-32.353-32.354H47.223C44.17 7.143 34.995 0 24.152 0 10.811 0 0 10.81 0 24.152c0 13.341 10.812 24.152 24.153 24.152 11.239 0 20.687-7.677 23.381-18.076h110.279c10.535 0 19.107 8.573 19.107 19.11s-8.572 19.109-19.107 19.109h-61.13c-17.839 0-32.353 14.513-32.353 32.354 0 17.84 14.513 32.352 32.354 32.352h111.93c2.878 10.121 12.189 17.53 23.234 17.53 13.341 0 24.152-10.81 24.152-24.151 0-13.342-10.81-24.152-24.152-24.152-11.044 0-20.354 7.408-23.233 17.528" /></svg>;

export function RelayLogo({
  variant = "color",
  type = "icon",
  title = "Relay",
  className,
  ...props
}: RelayLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return <Wordmark {...shared} className={className} />;
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default RelayLogo;
