/**
 * Rider logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/rider).
 * Artwork: gilbarbara/logos (CC0-1.0). Rider is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type RiderLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><defs><linearGradient id="rider-a" x1="90.832%" x2="-19.123%" y1="81.803%" y2="19.04%"><stop offset="0%" stopColor="#dd1265" /><stop offset="48%" stopColor="#dd1265" /><stop offset="94%" stopColor="#fdb60d" /></linearGradient><linearGradient id="rider-b" x1="35.983%" x2="53.7%" y1="7.271%" y2="92.994%"><stop offset="14%" stopColor="#087cfa" /><stop offset="48%" stopColor="#dd1265" /><stop offset="96%" stopColor="#087cfa" /></linearGradient><linearGradient id="rider-c" x1="39.545%" x2="56.938%" y1="11.352%" y2="91.694%"><stop offset="28%" stopColor="#dd1265" /><stop offset="97%" stopColor="#fdb60d" /></linearGradient></defs><path fill="url(#rider-a)" d="M256 99.6 76.533 0l120.16 178.533 24.694-16.186z" /><path fill="url(#rider-b)" d="m184.4 58.987-22.48-54.96-49.733 48.96 20.346 177.653L180.72 256 256 212.027z" /><path fill="url(#rider-c)" d="M76.533 0 0 51.547 28.453 227.36l73.387 28.213 94.853-77.04z" /><path d="M48 48.32h160v160H48z" /><path fill="#fff" d="M67.947 178.08h60v10h-60zM68 68.107h27.467a24 24 0 0 1 17.52 6.106 18.88 18.88 0 0 1 5.188 12.957l-.015.963a18.67 18.67 0 0 1-12.907 18.667l14.72 21.493H104.48L91.6 109.04H81.333v19.253H68zM94.667 97.44c6.238 0 9.91-3.214 10.147-8.005l.013-.662c0-5.68-3.947-8.613-10.4-8.613H81.333v17.28zm34.48-29.333h23.466c18.616 0 31.596 12.59 31.991 29.141l.01.965c0 16.934-13.067 30.08-32 30.08h-23.467zm13.333 11.946v36.267h10.24a17.147 17.147 0 0 0 18.155-17.206l-.022-.927a17.307 17.307 0 0 0-18.133-18.16z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M0 0v24h24V0zm7.031 3.113A4.06 4.06 0 0 1 9.72 4.14a3.23 3.23 0 0 1 .84 2.28A3.16 3.16 0 0 1 8.4 9.54l2.46 3.6H8.28L6.12 9.9H4.38v3.24H2.16V3.12c1.61-.004 3.281.009 4.871-.007m5.509.007h3.96c3.18 0 5.34 2.16 5.34 5.04 0 2.82-2.16 5.04-5.34 5.04h-3.96zm4.069 1.976c-.607.01-1.235.004-1.849.004v6.06h1.74a2.88 2.88 0 0 0 3.06-3 2.897 2.897 0 0 0-2.951-3.064M4.319 5.1v2.88H6.6c1.08 0 1.68-.6 1.68-1.44 0-.96-.66-1.44-1.74-1.44zM2.16 19.5h9V21h-9Z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><defs><linearGradient id="rider-a-dark" x1="90.832%" x2="-19.123%" y1="81.803%" y2="19.04%"><stop offset="0%" stopColor="#dd1265" /><stop offset="48%" stopColor="#dd1265" /><stop offset="94%" stopColor="#fdb60d" /></linearGradient><linearGradient id="rider-b-dark" x1="35.983%" x2="53.7%" y1="7.271%" y2="92.994%"><stop offset="14%" stopColor="#087cfa" /><stop offset="48%" stopColor="#dd1265" /><stop offset="96%" stopColor="#087cfa" /></linearGradient><linearGradient id="rider-c-dark" x1="39.545%" x2="56.938%" y1="11.352%" y2="91.694%"><stop offset="28%" stopColor="#dd1265" /><stop offset="97%" stopColor="#fdb60d" /></linearGradient></defs><path fill="url(#rider-a-dark)" d="M256 99.6 76.533 0l120.16 178.533 24.694-16.186z" /><path fill="url(#rider-b-dark)" d="m184.4 58.987-22.48-54.96-49.733 48.96 20.346 177.653L180.72 256 256 212.027z" /><path fill="url(#rider-c-dark)" d="M76.533 0 0 51.547 28.453 227.36l73.387 28.213 94.853-77.04z" /><path d="M48 48.32h160v160H48z" /><path fill="#0a0a0a" d="M67.947 178.08h60v10h-60zM68 68.107h27.467a24 24 0 0 1 17.52 6.106 18.88 18.88 0 0 1 5.188 12.957l-.015.963a18.67 18.67 0 0 1-12.907 18.667l14.72 21.493H104.48L91.6 109.04H81.333v19.253H68zM94.667 97.44c6.238 0 9.91-3.214 10.147-8.005l.013-.662c0-5.68-3.947-8.613-10.4-8.613H81.333v17.28zm34.48-29.333h23.466c18.616 0 31.596 12.59 31.991 29.141l.01.965c0 16.934-13.067 30.08-32 30.08h-23.467zm13.333 11.946v36.267h10.24a17.147 17.147 0 0 0 18.155-17.206l-.022-.927a17.307 17.307 0 0 0-18.133-18.16z" /></svg>;

export function RiderLogo({
  variant = "color",
  mode = "auto",
  title = "Rider",
  className,
  ...props
}: RiderLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default RiderLogo;
