/**
 * Sinatra logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/sinatra).
 * Artwork: gilbarbara/logos (CC0-1.0). Sinatra is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type SinatraLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 174" {...props}><radialGradient id="sinatra-a" cx={125.97} cy={125.709} r={129.906} gradientTransform="matrix(1 0 0 .3673 0 79.541)" gradientUnits="userSpaceOnUse"><stop offset={0.694} style={{
      stopColor: "#afadae"
    }} /><stop offset={0.968} style={{
      stopColor: "#afadae",
      stopOpacity: 0
    }} /></radialGradient><path d="M5 123c0-27.8 56.2-50.3 125.5-50.3S256 95.2 256 123s-56.2 50.3-125.5 50.3C61.2 173.4 5 150.8 5 123" style={{
    fill: "url(#sinatra-a)"
  }} /><radialGradient id="sinatra-b" cx={178.61} cy={90.852} r={177.391} gradientTransform="matrix(-.9856 .1689 -.09166 -.535 362.983 109.296)" gradientUnits="userSpaceOnUse"><stop offset={0.476} style={{
      stopColor: "#f3efe9"
    }} /><stop offset={0.568} style={{
      stopColor: "#eeeae3"
    }} /><stop offset={0.688} style={{
      stopColor: "#e1dbd2"
    }} /><stop offset={0.824} style={{
      stopColor: "#cdc5b7"
    }} /><stop offset={0.963} style={{
      stopColor: "#b4aa98"
    }} /></radialGradient><path d="M2.9 127.8s-20.6-40 47.4-62.4C82.1 54.9 119.4 48 152.7 46.8c38-1.3 71.7 5.3 86.4 27.7 10.6 16.2 4.2 36-16.3 51.4-12.3 9.2-39.3 18.4-57.3 23.6-18 5.1-53.3 12-82.2 10.4s-64.8-5.8-80.4-32.1" style={{
    fill: "url(#sinatra-b)"
  }} /><path d="M2.9 127.8s-20.6-40 47.4-62.4C82.1 54.9 119.4 48 152.7 46.8c38-1.3 71.7 5.3 86.4 27.7 10.6 16.2 4.2 36-16.3 51.4-12.3 9.2-39.3 18.4-57.3 23.6-18 5.1-53.3 12-82.2 10.4s-64.8-5.8-80.4-32.1m81 30.9c28.2 1.6 62.6-5.2 80.1-10.2s44.2-13.6 56.2-22.6c20-15 28.1-33.7 16.9-50.9-14.2-22-48.7-28.8-85.7-27.5-32.4 1.1-68.8 8.8-99.8 19-66.3 21.9-46.2 60.9-46.2 60.9 15.3 25.6 50.3 29.7 78.5 31.3" style={{
    fill: "#cec7bc"
  }} /><linearGradient id="sinatra-c" x1={53.662} x2={197.066} y1={47.58} y2={58.425} gradientUnits="userSpaceOnUse"><stop offset={0.094} style={{
      stopColor: "#d7d0c6"
    }} /><stop offset={0.248} style={{
      stopColor: "#cdc7bb"
    }} /><stop offset={0.401} style={{
      stopColor: "#c7c2b5"
    }} /><stop offset={0.525} style={{
      stopColor: "#cbc6ba"
    }} /><stop offset={0.669} style={{
      stopColor: "#d7d1c7"
    }} /><stop offset={0.78} style={{
      stopColor: "#e6dfd6"
    }} /><stop offset={0.892} style={{
      stopColor: "#e7e3d9"
    }} /><stop offset={0.934} style={{
      stopColor: "#e5dfd3"
    }} /><stop offset={0.98} style={{
      stopColor: "#dfd5c6"
    }} /></linearGradient><path d="M57.3 95.9c-5.9-4.3-14.2-25.4-11-30s8-14.2 10.7-23.6c2.7-9.3 6.5-29.1 14-36.1s18.7-7 33.5-5.4c14.7 1.6 57.8 9.4 68.3 13.1 10.4 3.7 24 10.7 23.2 27s.7 24.4-1.2 33.5-21.7 26.8-46.6 28.1c-25 1.5-85-2.3-90.9-6.6" style={{
    fill: "url(#sinatra-c)"
  }} /><radialGradient id="sinatra-d" cx={110.123} cy={23.771} r={53.767} gradientTransform="rotate(84.941 132.128 43.915)scale(1 2.6947)" gradientUnits="userSpaceOnUse"><stop offset={0.067} style={{
      stopColor: "#b2a797"
    }} /><stop offset={0.29} style={{
      stopColor: "#c7bdae"
    }} /><stop offset={0.481} style={{
      stopColor: "#d6cebf"
    }} /><stop offset={0.688} style={{
      stopColor: "#e2dcd0"
    }} /><stop offset={0.942} style={{
      stopColor: "#f7f5ee"
    }} /></radialGradient><path d="M127.8 75.8s25.7-3.4 41.2-17.9 1.8-24.9-2.4-27.5S148.3 21 126 22s-44.3 1.2-42.8 17.7c1.5 16.4 19.5 36.1 44.6 36.1" style={{
    fill: "url(#sinatra-d)"
  }} /><linearGradient id="sinatra-e" x1={69.277} x2={177.061} y1={15.553} y2={15.553} gradientUnits="userSpaceOnUse"><stop offset={0.056} style={{
      stopColor: "#f7f5ee"
    }} /><stop offset={0.226} style={{
      stopColor: "#e6e1d6"
    }} /><stop offset={0.43} style={{
      stopColor: "#d8d1c3"
    }} /><stop offset={0.639} style={{
      stopColor: "#d0c8b9"
    }} /><stop offset={0.857} style={{
      stopColor: "#cec5b5"
    }} /></linearGradient><path d="M71 26.2c-2.8-1.8-3.2-11.6 7.2-18.3 10.4-6.6 37.2-2.6 54.6 1.6 17.5 4.2 45.7 10.1 44.2 11.7-1.5 1.5-43.5-3.6-62.7-2.6C88.2 20 75.4 29 71 26.2" style={{
    fill: "url(#sinatra-e)"
  }} /><linearGradient id="sinatra-f" x1={42.47} x2={196.375} y1={94.53} y2={94.53} gradientUnits="userSpaceOnUse"><stop offset={0.018} style={{
      stopColor: "#262222"
    }} /><stop offset={0.096} style={{
      stopColor: "#2f2c2c"
    }} /><stop offset={0.3} style={{
      stopColor: "#424143"
    }} /><stop offset={0.402} style={{
      stopColor: "#4a4a4c"
    }} /><stop offset={0.514} style={{
      stopColor: "#4a4a4c"
    }} /><stop offset={0.78} style={{
      stopColor: "#383536"
    }} /><stop offset={1} style={{
      stopColor: "#262222"
    }} /></linearGradient><path d="M195.6 71.7c-.3 0-.4.9-.8 1.4-3.3 5.4-13.1 14.6-35.4 14.6H98.8c-38.2 0-49.3-10.3-52.1-17.7-.2-.7-.5-1.6-.8-1.6s-.5 1.6-.5 1.6l-2.9 27.7c0 12.7 32.9 23 75.2 23s78.6-6 78.6-23c0 0 .2-16.9.1-24.4 0-.8-.1-1.6-.8-1.6" style={{
    fill: "url(#sinatra-f)"
  }} /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 174" {...props}><radialGradient id="sinatra-a-mono" cx={125.97} cy={125.709} r={129.906} gradientTransform="matrix(1 0 0 .3673 0 79.541)" gradientUnits="userSpaceOnUse"><stop offset={0.694} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.968} style={{
      stopColor: "currentColor",
      stopOpacity: 0
    }} /></radialGradient><path d="M5 123c0-27.8 56.2-50.3 125.5-50.3S256 95.2 256 123s-56.2 50.3-125.5 50.3C61.2 173.4 5 150.8 5 123" style={{
    fill: "url(#sinatra-a-mono)"
  }} /><radialGradient id="sinatra-b-mono" cx={178.61} cy={90.852} r={177.391} gradientTransform="matrix(-.9856 .1689 -.09166 -.535 362.983 109.296)" gradientUnits="userSpaceOnUse"><stop offset={0.476} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.568} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.688} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.824} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.963} style={{
      stopColor: "currentColor"
    }} /></radialGradient><path d="M2.9 127.8s-20.6-40 47.4-62.4C82.1 54.9 119.4 48 152.7 46.8c38-1.3 71.7 5.3 86.4 27.7 10.6 16.2 4.2 36-16.3 51.4-12.3 9.2-39.3 18.4-57.3 23.6-18 5.1-53.3 12-82.2 10.4s-64.8-5.8-80.4-32.1" style={{
    fill: "url(#sinatra-b-mono)"
  }} /><path d="M2.9 127.8s-20.6-40 47.4-62.4C82.1 54.9 119.4 48 152.7 46.8c38-1.3 71.7 5.3 86.4 27.7 10.6 16.2 4.2 36-16.3 51.4-12.3 9.2-39.3 18.4-57.3 23.6-18 5.1-53.3 12-82.2 10.4s-64.8-5.8-80.4-32.1m81 30.9c28.2 1.6 62.6-5.2 80.1-10.2s44.2-13.6 56.2-22.6c20-15 28.1-33.7 16.9-50.9-14.2-22-48.7-28.8-85.7-27.5-32.4 1.1-68.8 8.8-99.8 19-66.3 21.9-46.2 60.9-46.2 60.9 15.3 25.6 50.3 29.7 78.5 31.3" style={{
    fill: "currentColor"
  }} /><linearGradient id="sinatra-c-mono" x1={53.662} x2={197.066} y1={47.58} y2={58.425} gradientUnits="userSpaceOnUse"><stop offset={0.094} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.248} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.401} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.525} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.669} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.78} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.892} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.934} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.98} style={{
      stopColor: "currentColor"
    }} /></linearGradient><path d="M57.3 95.9c-5.9-4.3-14.2-25.4-11-30s8-14.2 10.7-23.6c2.7-9.3 6.5-29.1 14-36.1s18.7-7 33.5-5.4c14.7 1.6 57.8 9.4 68.3 13.1 10.4 3.7 24 10.7 23.2 27s.7 24.4-1.2 33.5-21.7 26.8-46.6 28.1c-25 1.5-85-2.3-90.9-6.6" style={{
    fill: "url(#sinatra-c-mono)"
  }} /><radialGradient id="sinatra-d-mono" cx={110.123} cy={23.771} r={53.767} gradientTransform="rotate(84.941 132.128 43.915)scale(1 2.6947)" gradientUnits="userSpaceOnUse"><stop offset={0.067} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.29} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.481} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.688} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.942} style={{
      stopColor: "currentColor"
    }} /></radialGradient><path d="M127.8 75.8s25.7-3.4 41.2-17.9 1.8-24.9-2.4-27.5S148.3 21 126 22s-44.3 1.2-42.8 17.7c1.5 16.4 19.5 36.1 44.6 36.1" style={{
    fill: "url(#sinatra-d-mono)"
  }} /><linearGradient id="sinatra-e-mono" x1={69.277} x2={177.061} y1={15.553} y2={15.553} gradientUnits="userSpaceOnUse"><stop offset={0.056} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.226} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.43} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.639} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.857} style={{
      stopColor: "currentColor"
    }} /></linearGradient><path d="M71 26.2c-2.8-1.8-3.2-11.6 7.2-18.3 10.4-6.6 37.2-2.6 54.6 1.6 17.5 4.2 45.7 10.1 44.2 11.7-1.5 1.5-43.5-3.6-62.7-2.6C88.2 20 75.4 29 71 26.2" style={{
    fill: "url(#sinatra-e-mono)"
  }} /><linearGradient id="sinatra-f-mono" x1={42.47} x2={196.375} y1={94.53} y2={94.53} gradientUnits="userSpaceOnUse"><stop offset={0.018} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.096} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.3} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.402} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.514} style={{
      stopColor: "currentColor"
    }} /><stop offset={0.78} style={{
      stopColor: "currentColor"
    }} /><stop offset={1} style={{
      stopColor: "currentColor"
    }} /></linearGradient><path d="M195.6 71.7c-.3 0-.4.9-.8 1.4-3.3 5.4-13.1 14.6-35.4 14.6H98.8c-38.2 0-49.3-10.3-52.1-17.7-.2-.7-.5-1.6-.8-1.6s-.5 1.6-.5 1.6l-2.9 27.7c0 12.7 32.9 23 75.2 23s78.6-6 78.6-23c0 0 .2-16.9.1-24.4 0-.8-.1-1.6-.8-1.6" style={{
    fill: "url(#sinatra-f-mono)"
  }} /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 174" {...props}><radialGradient id="sinatra-a-dark" cx={125.97} cy={125.709} r={129.906} gradientTransform="matrix(1 0 0 .3673 0 79.541)" gradientUnits="userSpaceOnUse"><stop offset={0.694} style={{
      stopColor: "#afadae"
    }} /><stop offset={0.968} style={{
      stopColor: "#afadae",
      stopOpacity: 0
    }} /></radialGradient><path d="M5 123c0-27.8 56.2-50.3 125.5-50.3S256 95.2 256 123s-56.2 50.3-125.5 50.3C61.2 173.4 5 150.8 5 123" style={{
    fill: "url(#sinatra-a-dark)"
  }} /><radialGradient id="sinatra-b-dark" cx={178.61} cy={90.852} r={177.391} gradientTransform="matrix(-.9856 .1689 -.09166 -.535 362.983 109.296)" gradientUnits="userSpaceOnUse"><stop offset={0.476} style={{
      stopColor: "#0a0a0a"
    }} /><stop offset={0.568} style={{
      stopColor: "#0a0a0a"
    }} /><stop offset={0.688} style={{
      stopColor: "#e1dbd2"
    }} /><stop offset={0.824} style={{
      stopColor: "#cdc5b7"
    }} /><stop offset={0.963} style={{
      stopColor: "#b4aa98"
    }} /></radialGradient><path d="M2.9 127.8s-20.6-40 47.4-62.4C82.1 54.9 119.4 48 152.7 46.8c38-1.3 71.7 5.3 86.4 27.7 10.6 16.2 4.2 36-16.3 51.4-12.3 9.2-39.3 18.4-57.3 23.6-18 5.1-53.3 12-82.2 10.4s-64.8-5.8-80.4-32.1" style={{
    fill: "url(#sinatra-b-dark)"
  }} /><path d="M2.9 127.8s-20.6-40 47.4-62.4C82.1 54.9 119.4 48 152.7 46.8c38-1.3 71.7 5.3 86.4 27.7 10.6 16.2 4.2 36-16.3 51.4-12.3 9.2-39.3 18.4-57.3 23.6-18 5.1-53.3 12-82.2 10.4s-64.8-5.8-80.4-32.1m81 30.9c28.2 1.6 62.6-5.2 80.1-10.2s44.2-13.6 56.2-22.6c20-15 28.1-33.7 16.9-50.9-14.2-22-48.7-28.8-85.7-27.5-32.4 1.1-68.8 8.8-99.8 19-66.3 21.9-46.2 60.9-46.2 60.9 15.3 25.6 50.3 29.7 78.5 31.3" style={{
    fill: "#cec7bc"
  }} /><linearGradient id="sinatra-c-dark" x1={53.662} x2={197.066} y1={47.58} y2={58.425} gradientUnits="userSpaceOnUse"><stop offset={0.094} style={{
      stopColor: "#d7d0c6"
    }} /><stop offset={0.248} style={{
      stopColor: "#cdc7bb"
    }} /><stop offset={0.401} style={{
      stopColor: "#c7c2b5"
    }} /><stop offset={0.525} style={{
      stopColor: "#cbc6ba"
    }} /><stop offset={0.669} style={{
      stopColor: "#d7d1c7"
    }} /><stop offset={0.78} style={{
      stopColor: "#e6dfd6"
    }} /><stop offset={0.892} style={{
      stopColor: "#e7e3d9"
    }} /><stop offset={0.934} style={{
      stopColor: "#e5dfd3"
    }} /><stop offset={0.98} style={{
      stopColor: "#dfd5c6"
    }} /></linearGradient><path d="M57.3 95.9c-5.9-4.3-14.2-25.4-11-30s8-14.2 10.7-23.6c2.7-9.3 6.5-29.1 14-36.1s18.7-7 33.5-5.4c14.7 1.6 57.8 9.4 68.3 13.1 10.4 3.7 24 10.7 23.2 27s.7 24.4-1.2 33.5-21.7 26.8-46.6 28.1c-25 1.5-85-2.3-90.9-6.6" style={{
    fill: "url(#sinatra-c-dark)"
  }} /><radialGradient id="sinatra-d-dark" cx={110.123} cy={23.771} r={53.767} gradientTransform="rotate(84.941 132.128 43.915)scale(1 2.6947)" gradientUnits="userSpaceOnUse"><stop offset={0.067} style={{
      stopColor: "#b2a797"
    }} /><stop offset={0.29} style={{
      stopColor: "#c7bdae"
    }} /><stop offset={0.481} style={{
      stopColor: "#d6cebf"
    }} /><stop offset={0.688} style={{
      stopColor: "#e2dcd0"
    }} /><stop offset={0.942} style={{
      stopColor: "#0a0a0a"
    }} /></radialGradient><path d="M127.8 75.8s25.7-3.4 41.2-17.9 1.8-24.9-2.4-27.5S148.3 21 126 22s-44.3 1.2-42.8 17.7c1.5 16.4 19.5 36.1 44.6 36.1" style={{
    fill: "url(#sinatra-d-dark)"
  }} /><linearGradient id="sinatra-e-dark" x1={69.277} x2={177.061} y1={15.553} y2={15.553} gradientUnits="userSpaceOnUse"><stop offset={0.056} style={{
      stopColor: "#0a0a0a"
    }} /><stop offset={0.226} style={{
      stopColor: "#e6e1d6"
    }} /><stop offset={0.43} style={{
      stopColor: "#d8d1c3"
    }} /><stop offset={0.639} style={{
      stopColor: "#d0c8b9"
    }} /><stop offset={0.857} style={{
      stopColor: "#cec5b5"
    }} /></linearGradient><path d="M71 26.2c-2.8-1.8-3.2-11.6 7.2-18.3 10.4-6.6 37.2-2.6 54.6 1.6 17.5 4.2 45.7 10.1 44.2 11.7-1.5 1.5-43.5-3.6-62.7-2.6C88.2 20 75.4 29 71 26.2" style={{
    fill: "url(#sinatra-e-dark)"
  }} /><linearGradient id="sinatra-f-dark" x1={42.47} x2={196.375} y1={94.53} y2={94.53} gradientUnits="userSpaceOnUse"><stop offset={0.018} style={{
      stopColor: "#ffffff"
    }} /><stop offset={0.096} style={{
      stopColor: "#ffffff"
    }} /><stop offset={0.3} style={{
      stopColor: "#ffffff"
    }} /><stop offset={0.402} style={{
      stopColor: "#ffffff"
    }} /><stop offset={0.514} style={{
      stopColor: "#ffffff"
    }} /><stop offset={0.78} style={{
      stopColor: "#ffffff"
    }} /><stop offset={1} style={{
      stopColor: "#ffffff"
    }} /></linearGradient><path d="M195.6 71.7c-.3 0-.4.9-.8 1.4-3.3 5.4-13.1 14.6-35.4 14.6H98.8c-38.2 0-49.3-10.3-52.1-17.7-.2-.7-.5-1.6-.8-1.6s-.5 1.6-.5 1.6l-2.9 27.7c0 12.7 32.9 23 75.2 23s78.6-6 78.6-23c0 0 .2-16.9.1-24.4 0-.8-.1-1.6-.8-1.6" style={{
    fill: "url(#sinatra-f-dark)"
  }} /></svg>;

export function SinatraLogo({
  variant = "color",
  mode = "auto",
  title = "Sinatra",
  className,
  ...props
}: SinatraLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default SinatraLogo;
