/**
 * Snowpack logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/snowpack).
 * Artwork: gilbarbara/logos (CC0-1.0). Snowpack is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type SnowpackLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 205" {...props}><path d="M253.964 185.078 138.764 5.88A12.8 12.8 0 0 0 127.998 0a12.8 12.8 0 0 0-10.768 5.88L2.03 185.078a12.8 12.8 0 0 0-.468 13.056 12.8 12.8 0 0 0 11.236 6.664h230.398c4.684 0 8.992-2.556 11.236-6.668a12.79 12.79 0 0 0-.468-13.052M127.997 36.472l34.156 53.127h-34.156l-25.6 25.6-15.224-15.224z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m23.81 19.751-10.8-16.8a1.2 1.2 0 0 0-2.02 0l-10.8 16.8a1.2 1.2 0 0 0-.043 1.224A1.2 1.2 0 0 0 1.2 21.6h21.6a1.2 1.2 0 0 0 1.053-.625 1.2 1.2 0 0 0-.044-1.224M12 5.82l3.202 4.981H12l-2.4 2.4-1.427-1.427z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 205" {...props}><path d="M253.964 185.078 138.764 5.88A12.8 12.8 0 0 0 127.998 0a12.8 12.8 0 0 0-10.768 5.88L2.03 185.078a12.8 12.8 0 0 0-.468 13.056 12.8 12.8 0 0 0 11.236 6.664h230.398c4.684 0 8.992-2.556 11.236-6.668a12.79 12.79 0 0 0-.468-13.052M127.997 36.472l34.156 53.127h-34.156l-25.6 25.6-15.224-15.224z" /></svg>;

export function SnowpackLogo({
  variant = "color",
  mode = "auto",
  title = "Snowpack",
  className,
  ...props
}: SnowpackLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default SnowpackLogo;
