/**
 * Solana logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/solana).
 * Artwork: Simple Icons (CC0-1.0). Solana is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type SolanaLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#9945ff" viewBox="0 0 24 24" {...props}><path d="m23.876 18.031-3.962 4.14a.9.9 0 0 1-.306.21.9.9 0 0 1-.367.074H.46a.47.47 0 0 1-.252-.073.45.45 0 0 1-.17-.196.44.44 0 0 1-.031-.255.44.44 0 0 1 .117-.23l3.965-4.139a.9.9 0 0 1 .305-.21.9.9 0 0 1 .366-.075h18.78a.47.47 0 0 1 .252.074.45.45 0 0 1 .17.196.44.44 0 0 1 .031.255.44.44 0 0 1-.117.23m-3.962-8.335a.9.9 0 0 0-.306-.21.9.9 0 0 0-.367-.075H.46a.47.47 0 0 0-.252.073.45.45 0 0 0-.17.197.44.44 0 0 0-.031.254.44.44 0 0 0 .117.23l3.965 4.14a.9.9 0 0 0 .305.21.9.9 0 0 0 .366.074h18.78a.47.47 0 0 0 .252-.073.45.45 0 0 0 .17-.196.44.44 0 0 0 .031-.255.44.44 0 0 0-.117-.23zM.46 6.723h18.782a.9.9 0 0 0 .367-.075.9.9 0 0 0 .306-.21l3.962-4.14a.44.44 0 0 0 .117-.23.44.44 0 0 0-.032-.254.45.45 0 0 0-.17-.196.47.47 0 0 0-.252-.073H4.76a.9.9 0 0 0-.366.074.9.9 0 0 0-.305.21L.125 5.97a.44.44 0 0 0-.117.23.44.44 0 0 0 .03.254.45.45 0 0 0 .17.196.47.47 0 0 0 .252.074z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m23.876 18.031-3.962 4.14a.9.9 0 0 1-.306.21.9.9 0 0 1-.367.074H.46a.47.47 0 0 1-.252-.073.45.45 0 0 1-.17-.196.44.44 0 0 1-.031-.255.44.44 0 0 1 .117-.23l3.965-4.139a.9.9 0 0 1 .305-.21.9.9 0 0 1 .366-.075h18.78a.47.47 0 0 1 .252.074.45.45 0 0 1 .17.196.44.44 0 0 1 .031.255.44.44 0 0 1-.117.23m-3.962-8.335a.9.9 0 0 0-.306-.21.9.9 0 0 0-.367-.075H.46a.47.47 0 0 0-.252.073.45.45 0 0 0-.17.197.44.44 0 0 0-.031.254.44.44 0 0 0 .117.23l3.965 4.14a.9.9 0 0 0 .305.21.9.9 0 0 0 .366.074h18.78a.47.47 0 0 0 .252-.073.45.45 0 0 0 .17-.196.44.44 0 0 0 .031-.255.44.44 0 0 0-.117-.23zM.46 6.723h18.782a.9.9 0 0 0 .367-.075.9.9 0 0 0 .306-.21l3.962-4.14a.44.44 0 0 0 .117-.23.44.44 0 0 0-.032-.254.45.45 0 0 0-.17-.196.47.47 0 0 0-.252-.073H4.76a.9.9 0 0 0-.366.074.9.9 0 0 0-.305.21L.125 5.97a.44.44 0 0 0-.117.23.44.44 0 0 0 .03.254.45.45 0 0 0 .17.196.47.47 0 0 0 .252.074z" /></svg>;

export function SolanaLogo({
  variant = "color",
  title = "Solana",
  className,
  ...props
}: SolanaLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default SolanaLogo;
