/**
 * Solidity logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/solidity).
 * Artwork: gilbarbara/logos (CC0-1.0). Solidity is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type SolidityLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 398" {...props}><path d="m191.513 0-63.867 113.512H0L63.823 0z" opacity={0.45} /><path d="M127.646 113.512h127.69L191.514 0H63.823z" opacity={0.6} /><path d="m63.823 226.981 63.823-113.469L63.823 0 0 113.512z" opacity={0.8} /><path d="m64.442 397.25 63.867-113.513H256L192.132 397.25z" opacity={0.45} /><path d="M128.309 283.737H.619L64.44 397.25h127.69z" opacity={0.6} /><path d="M192.132 170.269 128.31 283.737l63.823 113.513L256 283.737z" opacity={0.8} /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 398" {...props}><path d="m191.513 0-63.867 113.512H0L63.823 0z" opacity={0.45} /><path d="M127.646 113.512h127.69L191.514 0H63.823z" opacity={0.6} /><path d="m63.823 226.981 63.823-113.469L63.823 0 0 113.512z" opacity={0.8} /><path d="m64.442 397.25 63.867-113.513H256L192.132 397.25z" opacity={0.45} /><path d="M128.309 283.737H.619L64.44 397.25h127.69z" opacity={0.6} /><path d="M192.132 170.269 128.31 283.737l63.823 113.513L256 283.737z" opacity={0.8} /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 398" {...props}><path d="m191.513 0-63.867 113.512H0L63.823 0z" opacity={0.45} /><path d="M127.646 113.512h127.69L191.514 0H63.823z" opacity={0.6} /><path d="m63.823 226.981 63.823-113.469L63.823 0 0 113.512z" opacity={0.8} /><path d="m64.442 397.25 63.867-113.513H256L192.132 397.25z" opacity={0.45} /><path d="M128.309 283.737H.619L64.44 397.25h127.69z" opacity={0.6} /><path d="M192.132 170.269 128.31 283.737l63.823 113.513L256 283.737z" opacity={0.8} /></svg>;

export function SolidityLogo({
  variant = "color",
  mode = "auto",
  title = "Solidity",
  className,
  ...props
}: SolidityLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default SolidityLogo;
