/**
 * Sourcetree logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/sourcetree).
 * Artwork: gilbarbara/logos (CC0-1.0). Sourcetree is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type SourcetreeLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 322" {...props}><defs><linearGradient id="sourcetree-a" x1="49.928%" x2="49.928%" y1="90.721%" y2="36.288%"><stop offset="18%" stopColor="#0052cc" /><stop offset="100%" stopColor="#2684ff" /></linearGradient></defs><path fill="#2684ff" d="M255.462 127.52C255.462 57.094 198.369 0 127.942 0 65.17-.089 11.677 45.531 1.855 107.528s26.949 121.917 86.672 141.236v63.895a8.97 8.97 0 0 0 8.968 8.968h60.532a8.97 8.97 0 0 0 8.968-8.968v-63.85c52.674-16.961 88.406-65.95 88.466-121.288m-127.52 43.09c-23.811 0-43.113-19.301-43.113-43.112 0-23.81 19.302-43.112 43.112-43.112s43.112 19.302 43.112 43.112-19.302 43.113-43.112 43.113" /><path fill="url(#sourcetree-a)" d="M127.941 0v84.43c23.81 0 43.112 19.302 43.112 43.112s-19.302 43.112-43.112 43.112a39.413 39.413 0 0 1 39.413 39.414v38.785c59.746-19.322 96.533-79.262 86.71-141.281C244.243 45.553 190.735-.085 127.942 0" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.999 0C6.756 0 2.474 4.245 2.474 9.525c0 4.21 2.769 7.792 6.572 9.047v4.764c0 .37.295.664.664.664h4.506a.66.66 0 0 0 .664-.664v-4.764l.074-.027v.064c3.694-1.22 6.412-4.634 6.565-8.687q.007-.187.007-.375v-.022q-.001-.228-.013-.455C21.275 4.037 17.125 0 11.999 0m0 6.352a3.214 3.214 0 0 1 2.664 5.005v.002A3.22 3.22 0 0 1 12 12.775a3.212 3.212 0 0 1 0-6.424z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 322" {...props}><defs><linearGradient id="sourcetree-a-dark" x1="49.928%" x2="49.928%" y1="90.721%" y2="36.288%"><stop offset="18%" stopColor="#0058db" /><stop offset="100%" stopColor="#2684ff" /></linearGradient></defs><path fill="#2684ff" d="M255.462 127.52C255.462 57.094 198.369 0 127.942 0 65.17-.089 11.677 45.531 1.855 107.528s26.949 121.917 86.672 141.236v63.895a8.97 8.97 0 0 0 8.968 8.968h60.532a8.97 8.97 0 0 0 8.968-8.968v-63.85c52.674-16.961 88.406-65.95 88.466-121.288m-127.52 43.09c-23.811 0-43.113-19.301-43.113-43.112 0-23.81 19.302-43.112 43.112-43.112s43.112 19.302 43.112 43.112-19.302 43.113-43.112 43.113" /><path fill="url(#sourcetree-a-dark)" d="M127.941 0v84.43c23.81 0 43.112 19.302 43.112 43.112s-19.302 43.112-43.112 43.112a39.413 39.413 0 0 1 39.413 39.414v38.785c59.746-19.322 96.533-79.262 86.71-141.281C244.243 45.553 190.735-.085 127.942 0" /></svg>;

export function SourcetreeLogo({
  variant = "color",
  mode = "auto",
  title = "Sourcetree",
  className,
  ...props
}: SourcetreeLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default SourcetreeLogo;
