/**
 * Steam Deck logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/steam-deck).
 * Artwork: Simple Icons (CC0-1.0). Steam Deck is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type SteamDeckLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#1a9fff" viewBox="0 0 24 24" {...props}><path d="M8.999 0v4.309c4.242 0 7.694 3.45 7.694 7.691s-3.452 7.691-7.694 7.691V24c6.617 0 12-5.383 12-12s-5.383-12-12-12m0 6.011c-3.313 0-6 2.687-5.998 6a5.999 5.999 0 1 0 5.998-6" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M8.999 0v4.309c4.242 0 7.694 3.45 7.694 7.691s-3.452 7.691-7.694 7.691V24c6.617 0 12-5.383 12-12s-5.383-12-12-12m0 6.011c-3.313 0-6 2.687-5.998 6a5.999 5.999 0 1 0 5.998-6" /></svg>;

export function SteamDeckLogo({
  variant = "color",
  title = "Steam Deck",
  className,
  ...props
}: SteamDeckLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default SteamDeckLogo;
