/**
 * TensorFlow logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/tensorflow).
 * Artwork: gilbarbara/logos (CC0-1.0). TensorFlow is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type TensorflowLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 274" {...props}><path fill="#e55b2d" d="M145.726 42.065v42.07l72.861 42.07v-42.07zM0 84.135v42.07l36.43 21.03V105.17zm109.291 21.035-36.43 21.034v126.2l36.43 21.035v-84.135l36.435 21.035v-42.07l-36.435-21.034z" /><path fill="#ed8e24" d="M145.726 42.065 36.43 105.17v42.065l72.861-42.065v42.065l36.435-21.03zM255.022 63.1l-36.435 21.035v42.07l36.435-21.035zm-72.865 84.135-36.43 21.035v42.07l36.43-21.036zm-36.43 63.104-36.436-21.035v84.135l36.435-21.035z" /><path fill="#f8bf3c" d="M145.726 0 0 84.135l36.43 21.035 109.296-63.105 72.861 42.07L255.022 63.1zm0 126.204-36.435 21.03 36.435 21.036 36.43-21.035z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M1.292 5.856 11.54 0v24l-4.095-2.378V7.603l-6.168 3.564.015-5.31zm21.43 5.311-.014-5.31L12.46 0v24l4.095-2.378V14.87l3.092 1.788-.018-4.618-3.074-1.756V7.603z" /></svg>;

export function TensorflowLogo({
  variant = "color",
  title = "TensorFlow",
  className,
  ...props
}: TensorflowLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default TensorflowLogo;
