/**
 * TIDAL logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/tidal).
 * Artwork: gilbarbara/logos (CC0-1.0). TIDAL is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type TidalLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 171" {...props}><path fill="#0a0b09" d="m128.004 85.339 42.664 42.67-42.664 42.667-42.669-42.667zM42.667.002 85.335 42.67 42.667 85.34 0 42.67zm170.666 0L256 42.67l-42.667 42.67-42.666-42.67-42.663 42.669-42.669-42.67L128.004 0l42.663 42.665z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M12.012 3.992 8.008 7.996 4.004 3.992 0 7.996 4.004 12l4.004-4.004L12.012 12l-4.004 4.004 4.004 4.004 4.004-4.004L12.012 12l4.004-4.004zm4.03 4.004 3.979-3.979L24 7.996l-3.979 3.979z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 68" {...props}><path d="M203.294 8.504v11.264h-16.997v46.616h-13.142V19.768h-16.997V8.504zm52.548.001v57.88h-13.22V8.504zm233.294 0v46.457H512v11.422h-36.084V8.504zm-72.29 0 23.843 57.88h-14.53l-4.23-11.421h-24.404l-4.266 11.42H379.12l24.078-57.88zm-95.579 0c15.802 0 31.525 8.366 31.525 28.782 0 19.243-15.411 29.096-30.742 29.096h-22.2V8.505zm-.078 11.263h-8.51v35.273h8.198c11.028 0 18.382-6.882 18.382-17.833 0-10.403-7.431-17.44-18.07-17.44m88.598 2.276-8.718 22.637h17.356zM50.825 33.88l16.942 16.942-16.942 16.943-16.942-16.943zM16.941 0l16.942 16.94-16.942 16.94L0 16.94zm67.767 0 16.94 16.939-16.94 16.942L67.765 16.94l-16.94 16.94-16.942-16.943L50.825 0l16.942 16.937z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 171" {...props}><path fill="#ffffff" d="m128.004 85.339 42.664 42.67-42.664 42.667-42.669-42.667zM42.667.002 85.335 42.67 42.667 85.34 0 42.67zm170.666 0L256 42.67l-42.667 42.67-42.666-42.67-42.663 42.669-42.669-42.67L128.004 0l42.663 42.665z" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 68" {...props}><path d="M203.294 8.504v11.264h-16.997v46.616h-13.142V19.768h-16.997V8.504zm52.548.001v57.88h-13.22V8.504zm233.294 0v46.457H512v11.422h-36.084V8.504zm-72.29 0 23.843 57.88h-14.53l-4.23-11.421h-24.404l-4.266 11.42H379.12l24.078-57.88zm-95.579 0c15.802 0 31.525 8.366 31.525 28.782 0 19.243-15.411 29.096-30.742 29.096h-22.2V8.505zm-.078 11.263h-8.51v35.273h8.198c11.028 0 18.382-6.882 18.382-17.833 0-10.403-7.431-17.44-18.07-17.44m88.598 2.276-8.718 22.637h17.356zM50.825 33.88l16.942 16.942-16.942 16.943-16.942-16.943zM16.941 0l16.942 16.94-16.942 16.94L0 16.94zm67.767 0 16.94 16.939-16.94 16.942L67.765 16.94l-16.94 16.94-16.942-16.943L50.825 0l16.942 16.937z" /></svg>;

export function TidalLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "TIDAL",
  className,
  ...props
}: TidalLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default TidalLogo;
