/**
 * Uptime Kuma logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/uptime-kuma).
 * Artwork: Simple Icons (CC0-1.0). Uptime Kuma is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type UptimeKumaLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#5cdd8b" viewBox="0 0 24 24" {...props}><path d="M11.759.955c-4.071 0-7.93 2.265-10.06 5.774l-.16.263-.116.284c-1.81 4.44-2.188 9.118.621 12.459 2.67 3.174 6.221 3.328 9.477 3.308s6.323-.482 8.995-2.032C22.75 19.714 24 16.917 24 14.53c0-2.388-.724-4.698-1.882-7.343l-.112-.257-.148-.238C19.683 3.2 15.83.955 11.758.955Zm0 3.868q4.378 0 6.816 3.914 3.114 7.121 0 8.929c-3.116 1.808-11.234 2.359-13.57-.42q-2.337-2.78 0-8.51 2.376-3.913 6.754-3.913" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="M11.759.955c-4.071 0-7.93 2.265-10.06 5.774l-.16.263-.116.284c-1.81 4.44-2.188 9.118.621 12.459 2.67 3.174 6.221 3.328 9.477 3.308s6.323-.482 8.995-2.032C22.75 19.714 24 16.917 24 14.53c0-2.388-.724-4.698-1.882-7.343l-.112-.257-.148-.238C19.683 3.2 15.83.955 11.758.955Zm0 3.868q4.378 0 6.816 3.914 3.114 7.121 0 8.929c-3.116 1.808-11.234 2.359-13.57-.42q-2.337-2.78 0-8.51 2.376-3.913 6.754-3.913" /></svg>;

export function UptimeKumaLogo({
  variant = "color",
  title = "Uptime Kuma",
  className,
  ...props
}: UptimeKumaLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default UptimeKumaLogo;
