/**
 * V logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/v).
 * Artwork: gilbarbara/logos (CC0-1.0). V is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type VLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 253" {...props}><defs><path id="v-a" d="m5.614.039 68.178 6.568c4.325.417 9.001 4.084 10.437 8.185l43.851 125.291 43.638-125.287c1.397-4.014 5.899-7.613 10.142-8.158l.283-.031L250.32.039c4.326-.417 6.643 2.564 5.173 6.653l-86.696 241.083-.413 1.147c-.47 1.308-1.605 2.458-2.93 3.117-.483.372-1.136.587-1.919.587h-66.78q-.124 0-.246-.003l.246.003a9 9 0 0 1-.493-.014c-4.203-.237-8.629-3.459-10.043-7.394L.442 6.692c-1.47-4.089.847-7.07 5.172-6.653" /><path id="v-c" d="m158.907 248.922-36.096-104.274 5.156-3.223 36.741 106.35z" /><filter id="v-d" width="181.4%" height="132.2%" x="-40.2%" y="-14.9%" filterUnits="objectBoundingBox"><feMorphology in="SourceAlpha" operator="dilate" radius={2} result="shadowSpreadOuter1" /><feOffset dy={2} in="shadowSpreadOuter1" result="shadowOffsetOuter1" /><feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation={3} /><feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.3 0" /></filter></defs><mask id="v-b" fill="#fff"><use xlinkHref="#v-a" /></mask><path fill="#536b8a" d="M168.797 247.775 255.493 6.692c1.47-4.089-.847-7.07-5.173-6.653l-68.177 6.568c-4.325.417-8.997 4.086-10.425 8.189L91.473 245.193c-1.43 4.102.937 7.433 5.282 7.433h66.36c2.173 0 4.534-1.659 5.269-3.704z" mask="url(#v-b)" /><g mask="url(#v-b)"><use xlinkHref="#v-c" filter="url(#v-d)" /></g><path fill="#5d87bf" d="m5.614.039 68.178 6.568c4.325.417 9.001 4.084 10.437 8.185l81.943 234.12c.717 2.05-.464 3.714-2.637 3.714h-66.78c-4.345 0-9.066-3.319-10.536-7.408L.442 6.692c-1.47-4.089.847-7.07 5.172-6.653" mask="url(#v-b)" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 253" {...props}><defs><path id="v-a-mono" d="m5.614.039 68.178 6.568c4.325.417 9.001 4.084 10.437 8.185l43.851 125.291 43.638-125.287c1.397-4.014 5.899-7.613 10.142-8.158l.283-.031L250.32.039c4.326-.417 6.643 2.564 5.173 6.653l-86.696 241.083-.413 1.147c-.47 1.308-1.605 2.458-2.93 3.117-.483.372-1.136.587-1.919.587h-66.78q-.124 0-.246-.003l.246.003a9 9 0 0 1-.493-.014c-4.203-.237-8.629-3.459-10.043-7.394L.442 6.692c-1.47-4.089.847-7.07 5.172-6.653" /><path id="v-c-mono" d="m158.907 248.922-36.096-104.274 5.156-3.223 36.741 106.35z" /><filter id="v-d-mono" width="181.4%" height="132.2%" x="-40.2%" y="-14.9%" filterUnits="objectBoundingBox"><feMorphology in="SourceAlpha" operator="dilate" radius={2} result="shadowSpreadOuter1" /><feOffset dy={2} in="shadowSpreadOuter1" result="shadowOffsetOuter1" /><feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation={3} /><feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.3 0" /></filter></defs><mask id="v-b-mono" fill="#fff"><use xlinkHref="#v-a-mono" /></mask><path fill="currentColor" d="M168.797 247.775 255.493 6.692c1.47-4.089-.847-7.07-5.173-6.653l-68.177 6.568c-4.325.417-8.997 4.086-10.425 8.189L91.473 245.193c-1.43 4.102.937 7.433 5.282 7.433h66.36c2.173 0 4.534-1.659 5.269-3.704z" mask="url(#v-b-mono)" /><g mask="url(#v-b-mono)"><use xlinkHref="#v-c-mono" filter="url(#v-d-mono)" /></g><path fill="currentColor" d="m5.614.039 68.178 6.568c4.325.417 9.001 4.084 10.437 8.185l81.943 234.12c.717 2.05-.464 3.714-2.637 3.714h-66.78c-4.345 0-9.066-3.319-10.536-7.408L.442 6.692c-1.47-4.089.847-7.07 5.172-6.653" mask="url(#v-b-mono)" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 253" {...props}><defs><path id="v-a-dark" d="m5.614.039 68.178 6.568c4.325.417 9.001 4.084 10.437 8.185l43.851 125.291 43.638-125.287c1.397-4.014 5.899-7.613 10.142-8.158l.283-.031L250.32.039c4.326-.417 6.643 2.564 5.173 6.653l-86.696 241.083-.413 1.147c-.47 1.308-1.605 2.458-2.93 3.117-.483.372-1.136.587-1.919.587h-66.78q-.124 0-.246-.003l.246.003a9 9 0 0 1-.493-.014c-4.203-.237-8.629-3.459-10.043-7.394L.442 6.692c-1.47-4.089.847-7.07 5.172-6.653" /><path id="v-c-dark" d="m158.907 248.922-36.096-104.274 5.156-3.223 36.741 106.35z" /><filter id="v-d-dark" width="181.4%" height="132.2%" x="-40.2%" y="-14.9%" filterUnits="objectBoundingBox"><feMorphology in="SourceAlpha" operator="dilate" radius={2} result="shadowSpreadOuter1" /><feOffset dy={2} in="shadowSpreadOuter1" result="shadowOffsetOuter1" /><feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation={3} /><feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.3 0" /></filter></defs><mask id="v-b-dark" fill="#fff"><use xlinkHref="#v-a-dark" /></mask><path fill="#536b8a" d="M168.797 247.775 255.493 6.692c1.47-4.089-.847-7.07-5.173-6.653l-68.177 6.568c-4.325.417-8.997 4.086-10.425 8.189L91.473 245.193c-1.43 4.102.937 7.433 5.282 7.433h66.36c2.173 0 4.534-1.659 5.269-3.704z" mask="url(#v-b-dark)" /><g mask="url(#v-b-dark)"><use xlinkHref="#v-c-dark" filter="url(#v-d-dark)" /></g><path fill="#5d87bf" d="m5.614.039 68.178 6.568c4.325.417 9.001 4.084 10.437 8.185l81.943 234.12c.717 2.05-.464 3.714-2.637 3.714h-66.78c-4.345 0-9.066-3.319-10.536-7.408L.442 6.692c-1.47-4.089.847-7.07 5.172-6.653" mask="url(#v-b-dark)" /></svg>;

export function VLogo({
  variant = "color",
  mode = "auto",
  title = "V",
  className,
  ...props
}: VLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "not-dark:hidden")} />
    </>
  );
}

export default VLogo;
