/**
 * Vault logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/vault).
 * Artwork: gilbarbara/logos (CC0-1.0). Vault is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type VaultLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 256" {...props}><path fill="#ffd814" d="m0 0 127.56 256L256 0zm142.698 51.384h14.859v14.859h-14.859zm-29.557 59.354H98.323V95.92h14.818zm0-22.267H98.323V73.692h14.818zm0-22.228H98.323V51.384h14.818zm22.428 66.763h-14.818v-14.858h14.818zm0-22.268h-14.818V95.92h14.818zm0-22.267h-14.818V73.692h14.818zm0-22.228h-14.818V51.384h14.818zm7.13 7.45h14.858V88.51h-14.859zm0 37.085V95.96h14.858v14.818z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m0 0 11.955 24L24 0zm13.366 4.827h1.393v1.38h-1.393zm-2.77 5.569H9.22V8.993h1.389zm0-2.087H9.22V6.906h1.389zm0-2.086H9.22V4.819h1.389zm2.087 6.263h-1.377V11.08h1.388zm0-2.09h-1.377V8.993h1.388zm0-2.087h-1.377V6.906h1.388zm0-2.086h-1.377V4.819h1.388zm.683.683h1.393v1.389h-1.393zm0 3.475V8.993h1.389v1.388Z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 158" {...props}><path d="M283.432 27.369h19.545l-29.787 99.48h-27.764l-29.614-99.406h19.546l24.037 82.846zm73.791 99.48h-14.807l-1.357-4.937a39.8 39.8 0 0 1-21.644 6.417c-13.277 0-18.953-9.107-18.953-21.643 0-14.807 6.417-20.459 21.2-20.459h17.472v-7.65c0-8.07-2.246-10.908-13.894-10.908-6.772.068-13.518.82-20.138 2.246l-2.246-13.895a95.5 95.5 0 0 1 24.925-3.43c22.828 0 29.615 8.07 29.615 26.283zM339.035 99.38h-13.45c-5.972 0-7.6 1.653-7.6 7.181 0 4.936 1.628 7.404 7.403 7.404a28.9 28.9 0 0 0 13.746-3.727zm46.87-45.285v50.739c0 3.874 1.628 5.824 5.824 5.824s12.339-2.69 18.953-6.12V54.096h18.213v72.752H415l-1.777-6.12a72.65 72.65 0 0 1-29.121 7.626c-12.092 0-16.411-8.515-16.411-21.496V54.096zm52.681 72.752V24.382l18.213-2.467v104.933zm72.526-1.407a50.9 50.9 0 0 1-15.968 2.838c-13.277 0-20.014-6.268-20.014-19.249V68.557h-10.883V54.096h10.883V36.03l18.213-2.468V54.17H512l-1.185 14.461h-17.472v38.005a5.73 5.73 0 0 0 3.939 6.205 5.8 5.8 0 0 0 2.625.212 34.4 34.4 0 0 0 9.107-1.506z" /><path fill="#ffd814" d="m0 0 78.601 157.746L157.746 0zm87.93 31.663h9.156v9.155H87.93zM69.717 68.236h-9.131v-9.13h9.131zm0-13.72h-9.131v-9.107h9.131zm0-13.698h-9.131v-9.155h9.131zm13.82 41.14h-9.13v-9.156h9.13zm0-13.722h-9.13v-9.13h9.13zm0-13.72h-9.13v-9.107h9.13zm0-13.698h-9.13v-9.155h9.13zm4.393 4.59h9.156v9.132H87.93zm0 22.853V59.13h9.156v9.131z" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 158" {...props}><path d="M283.432 27.369h19.545l-29.787 99.48h-27.764l-29.614-99.406h19.546l24.037 82.846zm73.791 99.48h-14.807l-1.357-4.937a39.8 39.8 0 0 1-21.644 6.417c-13.277 0-18.953-9.107-18.953-21.643 0-14.807 6.417-20.459 21.2-20.459h17.472v-7.65c0-8.07-2.246-10.908-13.894-10.908-6.772.068-13.518.82-20.138 2.246l-2.246-13.895a95.5 95.5 0 0 1 24.925-3.43c22.828 0 29.615 8.07 29.615 26.283zM339.035 99.38h-13.45c-5.972 0-7.6 1.653-7.6 7.181 0 4.936 1.628 7.404 7.403 7.404a28.9 28.9 0 0 0 13.746-3.727zm46.87-45.285v50.739c0 3.874 1.628 5.824 5.824 5.824s12.339-2.69 18.953-6.12V54.096h18.213v72.752H415l-1.777-6.12a72.65 72.65 0 0 1-29.121 7.626c-12.092 0-16.411-8.515-16.411-21.496V54.096zm52.681 72.752V24.382l18.213-2.467v104.933zm72.526-1.407a50.9 50.9 0 0 1-15.968 2.838c-13.277 0-20.014-6.268-20.014-19.249V68.557h-10.883V54.096h10.883V36.03l18.213-2.468V54.17H512l-1.185 14.461h-17.472v38.005a5.73 5.73 0 0 0 3.939 6.205 5.8 5.8 0 0 0 2.625.212 34.4 34.4 0 0 0 9.107-1.506z" /><path fill="#ffd814" d="m0 0 78.601 157.746L157.746 0zm87.93 31.663h9.156v9.155H87.93zM69.717 68.236h-9.131v-9.13h9.131zm0-13.72h-9.131v-9.107h9.131zm0-13.698h-9.131v-9.155h9.131zm13.82 41.14h-9.13v-9.156h9.13zm0-13.722h-9.13v-9.13h9.13zm0-13.72h-9.13v-9.107h9.13zm0-13.698h-9.13v-9.155h9.13zm4.393 4.59h9.156v9.132H87.93zm0 22.853V59.13h9.156v9.131z" /></svg>;

export function VaultLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "Vault",
  className,
  ...props
}: VaultLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default VaultLogo;
