/**
 * webpack logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/webpack).
 * Artwork: gilbarbara/logos (CC0-1.0). webpack is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type WebpackLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 290" {...props}><path fill="#fff" d="m128 .048 128 72.405V217.31l-128 72.405L0 217.31V72.453z" /><path fill="#8ed6fb" d="m233.153 212.287-100.902 57.14V224.99l62.889-34.632zm6.907-6.231V86.654l-36.902 21.3v76.8zm-217.6 6.23 100.903 57.094v-44.438l-62.889-34.584zm-6.907-6.23V86.654l36.903 21.3v76.8zm4.3-127.13 103.51-58.543v42.99L57.045 99.84l-.532.29zm215.86 0L132.251 20.382v42.99l66.27 36.515.531.29z" /><path fill="#1c78c0" d="m123.363 214.847-62.02-34.15v-67.574l62.02 35.792zm8.888 0 62.02-34.101v-67.623l-62.02 35.792zM65.497 105.298l62.31-34.246 62.26 34.246-62.26 35.937z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 290" {...props}><defs><mask id="webpack-mono-cut-mono" maskUnits="userSpaceOnUse" x={0} y={0} width={256} height={290}><g fill="#000"><path fill="#fff" d="m128 .048 128 72.405V217.31l-128 72.405L0 217.31V72.453z" /><path fill="#000" d="m233.153 212.287-100.902 57.14V224.99l62.889-34.632zm6.907-6.231V86.654l-36.902 21.3v76.8zm-217.6 6.23 100.903 57.094v-44.438l-62.889-34.584zm-6.907-6.23V86.654l36.903 21.3v76.8zm4.3-127.13 103.51-58.543v42.99L57.045 99.84l-.532.29zm215.86 0L132.251 20.382v42.99l66.27 36.515.531.29z" /><path fill="#000" d="m123.363 214.847-62.02-34.15v-67.574l62.02 35.792zm8.888 0 62.02-34.101v-67.623l-62.02 35.792zM65.497 105.298l62.31-34.246 62.26 34.246-62.26 35.937z" /></g></mask></defs><rect x={0} y={0} width={256} height={290} fill="currentColor" mask="url(#webpack-mono-cut-mono)" /></svg>;

export function WebpackLogo({
  variant = "color",
  title = "webpack",
  className,
  ...props
}: WebpackLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default WebpackLogo;
