/**
 * WebSocket logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/websocket).
 * Artwork: gilbarbara/logos (CC0-1.0). WebSocket is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type WebsocketLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 193" {...props}><path fill="#231f20" d="M192.44 144.645h31.78V68.339l-35.805-35.804-22.472 22.472 26.497 26.497zm31.864 15.931H113.452L86.954 134.08l11.237-11.236 21.885 21.885h45.028l-44.357-44.441 11.32-11.32 44.357 44.358v-45.03l-21.801-21.801 11.152-11.153L110.685 0H0l31.696 31.696v.084h65.74l23.227 23.227-33.96 33.96L63.476 65.74V47.712h-31.78v31.193l55.007 55.007L64.314 156.3l35.805 35.805H256z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 193" {...props}><path fill="currentColor" d="M192.44 144.645h31.78V68.339l-35.805-35.804-22.472 22.472 26.497 26.497zm31.864 15.931H113.452L86.954 134.08l11.237-11.236 21.885 21.885h45.028l-44.357-44.441 11.32-11.32 44.357 44.358v-45.03l-21.801-21.801 11.152-11.153L110.685 0H0l31.696 31.696v.084h65.74l23.227 23.227-33.96 33.96L63.476 65.74V47.712h-31.78v31.193l55.007 55.007L64.314 156.3l35.805 35.805H256z" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 256 193" {...props}><path fill="#ffffff" d="M192.44 144.645h31.78V68.339l-35.805-35.804-22.472 22.472 26.497 26.497zm31.864 15.931H113.452L86.954 134.08l11.237-11.236 21.885 21.885h45.028l-44.357-44.441 11.32-11.32 44.357 44.358v-45.03l-21.801-21.801 11.152-11.153L110.685 0H0l31.696 31.696v.084h65.74l23.227 23.227-33.96 33.96L63.476 65.74V47.712h-31.78v31.193l55.007 55.007L64.314 156.3l35.805 35.805H256z" /></svg>;

export function WebsocketLogo({
  variant = "color",
  mode = "auto",
  title = "WebSocket",
  className,
  ...props
}: WebsocketLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default WebsocketLogo;
