/**
 * YAML logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/yaml).
 * Artwork: Simple Icons (CC0-1.0). YAML is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type YamlLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */
  variant?: "color" | "mono";
  /** "icon" (the mark) or "wordmark" (the full lockup). */
  type?: "icon" | "wordmark";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="#cb171e" viewBox="0 0 24 24" {...props}><path d="m0 .97 4.111 6.453v4.09h2.638v-4.09L11.053.969H8.214L5.58 5.125 2.965.969Zm12.093.024-4.47 10.544h2.114l.97-2.345h4.775l.804 2.345h2.26L14.255.994Zm1.133 2.225 1.463 3.87h-3.096zm3.06 9.475v10.29H24v-2.199h-5.454v-8.091zm-12.175.002v10.335h2.217v-7.129l2.32 4.792h1.746l2.4-4.96v7.295h2.127V12.696h-2.904L9.44 17.37l-2.455-4.674Z" /></svg>;

const IconMono = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" {...props}><path d="m0 .97 4.111 6.453v4.09h2.638v-4.09L11.053.969H8.214L5.58 5.125 2.965.969Zm12.093.024-4.47 10.544h2.114l.97-2.345h4.775l.804 2.345h2.26L14.255.994Zm1.133 2.225 1.463 3.87h-3.096zm3.06 9.475v10.29H24v-2.199h-5.454v-8.091zm-12.175.002v10.335h2.217v-7.129l2.32 4.792h1.746l2.4-4.96v7.295h2.127V12.696h-2.904L9.44 17.37l-2.455-4.674Z" /></svg>;

const Wordmark = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 176" {...props}><path fill="#fff" d="M117.109.803h297.05v28.902l96.34 144.511H1.5z" /><path d="M414.962 0H116.68L0 175.019h512L414.962 29.46zm-1.606 1.606v28.342L509 173.413H3L117.539 1.606z" /><path stroke="#000" d="M117.109.803h38.536L40.036 174.216H1.5l57.805-86.707L1.5.803h38.536l38.537 57.804zM49.67 174.216h38.537l77.072-115.609v115.609h38.536V.803H165.28zm162.174 0h38.536V58.607l38.536 57.805 38.537-57.805v115.609h38.536V.803h-48.17l-28.903 57.804L250.38.803h-38.536zm163.779 0H510.5l-25.691-38.536h-70.65V.803h-38.536z" /></svg>;

const WordmarkDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" viewBox="0 0 512 176" {...props}><path fill="#0a0a0a" d="M117.109.803h297.05v28.902l96.34 144.511H1.5z" /><path d="M414.962 0H116.68L0 175.019h512L414.962 29.46zm-1.606 1.606v28.342L509 173.413H3L117.539 1.606z" /><path stroke="#ffffff" d="M117.109.803h38.536L40.036 174.216H1.5l57.805-86.707L1.5.803h38.536l38.537 57.804zM49.67 174.216h38.537l77.072-115.609v115.609h38.536V.803H165.28zm162.174 0h38.536V58.607l38.536 57.805 38.537-57.805v115.609h38.536V.803h-48.17l-28.903 57.804L250.38.803h-38.536zm163.779 0H510.5l-25.691-38.536h-70.65V.803h-38.536z" /></svg>;

export function YamlLogo({
  variant = "color",
  type = "icon",
  mode = "auto",
  title = "YAML",
  className,
  ...props
}: YamlLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  if (type === "wordmark") {
    return mode === "light" ? (
      <Wordmark {...shared} className={className} />
    ) : mode === "dark" ? (
      <WordmarkDark {...shared} className={className} />
    ) : (
      <>
        <Wordmark {...shared} className={join(className, "dark:hidden")} />
        <WordmarkDark {...shared} className={join(className, "not-dark:hidden")} />
      </>
    );
  }

  if (variant === "mono") return <IconMono {...shared} className={className} />;

  return <Icon {...shared} className={className} />;
}

export default YamlLogo;
