/**
 * Zod logo — generated by Logoforge (https://logoforge.terravidhal.me/logos/zod).
 * Artwork: gilbarbara/logos (CC0-1.0). Zod is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ZodLogoProps = Omit<SVGProps<SVGSVGElement>, "type"> & {
  /** Brand colors, with automatic dark mode. */
  variant?: "color";
  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */
  mode?: "auto" | "light" | "dark";
  /** Accessible name. Pass "" when the logo is decorative. */
  title?: string;
};

const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");

const Icon = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 212" {...props}><defs><linearGradient id="zod-a" x1="50%" x2="50%" y1="100.031%" y2="0%"><stop offset="0%" stopColor="#4669f6" /><stop offset="100%" stopColor="#45a9ff" /></linearGradient><linearGradient id="zod-b" x1="95.049%" x2="10.721%" y1="28.918%" y2="71.593%"><stop offset="0%" stopColor="#fff" stopOpacity={0.6} /><stop offset="30.534%" stopColor="#fff" stopOpacity={0.595} /><stop offset="100%" stopColor="#fff" stopOpacity={0.4} /></linearGradient><linearGradient id="zod-d" x1="78.289%" x2="50%" y1="50%" y2="50%"><stop offset="0%" stopColor="#fff" stopOpacity={0.6} /><stop offset="100%" stopColor="#fff" /></linearGradient><path id="zod-c" d="M137.011 180.305a12.87 12.87 0 0 1-17 .065l-61.216-53.41h138.408z" /></defs><path fill="url(#zod-a)" d="M50.087 0a23.97 23.97 0 0 0-22.526 15.772L1.447 87.494a23.97 23.97 0 0 0 6.828 26.32l105.542 91.458c9.088 7.876 22.606 7.799 31.604-.18l102.51-90.89a23.97 23.97 0 0 0 6.652-26.055l-26.02-72.292A23.97 23.97 0 0 0 206.007 0z" /><path fill="url(#zod-b)" d="M225.397 68.751a13.695 13.695 0 0 1-5.242 16.002L98.71 161.785 58.795 126.96l153.889-93.535z" /><path fill="#fff" d="m212.169 31.997 12.922 35.901H30.786l13.092-35.957A16.38 16.38 0 0 1 59.14 21.167h137.495a16.38 16.38 0 0 1 15.533 10.83" /><use xlinkHref="#zod-c" fill="url(#zod-d)" /></svg>;

const IconDark = (props: SVGProps<SVGSVGElement>) => <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" viewBox="0 0 256 212" {...props}><defs><linearGradient id="zod-a-dark" x1="50%" x2="50%" y1="100.031%" y2="0%"><stop offset="0%" stopColor="#4669f6" /><stop offset="100%" stopColor="#45a9ff" /></linearGradient><linearGradient id="zod-b-dark" x1="95.049%" x2="10.721%" y1="28.918%" y2="71.593%"><stop offset="0%" stopColor="#0a0a0a" stopOpacity={0.6} /><stop offset="30.534%" stopColor="#0a0a0a" stopOpacity={0.595} /><stop offset="100%" stopColor="#0a0a0a" stopOpacity={0.4} /></linearGradient><linearGradient id="zod-d-dark" x1="78.289%" x2="50%" y1="50%" y2="50%"><stop offset="0%" stopColor="#0a0a0a" stopOpacity={0.6} /><stop offset="100%" stopColor="#0a0a0a" /></linearGradient><path id="zod-c-dark" d="M137.011 180.305a12.87 12.87 0 0 1-17 .065l-61.216-53.41h138.408z" /></defs><path fill="url(#zod-a-dark)" d="M50.087 0a23.97 23.97 0 0 0-22.526 15.772L1.447 87.494a23.97 23.97 0 0 0 6.828 26.32l105.542 91.458c9.088 7.876 22.606 7.799 31.604-.18l102.51-90.89a23.97 23.97 0 0 0 6.652-26.055l-26.02-72.292A23.97 23.97 0 0 0 206.007 0z" /><path fill="url(#zod-b-dark)" d="M225.397 68.751a13.695 13.695 0 0 1-5.242 16.002L98.71 161.785 58.795 126.96l153.889-93.535z" /><path fill="#0a0a0a" d="m212.169 31.997 12.922 35.901H30.786l13.092-35.957A16.38 16.38 0 0 1 59.14 21.167h137.495a16.38 16.38 0 0 1 15.533 10.83" /><use xlinkHref="#zod-c-dark" fill="url(#zod-d-dark)" /></svg>;

export function ZodLogo({
  variant = "color",
  mode = "auto",
  title = "Zod",
  className,
  ...props
}: ZodLogoProps) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;

  void variant;

  return mode === "light" ? (
    <Icon {...shared} className={className} />
  ) : mode === "dark" ? (
    <IconDark {...shared} className={className} />
  ) : (
    <>
      <Icon {...shared} className={join(className, "dark:hidden")} />
      <IconDark {...shared} className={join(className, "hidden dark:block not-dark:hidden")} />
    </>
  );
}

export default ZodLogo;
