import { transform } from "@svgr/core";

/**
 * One typed React component per logo, generated from its SVG variants.
 *
 *   <StripeLogo />                     color, switches to its dark file under .dark
 *   <StripeLogo variant="mono" />      currentColor
 *   <StripeLogo type="wordmark" />     when the brand has a wordmark
 *   <StripeLogo title="" />            decorative (aria-hidden)
 *
 * No dependency but React. The light/dark swap uses `dark:hidden` and
 * `not-dark:hidden` (variants, so they win over a user `block`/`flex` class).
 */

type Files = Partial<Record<"icon" | "icon-dark" | "icon-mono" | "wordmark" | "wordmark-dark", string>>;

/** Distinct ids per variant: the same logo may render several variants on one page. */
function suffixIds(svg: string, suffix: string) {
  return svg
    .replace(/\bid="([^"]+)"/g, `id="$1${suffix}"`)
    .replace(/url\(#([^)]+)\)/g, `url(#$1${suffix})`)
    .replace(/href="#([^"]+)"/g, `href="#$1${suffix}"`);
}

async function toJsx(svg: string, name: string) {
  const clean = svg.replace(/<title>[\s\S]*?<\/title>/g, "");
  const code = await transform(
    clean,
    {
      plugins: ["@svgr/plugin-jsx"],
      jsxRuntime: "automatic",
      typescript: true,
      dimensions: false,
      expandProps: "end",
      template: (variables, { tpl }) =>
        tpl`const ${variables.componentName} = (props: SVGProps<SVGSVGElement>) => (${variables.jsx});`,
    },
    { componentName: name },
  );
  return code.trim();
}

const SUFFIX: Record<keyof Files, string> = {
  icon: "",
  "icon-dark": "-dark",
  "icon-mono": "-mono",
  wordmark: "-wm",
  "wordmark-dark": "-wm-dark",
};

const PART: Record<keyof Files, string> = {
  icon: "Icon",
  "icon-dark": "IconDark",
  "icon-mono": "IconMono",
  wordmark: "Wordmark",
  "wordmark-dark": "WordmarkDark",
};

export async function buildComponent(opts: {
  slug: string;
  name: string;
  componentName: string;
  files: Files;
  credit: string;
  siteUrl: string;
}) {
  const { slug, name, componentName, files, credit, siteUrl } = opts;
  const parts: string[] = [];
  for (const [variant, svg] of Object.entries(files) as [keyof Files, string][]) {
    parts.push(await toJsx(suffixIds(svg, SUFFIX[variant]), PART[variant]));
  }

  const hasMono = Boolean(files["icon-mono"]);
  const hasWordmark = Boolean(files.wordmark);
  const hasDark = Boolean(files["icon-dark"] || files["wordmark-dark"]);
  // auto = both files, swapped by the .dark class; light/dark = exactly one file.
  const pair = (light: string, dark?: string, indent = "") =>
    dark
      ? `mode === "light" ? (
    <${light} {...shared} className={className} />
  ) : mode === "dark" ? (
    <${dark} {...shared} className={className} />
  ) : (
    <>
      <${light} {...shared} className={join(className, "dark:hidden")} />
      <${dark} {...shared} className={join(className, "not-dark:hidden")} />
    </>
  )`.replaceAll("\n", `\n${indent}`)
      : `<${light} {...shared} className={className} />`;

  const joinHelper = hasDark
    ? `const join = (...classes: (string | undefined)[]) => classes.filter(Boolean).join(" ");\n\n`
    : "";

  const props = [
    hasMono
      ? `  /** "color" (brand colors, automatic dark mode) or "mono" (currentColor). */\n  variant?: "color" | "mono";`
      : `  /** Brand colors, with automatic dark mode. */\n  variant?: "color";`,
    hasWordmark ? `  /** "icon" (the mark) or "wordmark" (the full lockup). */\n  type?: "icon" | "wordmark";` : "",
    hasDark
      ? '  /** "auto" swaps with your `.dark` class (Tailwind); "light" / "dark" force one file. */\n  mode?: "auto" | "light" | "dark";'
      : "",
    `  /** Accessible name. Pass "" when the logo is decorative. */\n  title?: string;`,
  ].filter(Boolean);

  const defaults = [
    `  variant = "color",`,
    hasWordmark ? `  type = "icon",` : "",
    hasDark ? `  mode = "auto",` : "",
  ].filter(Boolean);

  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

  return `/**
 * ${name} logo — generated by Logoforge (${siteUrl}/logos/${slug}).
 * Artwork: ${credit}. ${name} is a trademark of its respective owner.
 */
import type { SVGProps } from "react";

export type ${componentName}Props = Omit<SVGProps<SVGSVGElement>, "type"> & {
${props.join("\n")}
};

${joinHelper}${parts.join("\n\n")}

export function ${componentName}({
${defaults.join("\n")}
  title = "${esc(name)}",
  className,
  ...props
}: ${componentName}Props) {
  const shared = {
    height: "1em",
    ...(title ? { role: "img", "aria-label": title } : { "aria-hidden": true }),
    ...props,
  } as SVGProps<SVGSVGElement>;
${hasWordmark ? `\n  if (type === "wordmark") {\n    return ${pair("Wordmark", files["wordmark-dark"] ? "WordmarkDark" : undefined, "  ")};\n  }\n` : ""}${hasMono ? `\n  if (variant === "mono") return <IconMono {...shared} className={className} />;\n` : `\n  void variant;\n`}
  return ${pair("Icon", files["icon-dark"] ? "IconDark" : undefined)};
}

export default ${componentName};
`;
}
